$path='E:\Finance-Inzicht\src\Web\src\main.ts';$text=[IO.File]::ReadAllText($path)
$text=$text.Replace("import {CommonModule} from '@angular/common';","import {CommonModule} from '@angular/common';`r`nimport {UI, categoryText, type Language, type TranslationKey} from './i18n';")
$start=$text.IndexOf('  translations:any={');$end=$text.IndexOf('  setLanguage(', $start)
if($start -lt 0 -or $end -lt 0){throw 'Inline translation block missing'}
$setEnd=$text.IndexOf([Environment]::NewLine,$end)
$replacement=@'
  t(key:TranslationKey|string){return (UI[this.language()] as any)[key]||(UI.en as any)[key]||key}
  categoryText(value:string){return value.split(' / ').map(x=>categoryText(x,this.language())).join(' / ')}
  directionText(value:string){return ({Incoming:this.t('incoming'),Outgoing:this.t('outgoing'),'Transfer in':this.t('transferIn'),'Transfer out':this.t('transferOut')} as any)[value]||value}
  setLanguage(event:Event){const value=(event.target as HTMLSelectElement).value as Language;this.language.set(value);localStorage.setItem('finance-language',value)}
'@
$text=$text.Substring(0,$start)+$replacement+$text.Substring($setEnd+2)
$text=$text.Replace("language=signal<'en'|'nl'>((localStorage.getItem('finance-language') as 'en'|'nl')||'en');","language=signal<Language>((localStorage.getItem('finance-language') as Language)||'en');")

$pairs=@(
@('<b>System online</b>','<b>{{t(''systemOnline'')}}</b>'),@('<small>CAMT worker active</small>','<small>{{t(''workerActive'')}}</small>'),@('Calculating your financial overview…','{{t(''calculating'')}}'),
@('<p class="eyebrow">FINANCIAL OVERVIEW</p>','<p class="eyebrow">{{t(''financialOverview'')}}</p>'),@('<p class="eyebrow">CASH FLOW</p>','<p class="eyebrow">{{t(''cashFlowChart'')}}</p>'),@('<p class="eyebrow">SPENDING</p>','<p class="eyebrow">{{t(''spending'')}}</p>'),@('<p class="eyebrow">BALANCE TREND</p>','<p class="eyebrow">{{t(''balanceTrend'')}}</p>'),@('<p class="eyebrow">INCOME</p>','<p class="eyebrow">{{t(''income'')}}</p>'),@('<p class="eyebrow">MONTHLY MONEY FLOW</p>','<p class="eyebrow">{{t(''monthlyMoneyFlowLabel'')}}</p>'),@('<p class="eyebrow">SPENDING PATTERNS</p>','<p class="eyebrow">{{t(''spendingPatterns'')}}</p>'),@('<p class="eyebrow">EXPENSE METRICS</p>','<p class="eyebrow">{{t(''expenseMetrics'')}}</p>'),@('<p class="eyebrow">MERCHANTS</p>','<p class="eyebrow">{{t(''merchants'')}}</p>'),@('<p class="eyebrow">ACCOUNTS</p>','<p class="eyebrow">{{t(''accounts'')}}</p>'),@('<p class="eyebrow">SELECTED INSIGHT</p>','<p class="eyebrow">{{t(''selectedInsight'')}}</p>'),
@('>Cash inflow<','>{{t(''cashInflow'')}}<'),@('>Total spent<','>{{t(''totalSpent'')}}<'),@('>Largest purchase<','>{{t(''largestPurchase'')}}<'),@('>Smallest purchase<','>{{t(''smallestPurchase'')}}<'),@('>Average purchase<','>{{t(''averagePurchase'')}}<'),@('>Negative flow months<','>{{t(''negativeFlowMonths'')}}<'),@('>Less <','>{{t(''less'')}} <'),@('> More<','> {{t(''more'')}}<'),
@('Import more statements to reveal monthly trends.','{{t(''importMoreHistory'')}}'),@('No expenses yet.','{{t(''noExpense'')}}'),@('Balance history will appear here.','{{t(''noBalanceHistory'')}}'),@('No income sources found.','{{t(''noIncomeSources'')}}'),@('Monthly flows appear after transactions are imported.','{{t(''noMonthlyFlows'')}}'),@('No merchant data available.','{{t(''noMerchantData'')}}'),@('<b>Data availability</b>','<b>{{t(''dataAvailability'')}}</b>'),@('Some requested metrics need data that CAMT statements do not contain.','{{t(''dataAvailabilityText'')}}'),
@('<p class="eyebrow">ACCOUNT SETTINGS</p>','<p class="eyebrow">{{t(''accountSettings'')}}</p>'),@('Custom names and account types are stored separately from bank-provided CAMT values.','{{t(''accountSettingsText'')}}'),@('>Current account<','>{{t(''currentAccount'')}}<'),@('>Savings account<','>{{t(''savingsAccount'')}}<'),@('>Credit account<','>{{t(''creditAccount'')}}<'),@('>Investment account<','>{{t(''investmentAccount'')}}<'),@('>Other<','>{{t(''other'')}}<'),
@('<p class="eyebrow">DATA INGESTION</p>','<p class="eyebrow">{{t(''dataIngestion'')}}</p>'),@('Upload one CAMT XML file or a ZIP containing up to 10,000 XML files.','{{t(''uploadText'')}}'),@("{{busy()?'Uploading and creating import jobs…':'Choose or drop an XML / ZIP file'}}","{{busy()?t('uploading'):t('chooseFile')}}"),@('Maximum ZIP size 2 GiB','{{t(''maximumZip'')}}'),@('<p class="eyebrow">IMPORT HISTORY</p>','<p class="eyebrow">{{t(''importHistory'')}}</p>'),@('<th>File</th>','<th>{{t(''file'')}}</th>'),@('<th>Uploaded</th>','<th>{{t(''uploaded'')}}</th>'),@('<th>Status</th>','<th>{{t(''status'')}}</th>'),@('<th>Transactions</th>','<th>{{t(''transactions'')}}</th>'),@('<th>Warnings</th>','<th>{{t(''warnings'')}}</th>'),@('No imports found.','{{t(''noImports'')}}'),
@('<p class="eyebrow">ACCOUNT LEDGER</p>','<p class="eyebrow">{{t(''accountLedger'')}}</p>'),@('Balances are calculated independently for every account. Category changes belong here; Raw Values stays read-only.','{{t(''ledgerText'')}}'),@('matching transactions','{{t(''matchingTransactions'')}}'),@('>All accounts<','>{{t(''allAccounts'')}}<'),@('>All categories<','>{{t(''allCategories'')}}<'),@('>All subcategories<','>{{t(''allSubcategories'')}}<'),@('>Incoming & outgoing<','>{{t(''incomingOutgoing'')}}<'),@('>Incoming<','>{{t(''incoming'')}}<'),@('>Outgoing<','>{{t(''outgoing'')}}<'),@('<b>Balance after transaction</b>','<b>{{t(''balanceAfterTransaction'')}}</b>'),@('Calculated within each account and statement, anchored to the bank-reported opening or closing balance.','{{t(''balanceExplanation'')}}'),@('<th>Booking date</th>','<th>{{t(''bookingDate'')}}</th>'),@('<th>Account</th>','<th>{{t(''account'')}}</th>'),@('<th>Description</th>','<th>{{t(''description'')}}</th>'),@('<th>Category</th>','<th>{{t(''category'')}}</th>'),@('<th>Reference</th>','<th>{{t(''reference'')}}</th>'),@('<th class="right">Debit</th>','<th class="right">{{t(''debit'')}}</th>'),@('<th class="right">Credit</th>','<th class="right">{{t(''credit'')}}</th>'),@('<th class="right">Balance after</th>','<th class="right">{{t(''balanceAfter'')}}</th>'),@('No ledger entries match these filters.','{{t(''noLedgerMatches'')}}'),@('<p class="eyebrow">CATEGORY LABEL</p>','<p class="eyebrow">{{t(''categoryLabel'')}}</p>'),
@('<p class="eyebrow">RAW VALUES</p>','<p class="eyebrow">{{t(''rawValuesLabel'')}}</p>'),@('Select a row to inspect every normalized CAMT field and source reference.','{{t(''rawText'')}}'),@('<th>Booking / value</th>','<th>{{t(''bookingValue'')}}</th>'),@('<th>Counterparty</th>','<th>{{t(''counterparty'')}}</th>'),@('<th>Remittance</th>','<th>{{t(''remittance'')}}</th>'),@('<th class="right">Amount</th>','<th class="right">{{t(''amount'')}}</th>'),@('<dt>Transaction ID</dt>','<dt>{{t(''transactionId'')}}</dt>'),@('<dt>Booking date</dt>','<dt>{{t(''bookingDate'')}}</dt>'),@('<dt>Value date</dt>','<dt>{{t(''valueDate'')}}</dt>'),@('<dt>Amount</dt>','<dt>{{t(''amount'')}}</dt>'),@('<dt>Currency</dt>','<dt>{{t(''currency'')}}</dt>'),@('<dt>Direction</dt>','<dt>{{t(''direction'')}}</dt>'),@('<dt>Status</dt>','<dt>{{t(''status'')}}</dt>'),@('<dt>Imported at</dt>','<dt>{{t(''importedAt'')}}</dt>'),@('<dt>Name</dt>','<dt>{{t(''name'')}}</dt>'),@('<dt>IBAN</dt>','<dt>{{t(''iban'')}}</dt>'),@('<dt>BIC</dt>','<dt>{{t(''bic'')}}</dt>'),@('<dt>Remittance</dt>','<dt>{{t(''remittance'')}}</dt>'),@('<dt>Additional information</dt>','<dt>{{t(''additionalInformation'')}}</dt>'),@('<dt>Entry reference</dt>','<dt>{{t(''entryReference'')}}</dt>'),@('<dt>Servicer reference</dt>','<dt>{{t(''servicerReference'')}}</dt>'),@('<dt>Instruction ID</dt>','<dt>{{t(''instructionId'')}}</dt>'),@('<dt>End-to-end ID</dt>','<dt>{{t(''endToEndId'')}}</dt>'),@('<dt>Mandate ID</dt>','<dt>{{t(''mandateId'')}}</dt>'),@('<dt>Bank transaction ID</dt>','<dt>{{t(''bankTransactionId'')}}</dt>'),@('<dt>External transaction ID</dt>','<dt>{{t(''externalTransactionId'')}}</dt>'),@('<h4>Classification & ownership</h4>','<h4>{{t(''classificationOwnership'')}}</h4>'),@('<dt>Bank transaction code</dt>','<dt>{{t(''bankTransactionCode'')}}</dt>'),@('<dt>Proprietary code</dt>','<dt>{{t(''proprietaryCode'')}}</dt>'),@('<dt>Bank account ID</dt>','<dt>{{t(''bankAccountId'')}}</dt>'),@('<dt>Statement ID</dt>','<dt>{{t(''statementId'')}}</dt>'),@('<dt>Fingerprint</dt>','<dt>{{t(''fingerprint'')}}</dt>'),@('Preserved normalized source metadata','{{t(''sourceMetadata'')}}'),@('No transactions match your search.','{{t(''noTransactionMatches'')}}'),
@('Every incoming and outgoing movement, grouped by category. Transfers between your own accounts are reported separately.','{{t(''monthlyText'')}}'),@('External cash received','{{t(''externalCashReceived'')}}'),@('External spending','{{t(''externalSpending'')}}'),@('Incoming minus outgoing','{{t(''incomingMinusOutgoing'')}}'),@('excluded from result','{{t(''transfersExcluded'')}}'),@('<p class="eyebrow">INTERNAL MOVEMENTS</p>','<p class="eyebrow">{{t(''internalMovements'')}}</p>'),@('Excluded from income and expenses','{{t(''excludedIncomeExpenses'')}}'),@('No incoming transactions this month.','{{t(''noIncomingMonth'')}}'),@('No outgoing transactions this month.','{{t(''noOutgoingMonth'')}}'),@('<th>Date</th>','<th>{{t(''date'')}}</th>'),@('<th>Description / reference</th>','<th>{{t(''descriptionReference'')}}</th>')
)
foreach($pair in $pairs){$text=$text.Replace($pair[0],$pair[1])}

# Translatable placeholders.
$text=$text.Replace('placeholder="For example: Emergency savings"','[placeholder]="t(''accountNamePlaceholder'')"').Replace('placeholder="Counterparty, IBAN, reference or description"','[placeholder]="t(''ledgerSearchPlaceholder'')"').Replace('placeholder="Search counterparty or remittance"','[placeholder]="t(''rawSearchPlaceholder'')"').Replace('placeholder="Any"','[placeholder]="t(''maximumPlaceholder'')"')

# Canonical category values remain English; only their display is localized.
$text=$text.Replace('{{group.name}}</option>','{{categoryText(group.name)}}</option>').Replace('{{sub}}</option>','{{categoryText(sub)}}</option>').Replace("{{x.category||'Miscellaneous'}}","{{categoryText(x.category||'Miscellaneous')}}").Replace("{{x.subcategory||'Other'}}","{{categoryText(x.subcategory||'Other')}}").Replace('{{c.name}}</span>','{{categoryText(c.name)}}</span>').Replace('{{g.category}}</b>','{{categoryText(g.category)}}</b>').Replace('{{g.subcategory}} ·','{{categoryText(g.subcategory)}} ·').Replace('{{g.direction}}</b>','{{directionText(g.direction)}}</b>')

# Runtime messages and enums.
$text=$text.Replace("source===2?'Manual':source===1?'IBAN rule':'Automatic recognition'","source===2?this.t('manual'):source===1?this.t('ibanRule'):this.t('automaticRecognition')")
$text=$text.Replace("this.categoryMessage.set(r.affected+' transaction(s) categorized.')","this.categoryMessage.set(r.affected+' '+this.t('categorySaved'))").Replace("x.error?.error||'Could not save the category.'","x.error?.error||this.t('categorySaveError')")
$text=$text.Replace("this.accountMessage.set('Account settings saved.')","this.accountMessage.set(this.t('accountSaved'))").Replace("x.error?.error||'Could not save account settings.'","x.error?.error||this.t('accountSaveError')")
$text=$text.Replace("'Could not calculate the dashboard.'","this.t('loadDashboardError')").Replace("'Could not load imports.'","this.t('loadImportsError')").Replace("'Could not load the account ledger.'","this.t('loadLedgerError')").Replace("'Could not load transactions.'","this.t('loadTransactionsError')").Replace("'Could not load the monthly overview.'","this.t('loadMonthlyError')")
$text=$text.Replace("return ['Pending','Processing','Completed','Completed with warnings','Failed','Duplicate'][v]||'Unknown'","return [this.t('pending'),this.t('processing'),this.t('completed'),this.t('completedWarnings'),this.t('failed'),this.t('duplicate')][v]||this.t('unknown')")
$text=$text.Replace("return v||'No source metadata preserved.'","return v||this.t('noSourceMetadata')")

[IO.File]::WriteAllText($path,$text,[Text.UTF8Encoding]::new($false))
