namespace FinanceInzicht.Domain;
public enum ImportStatus { Pending, Processing, Completed, CompletedWithWarnings, Failed, Duplicate }
public enum CreditDebitIndicator { Credit, Debit }
public enum BankAccountKind { Current, Savings, Credit, Investment, Other }
public sealed class ImportFile { public Guid Id {get;init;}=Guid.NewGuid(); public required string OriginalFileName {get;init;} public required string ObjectStorageKey {get;init;} public required string Sha256 {get;init;} public long ContentLength {get;init;} public DateTimeOffset UploadedAtUtc {get;init;}=DateTimeOffset.UtcNow; public required string ContentType {get;init;} }
public sealed class ImportJob { public Guid Id {get;init;}=Guid.NewGuid(); public Guid ImportFileId {get;init;} public ImportFile ImportFile {get;set;}=null!; public ImportStatus Status {get;set;}=ImportStatus.Pending; public DateTimeOffset CreatedAtUtc {get;init;}=DateTimeOffset.UtcNow; public DateTimeOffset? StartedAtUtc {get;set;} public DateTimeOffset? CompletedAtUtc {get;set;} public int AttemptCount {get;set;} public string? WorkerId {get;set;} public string? ErrorCode {get;set;} public string? ErrorMessage {get;set;} public string ParserVersion {get;set;}="camt-1"; public List<ImportWarning> Warnings {get;}=[]; }
public sealed class BankAccount { public Guid Id {get;init;}=Guid.NewGuid(); public string? Iban {get;set;} public string? OtherIdentification {get;set;} public required string Currency {get;set;} public string? AccountName {get;set;} public string? DisplayName {get;set;} public BankAccountKind AccountKind {get;set;}=BankAccountKind.Current; public string? ServicerBic {get;set;} public DateTimeOffset CreatedAtUtc {get;init;}=DateTimeOffset.UtcNow; }
public sealed class BankStatement { public Guid Id {get;init;}=Guid.NewGuid(); public Guid ImportJobId {get;init;} public Guid BankAccountId {get;init;} public required string MessageId {get;init;} public required string StatementId {get;init;} public DateTimeOffset? CreatedDateTimeUtc {get;init;} public DateTimeOffset? FromDateTimeUtc {get;init;} public DateTimeOffset? ToDateTimeUtc {get;init;} public decimal? OpeningBookedBalance {get;init;} public decimal? ClosingBookedBalance {get;init;} public required string Currency {get;init;} public required string RawStatementJson {get;init;} }
public sealed class BankTransaction { public Guid Id {get;init;}=Guid.NewGuid(); public Guid BankStatementId {get;init;} public Guid BankAccountId {get;init;} public string? EntryReference {get;init;} public string? AccountServicerReference {get;init;} public string? InstructionId {get;init;} public string? EndToEndId {get;init;} public string? MandateId {get;init;} public string? TransactionId {get;init;} public DateOnly BookingDate {get;init;} public DateOnly? ValueDate {get;init;} public decimal Amount {get;init;} public required string Currency {get;init;} public CreditDebitIndicator CreditDebitIndicator {get;init;} public string? Status {get;init;} public string? BankTransactionCode {get;init;} public string? ProprietaryTransactionCode {get;init;} public string? CounterpartyName {get;init;} public string? CounterpartyIban {get;init;} public string? CounterpartyBic {get;init;} public string? RemittanceInformation {get;init;} public string? AdditionalInformation {get;init;} public required string Fingerprint {get;init;} public required string RawEntryJson {get;init;} public DateTimeOffset CreatedAtUtc {get;init;}=DateTimeOffset.UtcNow; }
public sealed class ImportWarning { public Guid Id {get;init;}=Guid.NewGuid(); public Guid ImportJobId {get;init;} public string? StatementId {get;init;} public string? EntryReference {get;init;} public required string Code {get;init;} public required string Message {get;init;} public string? XmlPath {get;init;} public DateTimeOffset CreatedAtUtc {get;init;}=DateTimeOffset.UtcNow; }
