export type Language = 'en' | 'nl';

export const UI = {
  en: {
    systemOffline:'Server offline', savedDataAvailable:'Saved data is available', offlineMode:'Offline mode', offlineExplanation:'Saved data remains available. Changes will synchronize when the server reconnects.', syncPending:'Synchronization pending', changesWaiting:'change(s) waiting to sync', savedOffline:'Saved offline. This will synchronize automatically.', uploadQueued:'File saved offline and queued for import.', signInUnavailableOffline:'The server is offline. Reopen a previously signed-in session or reconnect to sign in.',
    language:'Language', overview:'Overview', ledger:'Ledger', monthlyOverview:'Monthly overview', yearOverview:'Year overview', rawValues:'Raw values', accounts:'Accounts', imports:'Imports', uploadCamt:'Upload CAMT', personalFinance:'Personal finance', importFiles:'Import files', thisMonth:'This month', currentYear:'This year', lastYear:'Last year', months:'months', dashboardHeadline:'Your money, clearly understood.', currentBalance:'Current balance', netWorth:'Net worth', cashFlow:'Cash flow', monthlyBurnRate:'Monthly burn rate', cashRunway:'Cash runway', transactions:'Transactions', averageTransaction:'Average transaction', incomeVsExpenses:'Income vs expenses', byCategory:'By category', runningBalance:'Running balance', topSources:'Top sources', monthlyMoneyFlow:'External incoming, outgoing and transfers', dailyExpenseActivity:'Daily expense activity', purchaseProfile:'Purchase profile', whereMoneyGoes:'Where your money goes', accountOverview:'Account overview', nameAccounts:'Name and classify accounts', customAccountName:'Custom account name', accountType:'Account type', saveAccount:'Save account', importStatements:'Import bank statements', statementImports:'Statement imports', newImport:'New import', ledgerHeadline:'Filter, review and categorize', account:'Account', category:'Category', subcategory:'Subcategory', direction:'Direction', from:'From', to:'To', minimumAmount:'Minimum amount', maximumAmount:'Maximum amount', search:'Search', clear:'Clear', applyFilters:'Apply filters', saveCategory:'Save category', close:'Close', categorize:'Categorize', rawHeadline:'All CAMT transaction fields', transactionDetail:'Transaction detail', coreTransaction:'Core transaction', counterparty:'Counterparty', bankReferences:'Bank references', monthlyBalanceSheet:'Monthly balance sheet', selectMonth:'Select month', selectYear:'Select year', incoming:'Incoming', outgoing:'Outgoing', netResult:'Net result', ownTransfers:'Own-account transfers', incomeByCategory:'Income by category', spendingByCategory:'Spending by category', transfersOwnAccounts:'Transfers between own accounts', viewInLedger:'View transactions in Ledger', viewLedger:'View ledger', tryAgain:'Try again',
    financialOverview:'Financial overview', updated:'Updated', importedTransactions:'imported transactions', activeAccounts:'active accounts', incomePeriod:'Income', expensesPeriod:'Expenses', savingsPeriod:'Savings', cashInflow:'Cash inflow', savingsRate:'savings rate', totalAssets:'Total assets', positiveMonthStreak:'positive month streak', perDay:'per day', emergencyMonths:'emergency months', outgoingPayments:'outgoing payments', medianExpense:'Median expense', cashFlowChart:'Cash flow', spending:'Spending', balanceTrend:'Balance trend', income:'Income', monthlyMoneyFlowLabel:'Monthly money flow', spendingPatterns:'Spending patterns', expenseMetrics:'Expense metrics', merchants:'Merchants', dataAvailability:'Data availability', dataAvailabilityText:'Some requested metrics need data that CAMT statements do not contain.', noExpense:'No expenses yet.', noIncomeSources:'No income sources found.', noMerchantData:'No merchant data available.', noMonthlyFlows:'Monthly flows appear after transactions are imported.', noBalanceHistory:'Balance history will appear here.', importMoreHistory:'Import more statements to reveal monthly trends.', totalSpent:'Total spent', largestPurchase:'Largest purchase', smallestPurchase:'Smallest purchase', averagePurchase:'Average purchase', negativeFlowMonths:'Negative flow months', less:'Less', more:'More', selectedInsight:'Selected insight',
    accountSettings:'Account settings', accountSettingsText:'Custom names and account types are stored separately from bank-provided CAMT values.', currentAccount:'Current account', savingsAccount:'Savings account', creditAccount:'Credit account', investmentAccount:'Investment account', other:'Other', accountNamePlaceholder:'For example: Emergency savings', accountSaved:'Account settings saved.', accountSaveError:'Could not save account settings.',
    dataIngestion:'Data ingestion', uploadText:'Upload one CAMT XML file or a ZIP containing up to 10,000 XML files.', chooseFile:'Choose or drop an XML / ZIP file', uploading:'Uploading and creating import jobs…', maximumZip:'Maximum ZIP size 2 GiB', uploadFailed:'Upload failed', importHistory:'Import history', file:'File', uploaded:'Uploaded', status:'Status', warnings:'Warnings', noImports:'No imports found.',
    accountLedger:'Account ledger', ledgerText:'Balances are calculated independently for every account. Category changes belong here; Raw Values stays read-only.', matchingTransactions:'matching transactions', allAccounts:'All accounts', allCategories:'All categories', allSubcategories:'All subcategories', incomingOutgoing:'Incoming & outgoing', minimumPlaceholder:'0.00', maximumPlaceholder:'Any', ledgerSearchPlaceholder:'Counterparty, IBAN, reference or description', balanceAfterTransaction:'Balance after transaction', balanceExplanation:'Calculated within each account and statement, anchored to the bank-reported opening or closing balance.', bookingDate:'Booking date', valueDate:'Value date', description:'Description', reference:'Reference', debit:'Debit', credit:'Credit', balanceAfter:'Balance after', noLedgerMatches:'No ledger entries match these filters.', categoryLabel:'Category label', currentSource:'Current source', applyIban:'Apply to all existing and future transactions for', thisIban:'this IBAN', categorySaved:'transaction(s) categorized.', categorySaveError:'Could not save the category.', automaticRecognition:'Automatic recognition', ibanRule:'IBAN rule', manual:'Manual',
    rawValuesLabel:'Raw values', rawText:'Select a row to inspect every normalized CAMT field and source reference.', rawSearchPlaceholder:'Search counterparty or remittance', bookingValue:'Booking / value', remittance:'Remittance', amount:'Amount', unknownCounterparty:'Unknown counterparty', noIban:'No IBAN', noStatus:'No status', transactionId:'Transaction ID', currency:'Currency', importedAt:'Imported at', name:'Name', iban:'IBAN', bic:'BIC', additionalInformation:'Additional information', entryReference:'Entry reference', servicerReference:'Servicer reference', instructionId:'Instruction ID', endToEndId:'End-to-end ID', mandateId:'Mandate ID', bankTransactionId:'Bank transaction ID', externalTransactionId:'External transaction ID', classificationOwnership:'Classification & ownership', bankTransactionCode:'Bank transaction code', proprietaryCode:'Proprietary code', bankAccountId:'Bank account ID', statementId:'Statement ID', fingerprint:'Fingerprint', sourceMetadata:'Preserved normalized source metadata', noSourceMetadata:'No source metadata preserved.', noTransactionMatches:'No transactions match your search.',
    monthlyText:'Every incoming and outgoing movement, grouped by category. Transfers between your own accounts are reported separately.', externalCashReceived:'External cash received', externalSpending:'External spending', incomingMinusOutgoing:'Incoming minus outgoing', transfersExcluded:'excluded from income and expenses', transactionRange:'transactions', incomeCategory:'Income by category', spendingCategory:'Spending by category', internalMovements:'Internal movements', excludedIncomeExpenses:'Excluded from income and expenses', noIncomingMonth:'No incoming transactions this month.', noOutgoingMonth:'No outgoing transactions this month.', date:'Date', descriptionReference:'Description / reference', transferIn:'Transfer in', transferOut:'Transfer out', betweenOwnAccounts:'Between own accounts', previousMonth:'Previous month', nextMonth:'Next month', dailySpending:'Daily spending', spendingTimeline:'Spending through the month', spendingPace:'Spending pace', monthRhythm:'This month’s rhythm', monthElapsed:'month elapsed', averagePerDay:'Average per day', largestDay:'Largest spending day', activeDays:'Active days', spendingCalendar:'Spending calendar', incomeAndSpendingDetails:'Income and spending details', showDetails:'Show details', yearOverviewText:'All twelve months, external cash flow, category patterns and own-account transfers.', previousYear:'Previous year', nextYear:'Next year', annualTrend:'Annual trend', monthlyPerformance:'Monthly performance', allTwelveMonths:'All twelve months', categoryTrends:'Category trends', yearPattern:'Annual pattern', categoryByMonth:'Categories by month', selectCategoryHint:'Select a category to focus its trend', annualDetails:'Annual details',
    systemOnline:'System online', workerActive:'CAMT worker active', calculating:'Calculating your financial overview…', loadDashboardError:'Could not calculate the dashboard.', loadImportsError:'Could not load imports.', loadLedgerError:'Could not load the account ledger.', loadTransactionsError:'Could not load transactions.', loadMonthlyError:'Could not load the monthly overview.', payment:'payment',payments:'payments',day:'day',days:'days',notEnoughHistory:'Not enough history',averageShort:'avg',value:'Value',ownAccount:'Own account',bankAccount:'Bank account',activity:'activity',netSavings:'net savings',cashOutflow:'cash outflow',balanceAcrossAccounts:'Balance across all active accounts',transferExplanation:'Transfers between imported accounts are shown separately and excluded from income and spending.',creditUtilizationUnavailable:'Credit utilization requires credit-limit data',paycheckUnavailable:'Days until next paycheck requires a payroll schedule',paymentMethodUnavailable:'Payment method is not consistently supplied by CAMT',forecastUnavailable:'Forecasts require more history and an explicit forecasting model',pending:'Pending', processing:'Processing', completed:'Completed', completedWarnings:'Completed with warnings', failed:'Failed', duplicate:'Duplicate', unknown:'Unknown', userManagement:'User management', administration:'Administration', usersText:'Create, deactivate, and manage access for local users.', addUser:'Add user', user:'User', administrator:'Administrator', role:'Role', active:'Active', inactive:'Inactive', activate:'Activate', deactivate:'Deactivate', signOut:'Sign out', refresh:'Refresh', toggleNavigation:'Collapse or expand navigation'
  },
  nl: {
    systemOffline:'Server offline', savedDataAvailable:'Opgeslagen gegevens zijn beschikbaar', offlineMode:'Offlinemodus', offlineExplanation:'Opgeslagen gegevens blijven beschikbaar. Wijzigingen worden gesynchroniseerd zodra de server weer bereikbaar is.', syncPending:'Synchronisatie in afwachting', changesWaiting:'wijziging(en) wachten op synchronisatie', savedOffline:'Offline opgeslagen. Dit wordt automatisch gesynchroniseerd.', uploadQueued:'Bestand offline opgeslagen en klaargezet voor import.', signInUnavailableOffline:'De server is offline. Open een eerder aangemelde sessie of maak opnieuw verbinding om aan te melden.',
    language:'Taal', overview:'Overzicht', ledger:'Grootboek', monthlyOverview:'Maandoverzicht', yearOverview:'Jaaroverzicht', rawValues:'Ruwe gegevens', accounts:'Rekeningen', imports:'Imports', uploadCamt:'CAMT uploaden', personalFinance:'Persoonlijke financiën', importFiles:'Bestanden importeren', thisMonth:'Deze maand', currentYear:'Dit jaar', lastYear:'Vorig jaar', months:'maanden', dashboardHeadline:'Uw financiën helder in beeld.', currentBalance:'Huidig saldo', netWorth:'Nettovermogen', cashFlow:'Kasstroom', monthlyBurnRate:'Maandelijkse uitgaven', cashRunway:'Financiële buffer', transactions:'Transacties', averageTransaction:'Gemiddelde transactie', incomeVsExpenses:'Inkomsten versus uitgaven', byCategory:'Per categorie', runningBalance:'Saldoverloop', topSources:'Belangrijkste bronnen', monthlyMoneyFlow:'Externe inkomsten, uitgaven en overboekingen', dailyExpenseActivity:'Dagelijkse uitgaven', purchaseProfile:'Uitgavenprofiel', whereMoneyGoes:'Waar uw geld naartoe gaat', accountOverview:'Rekeningoverzicht', nameAccounts:'Rekeningen benoemen en indelen', customAccountName:'Aangepaste rekeningnaam', accountType:'Rekeningtype', saveAccount:'Rekening opslaan', importStatements:'Bankafschriften importeren', statementImports:'Geïmporteerde afschriften', newImport:'Nieuwe import', ledgerHeadline:'Filteren, controleren en categoriseren', account:'Rekening', category:'Categorie', subcategory:'Subcategorie', direction:'Richting', from:'Van', to:'Tot', minimumAmount:'Minimumbedrag', maximumAmount:'Maximumbedrag', search:'Zoeken', clear:'Wissen', applyFilters:'Filters toepassen', saveCategory:'Categorie opslaan', close:'Sluiten', categorize:'Categoriseren', rawHeadline:'Alle CAMT-transactievelden', transactionDetail:'Transactiedetail', coreTransaction:'Kerngegevens', counterparty:'Tegenpartij', bankReferences:'Bankreferenties', monthlyBalanceSheet:'Maandelijkse balans', selectMonth:'Selecteer maand', selectYear:'Selecteer jaar', incoming:'Inkomsten', outgoing:'Uitgaven', netResult:'Nettoresultaat', ownTransfers:'Overboekingen tussen eigen rekeningen', incomeByCategory:'Inkomsten per categorie', spendingByCategory:'Uitgaven per categorie', transfersOwnAccounts:'Overboekingen tussen eigen rekeningen', viewInLedger:'Transacties in grootboek bekijken', viewLedger:'Grootboek bekijken', tryAgain:'Opnieuw proberen',
    financialOverview:'Financieel overzicht', updated:'Bijgewerkt', importedTransactions:'geïmporteerde transacties', activeAccounts:'actieve rekeningen', incomePeriod:'Inkomsten', expensesPeriod:'Uitgaven', savingsPeriod:'Besparingen', cashInflow:'Geld ontvangen', savingsRate:'spaarpercentage', totalAssets:'Totale bezittingen', positiveMonthStreak:'positieve maanden op rij', perDay:'per dag', emergencyMonths:'buffermaanden', outgoingPayments:'uitgaande betalingen', medianExpense:'Mediane uitgave', cashFlowChart:'Kasstroom', spending:'Uitgaven', balanceTrend:'Saldoverloop', income:'Inkomsten', monthlyMoneyFlowLabel:'Maandelijkse geldstroom', spendingPatterns:'Uitgavenpatronen', expenseMetrics:'Uitgavenkengetallen', merchants:'Handelaren', dataAvailability:'Beschikbaarheid gegevens', dataAvailabilityText:'Sommige gevraagde kengetallen vereisen gegevens die niet in CAMT-afschriften staan.', noExpense:'Nog geen uitgaven.', noIncomeSources:'Geen inkomstenbronnen gevonden.', noMerchantData:'Geen gegevens over handelaren beschikbaar.', noMonthlyFlows:'Maandelijkse geldstromen verschijnen na het importeren van transacties.', noBalanceHistory:'Het saldoverloop verschijnt hier.', importMoreHistory:'Importeer meer afschriften om maandelijkse trends te zien.', totalSpent:'Totaal uitgegeven', largestPurchase:'Grootste aankoop', smallestPurchase:'Kleinste aankoop', averagePurchase:'Gemiddelde aankoop', negativeFlowMonths:'Maanden met negatieve kasstroom', less:'Minder', more:'Meer', selectedInsight:'Geselecteerd inzicht',
    accountSettings:'Rekeninginstellingen', accountSettingsText:'Aangepaste namen en rekeningtypen worden apart van de CAMT-bankgegevens opgeslagen.', currentAccount:'Betaalrekening', savingsAccount:'Spaarrekening', creditAccount:'Kredietrekening', investmentAccount:'Beleggingsrekening', other:'Overig', accountNamePlaceholder:'Bijvoorbeeld: Noodbuffer', accountSaved:'Rekeninginstellingen opgeslagen.', accountSaveError:'Rekeninginstellingen konden niet worden opgeslagen.',
    dataIngestion:'Gegevens importeren', uploadText:'Upload één CAMT XML-bestand of een ZIP met maximaal 10.000 XML-bestanden.', chooseFile:'Kies of sleep een XML- of ZIP-bestand', uploading:'Uploaden en importtaken aanmaken…', maximumZip:'Maximale ZIP-grootte 2 GiB', uploadFailed:'Upload mislukt', importHistory:'Importgeschiedenis', file:'Bestand', uploaded:'Geüpload', status:'Status', warnings:'Waarschuwingen', noImports:'Geen imports gevonden.',
    accountLedger:'Grootboek', ledgerText:'Saldi worden afzonderlijk per rekening berekend. Categorieën beheert u hier; Ruwe gegevens blijft alleen-lezen.', matchingTransactions:'overeenkomende transacties', allAccounts:'Alle rekeningen', allCategories:'Alle categorieën', allSubcategories:'Alle subcategorieën', incomingOutgoing:'Inkomsten en uitgaven', minimumPlaceholder:'0,00', maximumPlaceholder:'Onbeperkt', ledgerSearchPlaceholder:'Tegenpartij, IBAN, referentie of omschrijving', balanceAfterTransaction:'Saldo na transactie', balanceExplanation:'Per rekening en afschrift berekend, verankerd aan het door de bank gemelde begin- of eindsaldo.', bookingDate:'Boekdatum', valueDate:'Valutadatum', description:'Omschrijving', reference:'Referentie', debit:'Af', credit:'Bij', balanceAfter:'Saldo erna', noLedgerMatches:'Geen grootboekregels gevonden met deze filters.', categoryLabel:'Categorielabel', currentSource:'Huidige bron', applyIban:'Toepassen op alle bestaande en toekomstige transacties voor', thisIban:'dit IBAN', categorySaved:'transactie(s) gecategoriseerd.', categorySaveError:'De categorie kon niet worden opgeslagen.', automaticRecognition:'Automatische herkenning', ibanRule:'IBAN-regel', manual:'Handmatig',
    rawValuesLabel:'Ruwe gegevens', rawText:'Selecteer een regel om alle genormaliseerde CAMT-velden en bronreferenties te bekijken.', rawSearchPlaceholder:'Zoek op tegenpartij of omschrijving', bookingValue:'Boek- / valutadatum', remittance:'Betalingsomschrijving', amount:'Bedrag', unknownCounterparty:'Onbekende tegenpartij', noIban:'Geen IBAN', noStatus:'Geen status', transactionId:'Transactie-ID', currency:'Valuta', importedAt:'Geïmporteerd op', name:'Naam', iban:'IBAN', bic:'BIC', additionalInformation:'Aanvullende informatie', entryReference:'Boekingsreferentie', servicerReference:'Bankreferentie', instructionId:'Instructie-ID', endToEndId:'End-to-end-ID', mandateId:'Machtigings-ID', bankTransactionId:'Banktransactie-ID', externalTransactionId:'Extern transactie-ID', classificationOwnership:'Classificatie en herkomst', bankTransactionCode:'Banktransactiecode', proprietaryCode:'Bankeigen code', bankAccountId:'Rekening-ID', statementId:'Afschrift-ID', fingerprint:'Vingerafdruk', sourceMetadata:'Bewaarde genormaliseerde bronmetadata', noSourceMetadata:'Geen bronmetadata bewaard.', noTransactionMatches:'Geen transacties gevonden.',
    monthlyText:'Alle inkomsten en uitgaven, gegroepeerd per categorie. Overboekingen tussen eigen rekeningen staan apart.', externalCashReceived:'Extern ontvangen geld', externalSpending:'Externe uitgaven', incomingMinusOutgoing:'Inkomsten min uitgaven', transfersExcluded:'uitgesloten van inkomsten en uitgaven', transactionRange:'transacties', incomeCategory:'Inkomsten per categorie', spendingCategory:'Uitgaven per categorie', internalMovements:'Interne overboekingen', excludedIncomeExpenses:'Uitgesloten van inkomsten en uitgaven', noIncomingMonth:'Geen inkomsten in deze maand.', noOutgoingMonth:'Geen uitgaven in deze maand.', date:'Datum', descriptionReference:'Omschrijving / referentie', transferIn:'Overboeking in', transferOut:'Overboeking uit', betweenOwnAccounts:'Tussen eigen rekeningen', previousMonth:'Vorige maand', nextMonth:'Volgende maand', dailySpending:'Dagelijkse uitgaven', spendingTimeline:'Uitgaven gedurende de maand', spendingPace:'Uitgaventempo', monthRhythm:'Ritme van deze maand', monthElapsed:'van de maand verstreken', averagePerDay:'Gemiddeld per dag', largestDay:'Grootste uitgavendag', activeDays:'Actieve dagen', spendingCalendar:'Uitgavenkalender', incomeAndSpendingDetails:'Details inkomsten en uitgaven', showDetails:'Details tonen', yearOverviewText:'Alle twaalf maanden, externe kasstroom, categoriepatronen en overboekingen tussen eigen rekeningen.', previousYear:'Vorig jaar', nextYear:'Volgend jaar', annualTrend:'Jaartrend', monthlyPerformance:'Maandprestaties', allTwelveMonths:'Alle twaalf maanden', categoryTrends:'Categorietrends', yearPattern:'Jaarpatroon', categoryByMonth:'Categorieën per maand', selectCategoryHint:'Selecteer een categorie om de trend te bekijken', annualDetails:'Jaardetails',
    systemOnline:'Systeem online', workerActive:'CAMT-verwerker actief', calculating:'Uw financieel overzicht wordt berekend…', loadDashboardError:'Het overzicht kon niet worden berekend.', loadImportsError:'Imports konden niet worden geladen.', loadLedgerError:'Het grootboek kon niet worden geladen.', loadTransactionsError:'Transacties konden niet worden geladen.', loadMonthlyError:'Het maandoverzicht kon niet worden geladen.', payment:'betaling',payments:'betalingen',day:'dag',days:'dagen',notEnoughHistory:'Onvoldoende historie',averageShort:'gem.',value:'Waarde',ownAccount:'Eigen rekening',bankAccount:'Bankrekening',activity:'activiteit',netSavings:'netto besparing',cashOutflow:'uitgaande geldstroom',balanceAcrossAccounts:'Saldo over alle actieve rekeningen',transferExplanation:'Overboekingen tussen geïmporteerde rekeningen worden apart getoond en tellen niet als inkomsten of uitgaven.',creditUtilizationUnavailable:'Kredietbenutting vereist gegevens over de kredietlimiet',paycheckUnavailable:'Dagen tot de volgende salarisbetaling vereist een betaalschema',paymentMethodUnavailable:'De betaalmethode wordt niet consequent in CAMT aangeleverd',forecastUnavailable:'Prognoses vereisen meer historie en een expliciet prognosemodel',pending:'In afwachting', processing:'Wordt verwerkt', completed:'Voltooid', completedWarnings:'Voltooid met waarschuwingen', failed:'Mislukt', duplicate:'Duplicaat', unknown:'Onbekend', userManagement:'Gebruikersbeheer', administration:'Beheer', usersText:'Maak lokale gebruikers aan, deactiveer ze en beheer hun toegang.', addUser:'Gebruiker toevoegen', user:'Gebruiker', administrator:'Beheerder', role:'Rol', active:'Actief', inactive:'Inactief', activate:'Activeren', deactivate:'Deactiveren', signOut:'Afmelden', refresh:'Vernieuwen', toggleNavigation:'Navigatie in- of uitklappen'
  }
} as const;

export type TranslationKey = keyof typeof UI.en;

export const CATEGORY_NL: Record<string,string> = {
  'Income':'Inkomsten','Work Income':'Inkomen uit werk','Salary':'Salaris','Bonus':'Bonus','Freelance Income':'Freelance-inkomen','Benefits':'Uitkeringen','Pension':'Pensioen','Interest':'Rente','Dividends':'Dividend','Refunds':'Terugbetalingen','Other Income':'Overige inkomsten',
  'Housing':'Wonen','Rent/Mortgage':'Huur/Hypotheek','Property Tax':'Onroerendezaakbelasting','Home Insurance':'Woonverzekering','Maintenance & Repairs':'Onderhoud en reparaties','Furniture & Home Decor':'Meubels en woninginrichting',
  'Utilities':'Vaste lasten','Electricity':'Elektriciteit','Gas':'Gas','Water':'Water','Internet':'Internet','Mobile Phone':'Mobiele telefoon','Streaming Services':'Streamingdiensten',
  'Food':'Eten','Groceries':'Boodschappen','Restaurants':'Restaurants','Coffee & Snacks':'Koffie en snacks','Food Delivery':'Maaltijdbezorging',
  'Transportation':'Vervoer','Fuel':'Brandstof','Public Transport':'Openbaar vervoer','Car Payment':'Autofinanciering','Car Insurance':'Autoverzekering','Maintenance':'Onderhoud','Parking & Tolls':'Parkeren en tol',
  'Health':'Gezondheid','Health Insurance':'Zorgverzekering','Doctor & Dentist':'Arts en tandarts','Pharmacy':'Apotheek','Gym':'Sportschool','Mental Health':'Geestelijke gezondheid',
  'Shopping':'Winkelen','Clothing':'Kleding','Electronics':'Elektronica','Household Items':'Huishoudelijke artikelen','Personal Care':'Persoonlijke verzorging',
  'Entertainment':'Entertainment','Movies':'Films','Gaming':'Games','Hobbies':'Hobby’s','Events':'Evenementen','Subscriptions':'Abonnementen',
  'Travel':'Reizen','Flights':'Vluchten','Hotels':'Hotels','Transport':'Vervoer','Activities':'Activiteiten','Travel Insurance':'Reisverzekering',
  'Education':'Opleiding','Courses':'Cursussen','Books':'Boeken','Certifications':'Certificeringen','School Expenses':'Schoolkosten',
  'Financial':'Financieel','Savings':'Sparen','Investments':'Beleggingen','Emergency Fund':'Noodbuffer','Loan Payments':'Aflossingen','Credit Card Payments':'Creditcardbetalingen','Bank Fees':'Bankkosten',
  'Gifts & Donations':'Cadeaus en donaties','Gifts':'Cadeaus','Charity':'Goede doelen','Special Occasions':'Bijzondere gelegenheden',
  'Family & Kids':'Gezin en kinderen','Childcare':'Kinderopvang','School Supplies':'Schoolspullen','Toys':'Speelgoed','Allowance':'Zakgeld',
  'Pets':'Huisdieren','Vet':'Dierenarts','Grooming':'Verzorging','Supplies':'Benodigdheden',
  'Work':'Werk','Office Supplies':'Kantoorartikelen','Business Expenses':'Zakelijke uitgaven','Professional Memberships':'Beroepslidmaatschappen',
  'Miscellaneous':'Overig','Taxes':'Belastingen','Government Fees':'Overheidsheffingen','Unexpected Expenses':'Onverwachte uitgaven','Other':'Overig','Transfers':'Overboekingen','Between own accounts':'Tussen eigen rekeningen'
};

export function categoryText(value:string, language:Language):string {
  return language === 'nl' ? CATEGORY_NL[value] ?? value : value;
}
