import {Component, computed, inject, OnInit, signal} from '@angular/core';
import {bootstrapApplication} from '@angular/platform-browser';
import {HttpClient, HttpInterceptorFn, provideHttpClient, withInterceptors} from '@angular/common/http';
import {CommonModule} from '@angular/common';
import {UI, categoryText, type Language, type TranslationKey} from './i18n';

type CategoryGroup={name:string;subcategories:string[]};
type ImportRow={id:string;originalFileName:string;status:number;createdAtUtc:string;transactionCount:number;warningCount:number};
type Tx={id:string;bankStatementId:string;bankAccountId:string;externalTransactionId?:string;entryReference?:string;accountServicerReference?:string;instructionId?:string;endToEndId?:string;mandateId?:string;transactionId?:string;bookingDate:string;valueDate?:string;amount:number;currency:string;creditDebitIndicator:number;status?:string;bankTransactionCode?:string;proprietaryTransactionCode?:string;counterpartyName?:string;counterpartyIban?:string;counterpartyBic?:string;remittanceInformation?:string;additionalInformation?:string;fingerprint:string;rawEntryJson:string;createdAtUtc:string;balanceAfterTransaction:number;category?:string;subcategory?:string;categorySource?:number};
type Point={period?:string;date?:string;label?:string;income:number;expenses:number;net:number;transferIn?:number;transferOut?:number;externalIncoming?:number;externalOutgoing?:number};
type Named={name:string;total:number;count:number;average?:number;percent?:number};
type Analytics={generatedAtUtc:string;dataAsOf?:string;selectedMonths?:number;rangeStart?:string;currency:string;kpis:any;monthly:Point[];daily:Point[];weeks:Point[];runningBalance:{date:string;balance:number}[];categories:Named[];merchants:Named[];incomeSources:Named[];heatmap:{date:string;value:number;count:number}[];accounts:any[];unavailable:string[]};
type PeriodDay={date:string;income:number;outgoing:number;net:number;count:number;transactions:any[]};
type PeriodCategory={name:string;total:number;count:number;largest:number;transactions:any[]};
type YearMonth={period:string;income:number;outgoing:number;net:number;transferIn:number;transferOut:number;count:number};

@Component({selector:'app-root',standalone:true,imports:[CommonModule],template:`
<section *ngIf="!authUser()" class="login-page"><div class="login-card"><div class="brand"><span class="brandmark">F</span><span>Finance<br><b>Inzicht</b></span></div><p class="eyebrow">{{setupRequired()?'First-time setup':'Secure sign in'}}</p><h1>{{setupRequired()?'Create administrator':'Welcome back'}}</h1><p class="muted">{{setupRequired()?'Create the first local administrator to protect your financial data.':'Sign in to continue to your private financial dashboard.'}}</p><label *ngIf="setupRequired()">Name<input #setupName autocomplete="name" placeholder="Your name" (input)="setupDisplayName.set(setupName.value)"></label><label>Email<input #loginEmail type="email" autocomplete="email" placeholder="you@example.com"></label><label>Password<input #loginPassword type="password" autocomplete="current-password" placeholder="At least 12 characters"></label><p *ngIf="authError()" class="alert error">{{authError()}}</p><button class="upload-btn" [disabled]="authBusy()" (click)="setupRequired()?bootstrap(setupDisplayName()||loginEmail.value.split('@')[0],loginEmail.value,loginPassword.value):login(loginEmail.value,loginPassword.value)">{{authBusy()?'Please wait…':(setupRequired()?'Create administrator':'Sign in')}}</button></div></section>
<div class="shell" *ngIf="authUser()" [class.compact]="sidebarCompact()">
  <aside>
    <div class="brand"><span class="brandmark">F</span><span>Finance<br><b>Inzicht</b></span><button class="sidebar-toggle" [title]="t('toggleNavigation')" (click)="toggleSidebar()">☰</button></div>
    <nav>
      <button class="core-nav" [class.active]="tab()==='dashboard'" (click)="mobileMenuOpen.set(false);showDashboard()"><span>⌂</span> {{t('overview')}}</button>
      <button class="core-nav" [class.active]="tab()==='monthly'" (click)="mobileMenuOpen.set(false);loadMonthlyOverview()"><span>▤</span> {{t('monthlyOverview')}}</button>
      <button class="core-nav" [class.active]="tab()==='year'" (click)="mobileMenuOpen.set(false);loadYearOverview()"><span>▥</span> {{t('yearOverview')}}</button>
      <div class="secondary-nav-group" [class.open]="mobileMenuOpen()">
        <button [class.active]="tab()==='ledger'" (click)="mobileMenuOpen.set(false);loadLedger()"><span>≋</span> {{t('ledger')}}</button>
        <button [class.active]="tab()==='transactions'" (click)="mobileMenuOpen.set(false);loadTransactions()"><span>↕</span> {{t('rawValues')}}</button>
        <button [class.active]="tab()==='accounts'" (click)="mobileMenuOpen.set(false);showAccounts()"><span>▦</span> {{t('accounts')}}</button>
        <button [class.active]="tab()==='imports'" (click)="mobileMenuOpen.set(false);loadImports()"><span>⇩</span> {{t('imports')}}</button>
        <button [class.active]="tab()==='import'" (click)="mobileMenuOpen.set(false);tab.set('import')"><span>＋</span> {{t('uploadCamt')}}</button>
        <button *ngIf="isAdmin()" [class.active]="tab()==='users'" (click)="mobileMenuOpen.set(false);loadUsers()"><span>♙</span> {{t('userManagement')}}</button>
      </div>
      <button class="mobile-more-button" [class.active]="mobileMenuOpen()" (click)="mobileMenuOpen.update(value=>!value)" [attr.aria-expanded]="mobileMenuOpen()"><span>•••</span> {{t('more')}}</button>
    </nav>
    <div class="side-note"><span class="pulse"></span><div><b>{{t('systemOnline')}}</b><small>{{t('workerActive')}}</small></div></div>
  </aside>

  <div class="workspace">
    <header><div><small>{{t('personalFinance')}}</small><h1>{{title()}}</h1></div><div class="header-actions"><label class="language-switch"><span>{{t('language')}}</span><select [value]="language()" (change)="setLanguage($event)"><option value="en">English</option><option value="nl">Nederlands</option></select></label><button class="icon-btn refresh-btn" [title]="t('refresh')" (click)="refresh()">↻</button><button class="profile-chip" [title]="t('signOut')" (click)="logout()"><span class="profile-avatar">{{initials(authUser()?.displayName||'U')}}</span><span class="profile-name">{{authUser()?.displayName}}</span><i>↪</i></button><button class="upload-btn" (click)="tab.set('import')">＋ {{t('importFiles')}}</button></div></header>
    <main>
      <div *ngIf="loading()" class="loading"><span></span><p>{{t('calculating')}}</p></div>
      <div *ngIf="error()" class="alert error">{{error()}} <button (click)="refresh()">{{t('tryAgain')}}</button></div>

      <ng-container *ngIf="tab()==='dashboard' && analytics() as a">
        <section class="hero-row"><div><p class="eyebrow">{{t('financialOverview')}}</p><h2>{{t('dashboardHeadline')}}</h2><p class="muted">Based on {{a.kpis.transactionCount | number}} imported transactions · Updated {{a.generatedAtUtc | date:'shortTime'}}</p></div><div class="period"><button [class.active]="dashboardMonths()===1 && dashboardRange()==='months'" (click)="setDashboardPeriod(1)">{{t('thisMonth')}}</button><button [class.active]="dashboardMonths()===3 && dashboardRange()==='months'" (click)="setDashboardPeriod(3)">3 {{t('months')}}</button><button [class.active]="dashboardMonths()===12 && dashboardRange()==='months'" (click)="setDashboardPeriod(12)">12 {{t('months')}}</button><button [class.active]="dashboardRange()==='this-year'" (click)="setDashboardCalendarPeriod('this-year')">{{t('currentYear')}}</button><button [class.active]="dashboardRange()==='last-year'" (click)="setDashboardCalendarPeriod('last-year')">{{t('lastYear')}}</button></div></section>
        <section class="dashboard-insight" *ngIf="dashboardInsight() as insight"><div><p class="eyebrow">{{t('selectedInsight')}}</p><h3>{{insight.title}}</h3><p>{{insight.detail}}</p></div><strong>{{insight.value}}</strong><div class="insight-actions"><button class="secondary-btn" (click)="dashboardInsight.set(null)">{{t('close')}}</button><button class="upload-btn" *ngIf="insight.ledger" (click)="openInsightLedger(insight.ledger)">{{t('viewInLedger')}}</button></div></section>

        <section class="kpi-grid primary">
          <article class="kpi balance dashboard-link" role="button" tabindex="0" (click)="inspectKpi(t('currentBalance'),a.kpis.currentBalance,a.currency,t('balanceAcrossAccounts'),{})" (keydown.enter)="inspectKpi(t('currentBalance'),a.kpis.currentBalance,a.currency,t('balanceAcrossAccounts'),{})"><div class="kpi-icon">€</div><label>{{t('currentBalance')}}</label><strong>{{money(a.kpis.currentBalance,a.currency)}}</strong><small>Across {{a.kpis.activeAccounts}} active account{{a.kpis.activeAccounts===1?'':'s'}}</small></article>
          <div class="money-strip">
          <article class="kpi dashboard-link" role="button" tabindex="0" (click)="inspectKpi(t('income'),a.kpis.incomeThisMonth,a.currency,periodLabel()+' '+t('cashInflow'),{direction:'credit'})" (keydown.enter)="inspectKpi(t('income'),a.kpis.incomeThisMonth,a.currency,periodLabel()+' '+t('cashInflow'),{direction:'credit'})"><div class="kpi-icon green">↗</div><label>Income · {{periodLabel()}}</label><strong>{{money(a.kpis.incomeThisMonth,a.currency)}}</strong><small class="positive">{{t('cashInflow')}}</small></article>
          <article class="kpi dashboard-link" role="button" tabindex="0" (click)="inspectKpi(t('expensesPeriod'),a.kpis.expensesThisMonth,a.currency,periodLabel()+' '+t('cashOutflow'),{direction:'debit'})" (keydown.enter)="inspectKpi(t('expensesPeriod'),a.kpis.expensesThisMonth,a.currency,periodLabel()+' '+t('cashOutflow'),{direction:'debit'})"><div class="kpi-icon coral">↘</div><label>Expenses · {{periodLabel()}}</label><strong>{{money(a.kpis.expensesThisMonth,a.currency)}}</strong><small>Avg {{money(a.kpis.averageDailySpending,a.currency)}} / day</small></article>
          <article class="kpi dashboard-link" role="button" tabindex="0" (click)="inspectKpi(t('savingsPeriod'),a.kpis.savingsThisMonth,a.currency,periodLabel()+' '+t('netSavings'),{})" (keydown.enter)="inspectKpi(t('savingsPeriod'),a.kpis.savingsThisMonth,a.currency,periodLabel()+' '+t('netSavings'),{})"><div class="kpi-icon blue">◇</div><label>Savings · {{periodLabel()}}</label><strong [class.negative]="a.kpis.savingsThisMonth<0">{{money(a.kpis.savingsThisMonth,a.currency)}}</strong><small>{{a.kpis.savingsRate | number:'1.0-1'}}% savings rate</small></article>
          </div>
        </section>

        <section class="kpi-grid secondary">
          <article class="mini"><label>{{t('netWorth')}}</label><b>{{money(a.kpis.netWorth,a.currency)}}</b><span>Total assets {{money(a.kpis.totalAssets,a.currency)}}</span></article>
          <article class="mini"><label>{{t('cashFlow')}}</label><b [class.negative]="a.kpis.cashFlow<0">{{signedMoney(a.kpis.cashFlow,a.currency)}}</b><span>{{a.kpis.positiveCashFlowStreak}} positive month streak</span></article>
          <article class="mini"><label>{{t('monthlyBurnRate')}}</label><b>{{money(a.kpis.averageMonthlySpending,a.currency)}}</b><span>{{money(a.kpis.burnRate,a.currency)}} per day</span></article>
          <article class="mini"><label>{{t('cashRunway')}}</label><b>{{a.kpis.daysOfCashRemaining==null?'—':(a.kpis.daysOfCashRemaining|number:'1.0-0')+' '+t('days')}}</b><span>{{a.kpis.emergencyFundMonths==null?t('notEnoughHistory'):(a.kpis.emergencyFundMonths|number:'1.1-1')+' '+t('emergencyMonths')}}</span></article>
          <article class="mini dashboard-link" role="button" tabindex="0" (click)="inspectCount(t('transactions'),a.kpis.transactionCount,periodLabel()+' '+t('activity'),{})" (keydown.enter)="inspectCount(t('transactions'),a.kpis.transactionCount,periodLabel()+' '+t('activity'),{})"><label>{{t('transactions')}}</label><b>{{a.kpis.transactionCount | number}}</b><span>{{a.kpis.purchaseCount | number}} outgoing payments</span></article>
          <article class="mini"><label>{{t('averageTransaction')}}</label><b>{{money(a.kpis.averageTransaction,a.currency)}}</b><span>Median expense {{money(a.kpis.medianExpense,a.currency)}}</span></article>
        </section>

        <section class="chart-grid">
          <article class="panel wide cashflow-panel"><div class="panel-head"><div><p class="eyebrow">{{t('cashFlowChart')}}</p><h3>{{t('incomeVsExpenses')}}</h3></div><div class="legend"><i class="income"></i>Income <i class="expense"></i>{{t('expensesPeriod')}}</div></div>
            <div *ngIf="!a.monthly.length" class="empty">{{t('importMoreHistory')}}</div>
            <div class="bar-chart" *ngIf="a.monthly.length"><div class="y-guide"><span>{{money(shortMax(a.monthly),a.currency)}}</span><span>{{money(shortMax(a.monthly)/2,a.currency)}}</span><span>0</span></div><div class="bars"><div class="bar-group dashboard-link" *ngFor="let m of a.monthly" role="button" tabindex="0" (click)="inspectMonth(m,a.currency)" (keydown.enter)="inspectMonth(m,a.currency)"><div class="bar-pair"><i class="income-bar" [style.height.%]="barHeight(m.income,a.monthly)"></i><i class="expense-bar" [style.height.%]="barHeight(m.expenses,a.monthly)"></i></div><small>{{monthLabel(m.period!)}}</small></div></div></div>
          </article>
          <article class="panel"><div class="panel-head"><div><p class="eyebrow">{{t('spending')}}</p><h3>{{t('byCategory')}}</h3></div></div><div *ngIf="!a.categories.length" class="empty">{{t('noExpense')}}</div><div class="donut-wrap" *ngIf="a.categories.length"><div class="donut" [style.background]="donut(a.categories)"><div><b>{{money(total(a.categories),a.currency)}}</b><small>{{t('totalSpent')}}</small></div></div><div class="category-list"><div *ngFor="let c of a.categories.slice(0,6);let i=index" class="dashboard-list-link" role="button" tabindex="0" (click)="inspectNamed(c,t('spendingCategory'),a.currency,{category:c.name})" (keydown.enter)="inspectNamed(c,t('spendingCategory'),a.currency,{category:c.name})"><i [style.background]="color(i)"></i><span>{{categoryText(c.name)}}</span><b>{{c.percent|number:'1.0-0'}}%</b></div></div></div></article>

          <article class="panel wide"><div class="panel-head"><div><p class="eyebrow">{{t('balanceTrend')}}</p><h3>{{t('runningBalance')}}</h3></div><b>{{money(a.kpis.currentBalance,a.currency)}}</b></div><div class="line-wrap" *ngIf="a.runningBalance.length"><svg viewBox="0 0 800 220" preserveAspectRatio="none"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#156b5b" stop-opacity=".25"/><stop offset="1" stop-color="#156b5b" stop-opacity="0"/></linearGradient></defs><polygon [attr.points]="areaPoints(a.runningBalance)" fill="url(#area)"/><polyline [attr.points]="linePoints(a.runningBalance)" fill="none" stroke="#156b5b" stroke-width="3" vector-effect="non-scaling-stroke"/></svg><div class="axis"><span>{{a.runningBalance[0].date|date:'MMM d'}}</span><span>{{a.runningBalance[a.runningBalance.length-1].date|date:'MMM d'}}</span></div></div><div *ngIf="!a.runningBalance.length" class="empty">{{t('noBalanceHistory')}}</div></article>
          <article class="panel"><div class="panel-head"><div><p class="eyebrow">{{t('income')}}</p><h3>{{t('topSources')}}</h3></div></div><div class="rank-list"><div *ngFor="let s of a.incomeSources;let i=index" class="dashboard-list-link" role="button" tabindex="0" (click)="inspectNamed(s,t('income'),a.currency,{search:s.name,direction:'credit'})" (keydown.enter)="inspectNamed(s,t('income'),a.currency,{search:s.name,direction:'credit'})"><span class="rank">{{i+1}}</span><div><b>{{s.name}}</b><small>{{s.count}} {{s.count===1?t('payment'):t('payments')}}</small></div><strong>{{money(s.total,a.currency)}}</strong></div><div *ngIf="!a.incomeSources.length" class="empty">{{t('noIncomeSources')}}</div></div></article>

          <article class="panel full"><div class="panel-head"><div><p class="eyebrow">{{t('monthlyMoneyFlowLabel')}}</p><h3>{{t('monthlyMoneyFlow')}}</h3><p class="muted">{{t('transferExplanation')}}</p></div><div class="flow-legend"><span><i class="fi"></i>{{t('incoming')}}</span><span><i class="fo"></i>{{t('outgoing')}}</span><span><i class="fti"></i>{{t('transferIn')}}</span><span><i class="fto"></i>{{t('transferOut')}}</span></div></div><div class="monthly-flow" *ngIf="a.monthly.length"><div class="flow-month dashboard-link" *ngFor="let m of a.monthly" role="button" tabindex="0" (click)="inspectMonth(m,a.currency)" (keydown.enter)="inspectMonth(m,a.currency)"><div class="flow-bars"><i class="flow-in" [style.height.%]="flowHeight(m.externalIncoming||0,a.monthly)"></i><i class="flow-out" [style.height.%]="flowHeight(m.externalOutgoing||0,a.monthly)"></i><i class="flow-transfer-in" [style.height.%]="flowHeight(m.transferIn||0,a.monthly)"></i><i class="flow-transfer-out" [style.height.%]="flowHeight(m.transferOut||0,a.monthly)"></i></div><b [class.negative]="m.net<0">{{signedMoney(m.net,a.currency)}}</b><small>{{monthLabel(m.period!)}}</small></div></div><div *ngIf="!a.monthly.length" class="empty">{{t('noMonthlyFlows')}}</div></article>
          <article class="panel full"><div class="panel-head"><div><p class="eyebrow">{{t('spendingPatterns')}}</p><h3>{{t('dailyExpenseActivity')}}</h3></div><div class="heat-legend">{{t('less')}} <i></i><i></i><i></i><i></i><i></i> {{t('more')}}</div></div><div class="heatmap"><div *ngFor="let day of heatDays(a.heatmap)" [class]="'heat h'+day.level" role="button" tabindex="0" (click)="inspectDay(day,a.currency)" (keydown.enter)="inspectDay(day,a.currency)" [title]="day.date+': '+money(day.value,a.currency)"></div></div><div class="heat-months"><span>{{analytics()?.rangeStart|date:'mediumDate'}}</span><span>{{analytics()?.dataAsOf|date:'mediumDate'}}</span></div></article>

          <article class="panel"><div class="panel-head"><div><p class="eyebrow">{{t('expenseMetrics')}}</p><h3>{{t('purchaseProfile')}}</h3></div></div><dl class="metrics"><div><dt>{{t('largestPurchase')}}</dt><dd>{{money(a.kpis.largestPurchase,a.currency)}}</dd></div><div><dt>{{t('smallestPurchase')}}</dt><dd>{{money(a.kpis.smallestPurchase,a.currency)}}</dd></div><div><dt>{{t('averagePurchase')}}</dt><dd>{{money(a.kpis.averageMonthlySpending/Math.max(1,a.kpis.purchaseCount),a.currency)}}</dd></div><div><dt>{{t('negativeFlowMonths')}}</dt><dd>{{a.kpis.negativeCashFlowMonths}}</dd></div></dl></article>
          <article class="panel wide"><div class="panel-head"><div><p class="eyebrow">{{t('merchants')}}</p><h3>{{t('whereMoneyGoes')}}</h3></div></div><div class="merchant-list"><div *ngFor="let m of a.merchants;let i=index" class="dashboard-list-link" role="button" tabindex="0" (click)="inspectNamed(m,t('merchants'),a.currency,{search:m.name,direction:'debit'})" (keydown.enter)="inspectNamed(m,t('merchants'),a.currency,{search:m.name,direction:'debit'})"><div class="merchant-avatar">{{initials(m.name)}}</div><div class="merchant-name"><b>{{m.name}}</b><small>{{m.count}} {{t('transactions')}} · {{t('averageShort')}} {{money(m.average,a.currency)}}</small></div><div class="merchant-bar"><i [style.width.%]="percentOf(m.total,a.merchants)"></i></div><strong>{{money(m.total,a.currency)}}</strong></div><div *ngIf="!a.merchants.length" class="empty">{{t('noMerchantData')}}</div></div></article>

          <article class="panel full"><div class="panel-head"><div><p class="eyebrow">{{t('accounts')}}</p><h3>{{t('accountOverview')}}</h3></div><button class="text-btn" (click)="goLedger()">{{t('viewLedger')}} →</button></div><div class="account-grid"><div class="account dashboard-link" *ngFor="let account of a.accounts" role="button" tabindex="0" (click)="inspectAccount(account)" (keydown.enter)="inspectAccount(account)"><span class="bank-icon">▦</span><div><b>{{account.displayName||account.accountName||t('bankAccount')}}</b><small>{{maskIban(account.iban)}}</small></div><strong>{{money(account.balance,account.currency)}}</strong></div></div></article>
        </section>
        <section class="data-note"><div>ⓘ</div><div><b>{{t('dataAvailability')}}</b><p>{{t('dataAvailabilityText')}}</p><span *ngFor="let note of a.unavailable">{{availabilityText(note)}}</span></div></section>
      </ng-container>

      <section *ngIf="tab()==='monthly' && monthlyOverview() as m" class="page-card period-page month-page">
        <header class="period-hero"><div><p class="eyebrow">{{t('monthlyOverview')}}</p><h2>{{monthFullLabel(m.month)}}</h2><p class="muted">{{t('monthlyText')}}</p></div><div class="period-navigator"><button type="button" (click)="shiftMonth(-1)" [attr.aria-label]="t('previousMonth')">‹</button><label><span>{{t('selectMonth')}}</span><input type="month" [value]="overviewMonth()" (change)="changeOverviewMonth($event)"></label><button type="button" (click)="shiftMonth(1)" [attr.aria-label]="t('nextMonth')">›</button></div></header>
        <section class="period-summary"><article class="income-summary"><label>{{t('incomePeriod')}}</label><strong>{{money(m.incoming,m.currency)}}</strong><small>{{t('externalCashReceived')}}</small></article><article class="expense-summary"><label>{{t('expensesPeriod')}}</label><strong>{{money(m.outgoing,m.currency)}}</strong><small>{{t('externalSpending')}}</small></article><article class="savings-summary" [class.negative]="m.net<0"><label>{{t('savingsPeriod')}}</label><strong>{{signedMoney(m.net,m.currency)}}</strong><small>{{savingsRate(m.incoming,m.net)|number:'1.0-1'}}% {{t('savingsRate')}}</small></article></section>
        <div class="period-meta"><b>{{m.transactionCount|number}} {{t('transactions')}}</b><span>{{m.from|date:'mediumDate'}} – {{m.to|date:'mediumDate'}}</span></div>

        <div class="month-analytics-grid">
          <article class="period-panel daily-panel"><div class="panel-head"><div><p class="eyebrow">{{t('dailySpending')}}</p><h3>{{t('spendingTimeline')}}</h3></div><small>{{money(monthAverageDaily(),m.currency)}} / {{t('day')}}</small></div><div class="daily-scroll" *ngIf="overviewDays().length"><div class="daily-chart"><button *ngFor="let day of overviewDays()" type="button" [class.selected]="activeOverviewDay()?.date===day.date" (click)="selectedOverviewDay.set(day.date)" [attr.aria-label]="(day.date|date:'mediumDate')+' '+money(day.outgoing,m.currency)"><span class="daily-bar"><i [style.height.%]="dailyBarHeight(day.outgoing)"></i></span><small>{{day.date|date:'d'}}</small></button></div></div><div class="empty" *ngIf="!overviewDays().length">{{t('noOutgoingMonth')}}</div><div class="selection-summary" *ngIf="activeOverviewDay() as day"><div><p class="eyebrow">{{day.date|date:'fullDate'}}</p><strong>{{money(day.outgoing,m.currency)}}</strong><small>{{day.count}} {{t('transactions')}} · {{money(day.income,m.currency)}} {{t('incoming').toLowerCase()}}</small></div><button class="secondary-btn" (click)="openDayLedger(day.date)">{{t('viewInLedger')}}</button></div></article>

          <article class="period-panel pace-panel"><div class="panel-head"><div><p class="eyebrow">{{t('spendingPace')}}</p><h3>{{t('monthRhythm')}}</h3></div></div><div class="pace-ring" [style.--pace]="monthElapsedPercent()+'%'"><div><strong>{{monthElapsedPercent()|number:'1.0-0'}}%</strong><small>{{t('monthElapsed')}}</small></div></div><dl class="pace-stats"><div><dt>{{t('averagePerDay')}}</dt><dd>{{money(monthAverageDaily(),m.currency)}}</dd></div><div><dt>{{t('largestDay')}}</dt><dd>{{money(monthLargestDay(),m.currency)}}</dd></div><div><dt>{{t('activeDays')}}</dt><dd>{{overviewDays().length}}</dd></div></dl></article>

          <article class="period-panel calendar-panel"><div class="panel-head"><div><p class="eyebrow">{{t('spendingCalendar')}}</p><h3>{{monthFullLabel(m.month)}}</h3></div><div class="heat-legend">{{t('less')}} <i></i><i></i><i></i><i></i> {{t('more')}}</div></div><div class="calendar-weekdays"><span *ngFor="let label of weekdayLabels()">{{label}}</span></div><div class="spending-calendar"><span class="calendar-blank" *ngFor="let blank of calendarLeadingDays()"></span><button *ngFor="let day of calendarDays()" type="button" [class]="'calendar-day h'+day.level" [class.selected]="activeOverviewDay()?.date===day.date" (click)="selectedOverviewDay.set(day.date)"><b>{{day.day}}</b><small *ngIf="day.outgoing">{{compactMoney(day.outgoing,m.currency)}}</small></button></div></article>

          <article class="period-panel category-panel"><div class="panel-head"><div><p class="eyebrow">{{t('categories')}}</p><h3>{{t('spendingByCategory')}}</h3></div><b>{{money(m.outgoing,m.currency)}}</b></div><div class="category-bars"><button *ngFor="let c of overviewCategories();let i=index" type="button" [class.selected]="activeOverviewCategory()?.name===c.name" (click)="selectedOverviewCategory.set(c.name)"><span><i [style.background]="color(i)"></i><b>{{categoryText(c.name)}}</b><small>{{c.count}} {{t('transactions')}}</small></span><strong>{{money(c.total,m.currency)}}</strong><em><i [style.width.%]="categoryPercent(c.total)"></i></em></button></div><div class="empty" *ngIf="!overviewCategories().length">{{t('noExpense')}}</div><div class="selection-summary category-selection" *ngIf="activeOverviewCategory() as c"><div><p class="eyebrow">{{categoryText(c.name)}}</p><strong>{{money(c.total,m.currency)}}</strong><small>{{c.count}} {{t('transactions')}} · {{t('largestPurchase')}} {{money(c.largest,m.currency)}}</small></div><button class="secondary-btn" (click)="openCategoryLedger(c.name)">{{t('viewInLedger')}}</button></div></article>
        </div>

        <details class="period-details"><summary><div><p class="eyebrow">{{t('cashFlow')}}</p><h3>{{t('incomeAndSpendingDetails')}}</h3></div><span>{{t('showDetails')}} ⌄</span></summary><div class="balance-columns"><section><div class="balance-column-head incoming-head"><div><p class="eyebrow">{{t('incoming')}}</p><h3>{{t('incomeByCategory')}}</h3></div><b>{{money(m.incoming,m.currency)}}</b></div><details class="balance-group" *ngFor="let g of directionGroups(m.groups,'Incoming')"><summary><div><b>{{categoryText(g.category)}}</b><small>{{categoryText(g.subcategory)}} · {{g.count}} {{t('transactions')}}</small></div><strong>{{money(g.total,m.currency)}}</strong><span>⌄</span></summary><div class="period-transactions"><button *ngFor="let x of g.transactions" (click)="openDayLedger(x.bookingDate)"><span><b>{{x.counterpartyName||x.accountName||t('unknownCounterparty')}}</b><small>{{x.bookingDate|date:'mediumDate'}} · {{x.accountName}}</small><em>{{x.remittanceInformation||x.additionalInformation||'—'}}</em></span><strong class="credit-value">{{money(x.amount,x.currency)}}</strong></button></div></details></section><section><div class="balance-column-head outgoing-head"><div><p class="eyebrow">{{t('outgoing')}}</p><h3>{{t('spendingByCategory')}}</h3></div><b>{{money(m.outgoing,m.currency)}}</b></div><details class="balance-group" *ngFor="let g of directionGroups(m.groups,'Outgoing')"><summary><div><b>{{categoryText(g.category)}}</b><small>{{categoryText(g.subcategory)}} · {{g.count}} {{t('transactions')}}</small></div><strong>{{money(g.total,m.currency)}}</strong><span>⌄</span></summary><div class="period-transactions"><button *ngFor="let x of g.transactions" (click)="openDayLedger(x.bookingDate)"><span><b>{{x.counterpartyName||x.accountName||t('unknownCounterparty')}}</b><small>{{x.bookingDate|date:'mediumDate'}} · {{x.accountName}}</small><em>{{x.remittanceInformation||x.additionalInformation||'—'}}</em></span><strong class="debit-value">{{money(x.amount,x.currency)}}</strong></button></div></details></section></div></details>
        <ng-container *ngTemplateOutlet="transferBlock;context:{$implicit:m}"></ng-container>
      </section>

      <section *ngIf="tab()==='year' && monthlyOverview() as m" class="page-card period-page year-page">
        <header class="period-hero"><div><p class="eyebrow">{{t('yearOverview')}}</p><h2>{{m.year}}</h2><p class="muted">{{t('yearOverviewText')}}</p></div><div class="period-navigator year-navigator"><button type="button" (click)="shiftYear(-1)" [attr.aria-label]="t('previousYear')">‹</button><label><span>{{t('selectYear')}}</span><input type="number" min="2000" max="2100" [value]="overviewYear()" (change)="changeOverviewYear($event)"></label><button type="button" (click)="shiftYear(1)" [attr.aria-label]="t('nextYear')">›</button></div></header>
        <section class="period-summary"><article class="income-summary"><label>{{t('incomePeriod')}}</label><strong>{{money(m.incoming,m.currency)}}</strong><small>{{t('externalCashReceived')}}</small></article><article class="expense-summary"><label>{{t('expensesPeriod')}}</label><strong>{{money(m.outgoing,m.currency)}}</strong><small>{{t('externalSpending')}}</small></article><article class="savings-summary" [class.negative]="m.net<0"><label>{{t('savingsPeriod')}}</label><strong>{{signedMoney(m.net,m.currency)}}</strong><small>{{savingsRate(m.incoming,m.net)|number:'1.0-1'}}% {{t('savingsRate')}}</small></article></section>
        <div class="year-analytics-grid">
          <article class="period-panel annual-trend-panel"><div class="panel-head"><div><p class="eyebrow">{{t('annualTrend')}}</p><h3>{{t('incomeVsExpenses')}}</h3></div><div class="flow-legend"><span><i class="fi"></i>{{t('incoming')}}</span><span><i class="fo"></i>{{t('outgoing')}}</span></div></div><div class="year-chart-scroll"><div class="year-chart"><button *ngFor="let month of yearMonths()" type="button" [class.selected]="activeYearMonth()?.period===month.period" (click)="selectedYearPeriod.set(month.period)"><div class="year-bars"><i class="income-bar" [style.height.%]="yearBarHeight(month.income)"></i><i class="expense-bar" [style.height.%]="yearBarHeight(month.outgoing)"></i></div><small>{{monthLabel(month.period)}}</small></button></div></div><div class="selection-summary month-selection" *ngIf="activeYearMonth() as month"><div><p class="eyebrow">{{monthFullLabel(month.period)}}</p><strong>{{signedMoney(month.net,m.currency)}}</strong><small>{{t('incoming')}} {{money(month.income,m.currency)}} · {{t('outgoing')}} {{money(month.outgoing,m.currency)}} · {{savingsRate(month.income,month.net)|number:'1.0-1'}}%</small></div><button class="secondary-btn" (click)="openMonthLedger(month.period)">{{t('viewInLedger')}}</button></div></article>

          <article class="period-panel monthly-performance-panel"><div class="panel-head"><div><p class="eyebrow">{{t('monthlyPerformance')}}</p><h3>{{t('allTwelveMonths')}}</h3></div></div><div class="month-card-rail"><button *ngFor="let month of yearMonths()" type="button" [class.selected]="activeYearMonth()?.period===month.period" (click)="selectedYearPeriod.set(month.period)"><span>{{monthLabel(month.period)}}</span><strong [class.negative]="month.net<0">{{compactMoney(month.net,m.currency,true)}}</strong><small>{{month.count}} {{t('transactions')}}</small></button></div></article>

          <article class="period-panel category-trend-panel"><div class="panel-head"><div><p class="eyebrow">{{t('categoryTrends')}}</p><h3>{{activeOverviewCategory()?categoryText(activeOverviewCategory()!.name):t('spendingByCategory')}}</h3></div></div><div class="category-chips"><button *ngFor="let c of overviewCategories()" type="button" [class.active]="activeOverviewCategory()?.name===c.name" (click)="selectedOverviewCategory.set(c.name)">{{categoryText(c.name)}}</button></div><div class="category-trend"><div *ngFor="let point of categoryTrend()"><span><i [style.height.%]="categoryTrendHeight(point.total)"></i></span><small>{{monthLabel(point.period)}}</small></div></div><div class="selection-summary category-selection" *ngIf="activeOverviewCategory() as c"><div><p class="eyebrow">{{categoryText(c.name)}}</p><strong>{{money(c.total,m.currency)}}</strong><small>{{c.count}} {{t('transactions')}} · {{t('largestPurchase')}} {{money(c.largest,m.currency)}}</small></div><button class="secondary-btn" (click)="openCategoryLedger(c.name)">{{t('viewInLedger')}}</button></div></article>

          <article class="period-panel year-pattern-panel"><div class="panel-head"><div><p class="eyebrow">{{t('yearPattern')}}</p><h3>{{t('categoryByMonth')}}</h3></div><small>{{t('selectCategoryHint')}}</small></div><div class="year-pattern"><div class="pattern-head"><span></span><b *ngFor="let month of yearMonths()">{{monthLabel(month.period)}}</b></div><button *ngFor="let row of yearCategoryPattern()" (click)="selectedOverviewCategory.set(row.name)"><strong>{{categoryText(row.name)}}</strong><i *ngFor="let value of row.values" [style.opacity]="patternOpacity(value,row.max)" [title]="money(value,m.currency)"></i></button></div></article>
        </div>

        <details class="period-details"><summary><div><p class="eyebrow">{{t('annualDetails')}}</p><h3>{{t('incomeAndSpendingDetails')}}</h3></div><span>{{t('showDetails')}} ⌄</span></summary><div class="balance-columns"><section><div class="balance-column-head incoming-head"><h3>{{t('incomeByCategory')}}</h3><b>{{money(m.incoming,m.currency)}}</b></div><details class="balance-group" *ngFor="let g of directionGroups(m.groups,'Incoming')"><summary><div><b>{{categoryText(g.category)}}</b><small>{{categoryText(g.subcategory)}} · {{g.count}} {{t('transactions')}}</small></div><strong>{{money(g.total,m.currency)}}</strong><span>⌄</span></summary></details></section><section><div class="balance-column-head outgoing-head"><h3>{{t('spendingByCategory')}}</h3><b>{{money(m.outgoing,m.currency)}}</b></div><details class="balance-group" *ngFor="let g of directionGroups(m.groups,'Outgoing')"><summary><div><b>{{categoryText(g.category)}}</b><small>{{categoryText(g.subcategory)}} · {{g.count}} {{t('transactions')}}</small></div><strong>{{money(g.total,m.currency)}}</strong><span>⌄</span></summary></details></section></div></details>
        <ng-container *ngTemplateOutlet="transferBlock;context:{$implicit:m}"></ng-container>
      </section>

      <ng-template #transferBlock let-m><section class="transfer-section" *ngIf="transferGroups(m.groups).length"><div class="balance-column-head"><div><p class="eyebrow">{{t('internalMovements')}}</p><h3>{{t('transfersOwnAccounts')}}</h3><small>{{t('excludedIncomeExpenses')}}</small></div><div class="transfer-totals"><span>{{t('transferIn')}} <b>{{money(m.transferIn,m.currency)}}</b></span><span>{{t('transferOut')}} <b>{{money(m.transferOut,m.currency)}}</b></span></div></div><details class="balance-group" *ngFor="let g of transferGroups(m.groups)"><summary><div><b>{{directionText(g.direction)}}</b><small>{{g.count}} {{t('transactions')}}</small></div><strong>{{money(g.total,m.currency)}}</strong><span>⌄</span></summary><div class="period-transactions"><button *ngFor="let x of g.transactions" (click)="openDayLedger(x.bookingDate)"><span><b>{{x.counterpartyName||x.counterpartyIban||t('ownAccount')}}</b><small>{{x.bookingDate|date:'mediumDate'}} · {{x.accountName}}</small><em>{{x.remittanceInformation||'—'}}</em></span><strong>{{money(x.amount,x.currency)}}</strong></button></div></details></section></ng-template>
      <section *ngIf="tab()==='accounts' && analytics() as a" class="page-card"><div class="panel-head"><div><p class="eyebrow">{{t('accountSettings')}}</p><h2>{{t('nameAccounts')}}</h2><p class="muted">{{t('accountSettingsText')}}</p></div></div><div class="account-settings"><article *ngFor="let account of a.accounts"><div class="settings-account-head"><span class="bank-icon">▦</span><div><b>{{account.displayName||account.accountName||t('bankAccount')}}</b><small class="mono">{{account.iban||t('noIban')}} · {{account.currency}}</small></div><strong>{{money(account.balance,account.currency)}}</strong></div><label>{{t('customAccountName')}}<input #accountName [value]="account.displayName||''" maxlength="100" [placeholder]="t('accountNamePlaceholder')"></label><label>{{t('accountType')}}<select #accountType [value]="account.accountKind"><option value="0">{{t('currentAccount')}}</option><option value="1">{{t('savingsAccount')}}</option><option value="2">{{t('creditAccount')}}</option><option value="3">{{t('investmentAccount')}}</option><option value="4">{{t('other')}}</option></select></label><button class="upload-btn" (click)="saveAccount(account,accountName.value,accountType.value)">{{t('saveAccount')}}</button></article></div><div *ngIf="accountMessage()" class="alert">{{accountMessage()}}</div></section>
      <section *ngIf="tab()==='import'" class="page-card import-page"><p class="eyebrow">{{t('dataIngestion')}}</p><h2>{{t('importStatements')}}</h2><p class="muted">{{t('uploadText')}}</p><label class="drop" [class.busy]="busy()" [class.dragging]="dragging()" (dragover)="dragOver($event)" (dragleave)="dragLeave()" (drop)="dropFile($event)"><input type="file" accept=".xml,.zip,application/xml,application/zip" (change)="upload($event)"><span>⇧</span><strong>{{busy()?'Uploading and creating import jobs…':'Choose or drop an XML / ZIP file'}}</strong><small>{{t('maximumZip')}}</small></label><div *ngIf="message()" class="alert">{{message()}}</div></section>
      <section *ngIf="tab()==='imports'" class="page-card"><div class="panel-head"><div><p class="eyebrow">{{t('importHistory')}}</p><h2>{{t('statementImports')}}</h2></div><button class="upload-btn" (click)="tab.set('import')">＋ {{t('newImport')}}</button></div><div class="table-wrap"><table><thead><tr><th>{{t('file')}}</th><th>{{t('uploaded')}}</th><th>{{t('status')}}</th><th>{{t('transactions')}}</th><th>{{t('warnings')}}</th></tr></thead><tbody><tr *ngFor="let x of imports()"><td><b>{{x.originalFileName}}</b></td><td>{{x.createdAtUtc|date:'medium'}}</td><td><span [class]="'status s'+x.status">{{statusLabel(x.status)}}</span></td><td>{{x.transactionCount}}</td><td>{{x.warningCount}}</td></tr></tbody></table><div *ngIf="!imports().length" class="empty">{{t('noImports')}}</div></div></section>
      <section *ngIf="tab()==='ledger'" class="page-card ledger-page">
        <div class="panel-head"><div><p class="eyebrow">{{t('accountLedger')}}</p><h2>{{t('ledgerHeadline')}}</h2><p class="muted">{{t('ledgerText')}}</p></div><div class="result-count"><b>{{ledgerTotal()|number}}</b><small>{{t('matchingTransactions')}}</small></div></div>
        <div class="ledger-filter-panel">
          <label>{{t('account')}}<select [value]="ledgerAccountId()" (change)="selectLedgerAccount($event)"><option value="">{{t('allAccounts')}}</option><option *ngFor="let account of analytics()?.accounts||[]" [value]="account.id">{{account.displayName||account.accountName||t('bankAccount')}} · {{maskIban(account.iban)}}</option></select></label>
          <label>{{t('category')}}<select #filterCategory [value]="ledgerFilterCategory()" (change)="ledgerFilterCategory.set(filterCategory.value);ledgerFilterSubcategory.set('')"><option value="">{{t('allCategories')}}</option><option *ngFor="let group of categoryGroups()" [value]="group.name">{{categoryText(group.name)}}</option></select></label>
          <label>{{t('subcategory')}}<select #filterSubcategory [value]="ledgerFilterSubcategory()" [disabled]="!ledgerFilterCategory()"><option value="">{{t('allSubcategories')}}</option><option *ngFor="let sub of subcategories(ledgerFilterCategory())" [value]="sub">{{categoryText(sub)}}</option></select></label>
          <label>{{t('direction')}}<select #filterDirection [value]="ledgerDirection()"><option value="">{{t('incomingOutgoing')}}</option><option value="credit">{{t('incoming')}}</option><option value="debit">{{t('outgoing')}}</option></select></label>
          <label>{{t('from')}}<input type="date" #filterFrom [value]="ledgerFrom()"></label><label>{{t('to')}}<input type="date" #filterTo [value]="ledgerTo()"></label>
          <label>{{t('minimumAmount')}}<input type="number" min="0" step="0.01" #filterMin [value]="ledgerMin()" placeholder="0.00"></label><label>{{t('maximumAmount')}}<input type="number" min="0" step="0.01" #filterMax [value]="ledgerMax()" [placeholder]="t('maximumPlaceholder')"></label>
          <label class="filter-search">{{t('search')}}<input #ledgerQuery [value]="ledgerSearch()" [placeholder]="t('ledgerSearchPlaceholder')" (keyup.enter)="applyLedgerFilters(ledgerQuery.value,filterSubcategory.value,filterDirection.value,filterFrom.value,filterTo.value,filterMin.value,filterMax.value)"></label>
          <div class="filter-actions"><button class="secondary-btn" (click)="clearLedgerFilters()">{{t('clear')}}</button><button class="upload-btn" (click)="applyLedgerFilters(ledgerQuery.value,filterSubcategory.value,filterDirection.value,filterFrom.value,filterTo.value,filterMin.value,filterMax.value)">{{t('applyFilters')}}</button></div>
        </div>
        <div class="ledger-explanation"><b>{{t('balanceAfterTransaction')}}</b><span>{{t('balanceExplanation')}}</span></div>
        <p class="category-feedback" *ngIf="categoryMessage()">{{categoryMessage()}}</p>
        <div class="table-wrap"><table class="ledger-balance-table"><thead><tr><th>{{t('bookingDate')}}</th><th>{{t('account')}}</th><th>{{t('description')}}</th><th>{{t('category')}}</th><th>{{t('reference')}}</th><th class="right">{{t('debit')}}</th><th class="right">{{t('credit')}}</th><th class="right">{{t('balanceAfter')}}</th><th></th></tr></thead><tbody>
          <ng-container *ngFor="let x of transactions()">
            <tr><td><b>{{x.bookingDate|date:'mediumDate'}}</b><small>{{t('value')}} {{x.valueDate?(x.valueDate|date:'mediumDate'):'—'}}</small></td><td class="mono">{{shortId(x.bankAccountId)}}</td><td><b>{{x.counterpartyName||t('unknownCounterparty')}}</b><small>{{x.remittanceInformation||x.additionalInformation||'—'}}</small></td><td><span class="category-pill">{{categoryText(x.category||'Miscellaneous')}}</span><small>{{categoryText(x.subcategory||'Other')}} · {{categorySourceLabel(x.categorySource)}}</small></td><td class="mono">{{x.accountServicerReference||x.entryReference||x.endToEndId||'—'}}</td><td class="right debit-value">{{x.creditDebitIndicator===1?money(x.amount,x.currency):'—'}}</td><td class="right credit-value">{{x.creditDebitIndicator===0?money(x.amount,x.currency):'—'}}</td><td class="right balance-value">{{money(x.balanceAfterTransaction,x.currency)}}</td><td><button class="secondary-btn compact" (click)="openLedgerCategory(x)">{{selectedTransaction()?.id===x.id?t('close'):t('categorize')}}</button></td></tr>
            <tr class="ledger-editor-row" *ngIf="selectedTransaction()?.id===x.id"><td colspan="9"><div class="category-editor"><div><p class="eyebrow">{{t('categoryLabel')}}</p><h4>{{x.counterpartyName||x.counterpartyIban||'Transaction'}}</h4><small>{{t('currentSource')}}: {{categorySourceLabel(x.categorySource)}}</small></div><label>{{t('category')}}<select #categorySelect [value]="x.category||'Miscellaneous'" (change)="categoryDraft.set(categorySelect.value)"><option *ngFor="let group of categoryGroups()" [value]="group.name">{{categoryText(group.name)}}</option></select></label><label>{{t('subcategory')}}<select #subcategorySelect><option *ngFor="let sub of subcategories(categoryDraft()||x.category||'Miscellaneous')" [value]="sub" [selected]="sub===x.subcategory">{{categoryText(sub)}}</option></select></label><label class="iban-rule"><input type="checkbox" #applyIban [disabled]="!x.counterpartyIban"> {{t('applyIban')}} {{x.counterpartyIban||'this IBAN'}}</label><button class="upload-btn" (click)="saveCategory(x,categorySelect.value,subcategorySelect.value,applyIban.checked)">{{t('saveCategory')}}</button></div></td></tr>
          </ng-container>
        </tbody></table><div *ngIf="!transactions().length" class="empty">{{t('noLedgerMatches')}}</div></div>
      </section>      <section *ngIf="tab()==='transactions'" class="page-card ledger-page">
        <div class="panel-head ledger-head"><div><p class="eyebrow">{{t('rawValuesLabel')}}</p><h2>{{t('rawHeadline')}}</h2><p class="muted">{{t('rawText')}}</p></div><div class="ledger-tools"><input class="search" [placeholder]="t('rawSearchPlaceholder')" #q (keyup.enter)="loadTransactions(q.value)"><button class="icon-btn" (click)="loadTransactions(q.value)">⌕</button></div></div>
        <div class="table-wrap"><table class="ledger-table"><thead><tr><th></th><th>{{t('bookingValue')}}</th><th>{{t('counterparty')}}</th><th>{{t('remittance')}}</th><th>{{t('status')}}</th><th>{{t('account')}}</th><th class="right">{{t('amount')}}</th></tr></thead><tbody>
          <ng-container *ngFor="let x of transactions()">
            <tr class="transaction-row" [class.selected]="selectedTransaction()?.id===x.id" (click)="toggleTransaction(x)"><td><button class="expand-btn">{{selectedTransaction()?.id===x.id?'−':'+'}}</button></td><td><b>{{x.bookingDate|date:'mediumDate'}}</b><small>{{t('value')}} {{x.valueDate?(x.valueDate|date:'mediumDate'):'—'}}</small></td><td><b>{{x.counterpartyName||t('unknownCounterparty')}}</b><small class="mono">{{x.counterpartyIban||t('noIban')}}</small></td><td class="remittance-cell">{{x.remittanceInformation||x.additionalInformation||'—'}}</td><td><span [class]="x.creditDebitIndicator===1?'pill debit-pill':'pill credit-pill'">{{x.creditDebitIndicator===1?'Debit':'Credit'}}</span><small>{{x.status||t('noStatus')}}</small></td><td class="mono">{{shortId(x.bankAccountId)}}</td><td class="right amount" [class.negative]="x.creditDebitIndicator===1">{{x.creditDebitIndicator===1?'-':'+'}}{{money(x.amount,x.currency)}}</td></tr>
            <tr class="detail-row" *ngIf="selectedTransaction()?.id===x.id"><td colspan="7"><div class="transaction-detail">
              <div class="detail-title"><div><p class="eyebrow">{{t('transactionDetail')}}</p><h3>{{x.counterpartyName||t('unknownCounterparty')}}</h3></div><div class="detail-amount" [class.negative]="x.creditDebitIndicator===1">{{x.creditDebitIndicator===1?'-':'+'}}{{money(x.amount,x.currency)}}<small>{{x.creditDebitIndicator===1?'Debit':'Credit'}} · {{x.status||t('unknown')}}</small></div></div>
              <div class="detail-groups">
                <section><h4>{{t('coreTransaction')}}</h4><dl><div><dt>{{t('transactionId')}}</dt><dd class="mono">{{x.id}}</dd></div><div><dt>{{t('bookingDate')}}</dt><dd>{{x.bookingDate|date:'fullDate'}}</dd></div><div><dt>{{t('valueDate')}}</dt><dd>{{x.valueDate?(x.valueDate|date:'fullDate'):'—'}}</dd></div><div><dt>{{t('amount')}}</dt><dd>{{money(x.amount,x.currency)}}</dd></div><div><dt>{{t('currency')}}</dt><dd>{{x.currency}}</dd></div><div><dt>{{t('direction')}}</dt><dd>{{x.creditDebitIndicator===1?'Debit':'Credit'}}</dd></div><div><dt>{{t('status')}}</dt><dd>{{x.status||'—'}}</dd></div><div><dt>{{t('importedAt')}}</dt><dd>{{x.createdAtUtc|date:'medium'}}</dd></div></dl></section>
                <section><h4>{{t('counterparty')}}</h4><dl><div><dt>{{t('name')}}</dt><dd>{{x.counterpartyName||'—'}}</dd></div><div><dt>{{t('iban')}}</dt><dd class="mono">{{x.counterpartyIban||'—'}}</dd></div><div><dt>{{t('bic')}}</dt><dd class="mono">{{x.counterpartyBic||'—'}}</dd></div><div><dt>{{t('remittance')}}</dt><dd>{{x.remittanceInformation||'—'}}</dd></div><div><dt>{{t('additionalInformation')}}</dt><dd>{{x.additionalInformation||'—'}}</dd></div></dl></section>
                <section><h4>{{t('bankReferences')}}</h4><dl><div><dt>{{t('entryReference')}}</dt><dd class="mono">{{x.entryReference||'—'}}</dd></div><div><dt>{{t('servicerReference')}}</dt><dd class="mono">{{x.accountServicerReference||'—'}}</dd></div><div><dt>{{t('instructionId')}}</dt><dd class="mono">{{x.instructionId||'—'}}</dd></div><div><dt>{{t('endToEndId')}}</dt><dd class="mono">{{x.endToEndId||'—'}}</dd></div><div><dt>{{t('mandateId')}}</dt><dd class="mono">{{x.mandateId||'—'}}</dd></div><div><dt>{{t('bankTransactionId')}}</dt><dd class="mono">{{x.transactionId||'—'}}</dd></div><div><dt>{{t('externalTransactionId')}}</dt><dd class="mono">{{x.externalTransactionId||'—'}}</dd></div></dl></section>
                <section><h4>{{t('classificationOwnership')}}</h4><dl><div><dt>{{t('bankTransactionCode')}}</dt><dd class="mono">{{x.bankTransactionCode||'—'}}</dd></div><div><dt>{{t('proprietaryCode')}}</dt><dd class="mono">{{x.proprietaryTransactionCode||'—'}}</dd></div><div><dt>{{t('bankAccountId')}}</dt><dd class="mono">{{x.bankAccountId}}</dd></div><div><dt>{{t('statementId')}}</dt><dd class="mono">{{x.bankStatementId}}</dd></div><div><dt>{{t('fingerprint')}}</dt><dd class="mono wrap">{{x.fingerprint}}</dd></div></dl></section>
              </div>
              <details class="raw-detail"><summary>{{t('sourceMetadata')}}</summary><pre>{{prettyJson(x.rawEntryJson)}}</pre></details>
            </div></td></tr>
          </ng-container>
        </tbody></table><div *ngIf="!transactions().length" class="empty">{{t('noTransactionMatches')}}</div></div>
      </section>
      <section *ngIf="tab()==='users'" class="page-card"><div class="panel-head"><div><p class="eyebrow">{{t('administration')}}</p><h2>{{t('userManagement')}}</h2><p class="muted">{{t('usersText')}}</p></div></div><div class="filters"><input #newName [placeholder]="t('name')"><input #newEmail type="email" placeholder="Email"><input #newPassword type="password" placeholder="Password (12+ characters)"><select #newRole><option value="User">{{t('user')}}</option><option value="Administrator">{{t('administrator')}}</option></select><button class="upload-btn" (click)="createUser(newName.value,newEmail.value,newPassword.value,newRole.value)">{{t('addUser')}}</button></div><p *ngIf="userMessage()" class="alert">{{userMessage()}}</p><table><thead><tr><th>{{t('name')}}</th><th>Email</th><th>{{t('role')}}</th><th>{{t('status')}}</th><th></th></tr></thead><tbody><tr *ngFor="let user of users()"><td>{{user.displayName}}</td><td>{{user.email}}</td><td>{{user.role}}</td><td>{{user.isActive?t('active'):t('inactive')}}</td><td><button class="text-btn" (click)="toggleUser(user)">{{user.isActive?t('deactivate'):t('activate')}}</button></td></tr></tbody></table></section>    </main>
  </div>
</div>`})
class App implements OnInit {
  readonly Math=Math;readonly Number=Number; private http=inject(HttpClient); language=signal<Language>((localStorage.getItem('finance-language') as Language)||'en'); tab=signal('dashboard');mobileMenuOpen=signal(false);loading=signal(false);busy=signal(false);message=signal('');error=signal('');analytics=signal<Analytics|null>(null);imports=signal<ImportRow[]>([]);transactions=signal<Tx[]>([]);selectedTransaction=signal<Tx|null>(null);ledgerAccountId=signal('');ledgerFilterCategory=signal('');ledgerFilterSubcategory=signal('');ledgerDirection=signal('');ledgerFrom=signal('');ledgerTo=signal('');ledgerMin=signal('');ledgerMax=signal('');ledgerSearch=signal('');ledgerTotal=signal(0);accountMessage=signal('');categoryGroups=signal<CategoryGroup[]>([]);categoryDraft=signal('');categoryMessage=signal('');dashboardMonths=signal(1);dashboardRange=signal('months');dashboardInsight=signal<any|null>(null);monthlyOverview=signal<any|null>(null);overviewMonth=signal('');overviewYear=signal(new Date().getFullYear());selectedOverviewDay=signal('');selectedOverviewCategory=signal('');selectedYearPeriod=signal('');authUser=signal<any|null>(null);setupRequired=signal(false);authBusy=signal(false);authError=signal('');setupDisplayName=signal('');dragging=signal(false);sidebarCompact=signal(localStorage.getItem('finance-sidebar-compact')==='true');users=signal<any[]>([]);userMessage=signal('');
  title=computed(()=>this.t(({dashboard:'overview',transactions:'rawValues',ledger:'ledger',monthly:'monthlyOverview',year:'yearOverview',users:'userManagement',accounts:'accounts',imports:'imports',import:'uploadCamt'} as any)[this.tab()]));
  overviewDays=computed<PeriodDay[]>(()=>this.buildOverviewDays(this.monthlyOverview()));
  overviewCategories=computed<PeriodCategory[]>(()=>this.buildOverviewCategories(this.monthlyOverview()));
  yearMonths=computed<YearMonth[]>(()=>this.buildYearMonths(this.monthlyOverview()));
  activeOverviewDay=computed<PeriodDay|null>(()=>this.overviewDays().find(x=>x.date===this.selectedOverviewDay())||[...this.overviewDays()].reverse().find(x=>x.outgoing>0)||this.overviewDays()[0]||null);
  activeOverviewCategory=computed<PeriodCategory|null>(()=>this.overviewCategories().find(x=>x.name===this.selectedOverviewCategory())||this.overviewCategories()[0]||null);
  activeYearMonth=computed<YearMonth|null>(()=>this.yearMonths().find(x=>x.period===this.selectedYearPeriod())||[...this.yearMonths()].reverse().find(x=>x.count>0)||this.yearMonths()[0]||null);
  categoryTrend=computed(()=>this.buildCategoryTrend(this.monthlyOverview(),this.activeOverviewCategory()?.name));
  colors=['#166b5c','#e0a84b','#e16b5a','#6387ba','#8f78ad','#69a58b','#d98aa4','#7a8b98'];
  t(key:TranslationKey|string){return (UI[this.language()] as any)[key]||(UI.en as any)[key]||key}
  categoryText(value:string){return value.split(' / ').map(x=>categoryText(x,this.language())).join(' / ')}
  directionText(value:string){return ({Incoming:this.t('incoming'),Outgoing:this.t('outgoing'),'Transfer in':this.t('transferIn'),'Transfer out':this.t('transferOut')} as any)[value]||value}
  setLanguage(event:Event){const value=(event.target as HTMLSelectElement).value as Language;this.language.set(value);localStorage.setItem('finance-language',value)} toggleSidebar(){this.sidebarCompact.update(x=>!x);localStorage.setItem('finance-sidebar-compact',String(this.sidebarCompact()))}  ngOnInit(){const token=localStorage.getItem('finance-token');this.http.get<any>('/api/v1/auth/setup-required').subscribe({next:x=>{this.setupRequired.set(x.setupRequired);if(!x.setupRequired&&token)this.restoreSession()},error:()=>this.authError.set('Could not reach the sign-in service.')})} isAdmin(){return this.authUser()?.role==='Administrator'} restoreSession(){this.http.get<any>('/api/v1/auth/me').subscribe({next:user=>{this.authUser.set(user);this.loadCategories();this.showDashboard()},error:()=>localStorage.removeItem('finance-token')})} login(email:string,password:string){this.authBusy.set(true);this.authError.set('');this.http.post<any>('/api/v1/auth/login',{email,password}).subscribe({next:r=>this.completeLogin(r),error:()=>{this.authBusy.set(false);this.authError.set('Invalid email address or password.')}})} bootstrap(displayName:string,email:string,password:string){this.authBusy.set(true);this.authError.set('');this.http.post<any>('/api/v1/auth/bootstrap',{displayName,email,password}).subscribe({next:r=>this.completeLogin(r),error:x=>{this.authBusy.set(false);this.authError.set(x.error?.error||'Could not create administrator.')}})} completeLogin(r:any){localStorage.setItem('finance-token',r.token);this.authUser.set(r.user);this.setupRequired.set(false);this.authBusy.set(false);this.loadCategories();this.showDashboard()} logout(){localStorage.removeItem('finance-token');this.authUser.set(null);this.analytics.set(null);this.tab.set('dashboard')}
  showDashboard(){this.tab.set('dashboard');this.loading.set(true);this.error.set('');const params:any={months:this.dashboardMonths()};if(this.dashboardRange()!=='months')params.period=this.dashboardRange();this.http.get<Analytics>('/api/v1/analytics/overview',{params}).subscribe({next:x=>{this.analytics.set(x);this.loading.set(false)},error:x=>{this.error.set(x.error?.detail||this.t('loadDashboardError'));this.loading.set(false)}})}
  setDashboardPeriod(months:number){this.dashboardRange.set('months');this.dashboardMonths.set(months);this.dashboardInsight.set(null);this.showDashboard()} setDashboardCalendarPeriod(period:'this-year'|'last-year'){this.dashboardRange.set(period);this.dashboardInsight.set(null);this.showDashboard()}
  periodLabel(){return this.dashboardRange()==='this-year'?this.t('currentYear'):this.dashboardRange()==='last-year'?this.t('lastYear'):this.dashboardMonths()===1?this.t('thisMonth'):this.dashboardMonths()+' '+this.t('months')}
  inspectKpi(title:string,value:number,currency:string,detail:string,ledger:any){this.dashboardInsight.set({title,value:this.money(value,currency),detail,ledger})}
  inspectCount(title:string,value:number,detail:string,ledger:any){this.dashboardInsight.set({title,value:value.toLocaleString(this.language()==='nl'?'nl-NL':'en-NL'),detail,ledger})}
  inspectMonth(m:Point,currency:string){this.dashboardInsight.set({title:this.monthLabel(m.period!),value:this.signedMoney(m.net,currency),detail:this.t('incoming')+' '+this.money(m.income,currency)+' / '+this.t('outgoing')+' '+this.money(m.expenses,currency),ledger:{period:m.period}})}
  inspectNamed(item:Named,type:string,currency:string,ledger:any){this.dashboardInsight.set({title:this.categoryText(item.name),value:this.money(item.total,currency),detail:type+' / '+item.count+' '+this.t('transactions').toLowerCase(),ledger})}
  inspectDay(day:any,currency:string){this.dashboardInsight.set({title:new Date(day.date+'T00:00:00').toLocaleDateString(this.language()==='nl'?'nl-NL':'en-NL'),value:this.money(day.value,currency),detail:this.t('dailyExpenseActivity')+' / '+(day.count||0)+' '+this.t('transactions').toLowerCase(),ledger:{from:day.date,to:day.date,direction:'debit'}})}
  inspectAccount(account:any){this.dashboardInsight.set({title:account.displayName||account.accountName||this.t('account'),value:this.money(account.balance,account.currency),detail:this.maskIban(account.iban),ledger:{accountId:account.id}})}
  openInsightLedger(filter:any){this.resetLedgerFilters();if(filter.accountId)this.ledgerAccountId.set(filter.accountId);if(filter.category)this.ledgerFilterCategory.set(filter.category);if(filter.search)this.ledgerSearch.set(filter.search);if(filter.direction)this.ledgerDirection.set(filter.direction);if(filter.from)this.ledgerFrom.set(filter.from);if(filter.to)this.ledgerTo.set(filter.to);if(filter.period){this.ledgerFrom.set(filter.period+'-01');this.ledgerTo.set(new Date(Number(filter.period.slice(0,4)),Number(filter.period.slice(5,7)),0).toISOString().slice(0,10))}if(!filter.from&&!filter.period&&this.analytics()?.rangeStart)this.ledgerFrom.set(this.analytics()!.rangeStart!);this.loadLedger()}
  refresh(){const current=this.tab();if(current==='dashboard')this.showDashboard();else if(current==='imports')this.loadImports();else if(current==='monthly')this.loadMonthlyOverview();else if(current==='year')this.loadYearOverview();else if(current==='ledger')this.loadLedger();else if(current==='accounts')this.showAccounts();else if(current==='users')this.loadUsers();else if(current==='transactions')this.loadTransactions()}
  money(value:number|null|undefined,currency='EUR'){if(value==null)return String.fromCharCode(8212);if(currency==='MIXED')return new Intl.NumberFormat(this.language()==='nl'?'nl-NL':'en-NL',{maximumFractionDigits:2}).format(value)+' mixed';return new Intl.NumberFormat(this.language()==='nl'?'nl-NL':'en-NL',{style:'currency',currency:currency||'EUR'}).format(value)}
  signedMoney(v:number,c:string){return (v>=0?'+':'')+this.money(v,c)}
  shortMax(rows:Point[]){return Math.max(1,...rows.flatMap(x=>[x.income,x.expenses]))}
  barHeight(v:number,rows:Point[]){return Math.max(2,v/this.shortMax(rows)*100)}
  monthLabel(v:string){return new Date(v+'-01T00:00:00').toLocaleDateString(this.language()==='nl'?'nl-NL':'en-NL',{month:'short'})}
  total(rows:Named[]){return rows.reduce((a,b)=>a+b.total,0)}
  color(i:number){return this.colors[i%this.colors.length]}
  donut(rows:Named[]){let p=0;const sum=this.total(rows)||1;return `conic-gradient(${rows.slice(0,8).map((x,i)=>{const s=p;p+=x.total/sum*100;return `${this.color(i)} ${s}% ${p}%`}).join(',')})`}
  linePoints(rows:{balance:number}[]){const vals=rows.map(x=>x.balance),min=Math.min(...vals),max=Math.max(...vals),range=max-min||1;return rows.map((x,i)=>`${i/(rows.length-1||1)*800},${205-(x.balance-min)/range*185}`).join(' ')}
  areaPoints(rows:{balance:number}[]){return `0,220 ${this.linePoints(rows)} 800,220`}
  heatDays(rows:{date:string;value:number;count?:number}[]){const map=new Map(rows.map(x=>[x.date,x]));const max=Math.max(1,...rows.map(x=>x.value));const end=new Date((this.analytics()?.dataAsOf||new Date().toISOString().slice(0,10))+'T00:00:00');const start=new Date((this.analytics()?.rangeStart||end.toISOString().slice(0,10))+'T00:00:00');const days=Math.max(1,Math.round((end.getTime()-start.getTime())/86400000)+1),out=[];for(let i=days-1;i>=0;i--){const d=new Date(end);d.setDate(end.getDate()-i);const key=this.localDate(d),item=map.get(key),value=item?.value||0;out.push({date:key,value,count:item?.count||0,level:value===0?0:Math.min(4,Math.ceil(value/max*4))})}return out}
  percentOf(v:number,rows:Named[]){return v/Math.max(1,...rows.map(x=>x.total))*100}
  initials(v:string){return v.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()}
  maskIban(v?:string){return v?v.slice(0,4)+' '+String.fromCharCode(8226).repeat(4)+' '+v.slice(-4):this.t('noIban')}
  upload(e:Event){const file=(e.target as HTMLInputElement).files?.[0];if(file)this.uploadFile(file)} dragOver(event:DragEvent){event.preventDefault();this.dragging.set(true)} dragLeave(){this.dragging.set(false)} dropFile(event:DragEvent){event.preventDefault();this.dragging.set(false);const file=event.dataTransfer?.files?.[0];if(file)this.uploadFile(file)} uploadFile(file:File){this.busy.set(true);this.message.set('');const form=new FormData();form.append('file',file);this.http.post<any>('/api/v1/imports',form).subscribe({next:r=>{this.busy.set(false);this.message.set(r.count.toLocaleString()+' '+this.t('newImport'));setTimeout(()=>this.loadImports(),1200)},error:x=>{this.busy.set(false);this.message.set(x.error?.error||x.error?.detail||this.t('uploadFailed')+' ('+(x.status||'network')+')')}})}
  loadCategories(){this.http.get<CategoryGroup[]>('/api/v1/categories').subscribe(x=>this.categoryGroups.set(x))}
  subcategories(category:string){return this.categoryGroups().find(x=>x.name===category)?.subcategories||['Other']}
  categorySourceLabel(source?:number){return source===2?this.t('manual'):source===1?this.t('ibanRule'):this.t('automaticRecognition')}
  saveCategory(transaction:Tx,category:string,subcategory:string,applyToIban:boolean){this.http.put<any>('/api/v1/transactions/'+transaction.id+'/category',{category,subcategory,applyToIban}).subscribe({next:r=>{if(applyToIban&&transaction.counterpartyIban){for(const item of this.transactions())if(item.counterpartyIban===transaction.counterpartyIban){item.category=category;item.subcategory=subcategory;item.categorySource=1}}else{transaction.category=category;transaction.subcategory=subcategory;transaction.categorySource=2}this.transactions.set([...this.transactions()]);this.categoryMessage.set(r.affected+' '+this.t('categorySaved'))},error:x=>this.categoryMessage.set(x.error?.error||this.t('categorySaveError'))})}
  showAccounts(){this.tab.set('accounts');this.accountMessage.set('');if(this.analytics())return;this.loading.set(true);this.error.set('');this.http.get<Analytics>('/api/v1/analytics/overview',{params:{months:this.dashboardMonths()}}).subscribe({next:x=>{this.analytics.set(x);this.loading.set(false)},error:()=>{this.error.set(this.t('loadDashboardError'));this.loading.set(false)}})}
  saveAccount(account:any,displayName:string,accountKind:string){this.http.put<any>('/api/v1/accounts/'+account.id,{displayName,accountKind:Number(accountKind)}).subscribe({next:updated=>{account.displayName=updated.displayName;account.accountKind=updated.accountKind;this.analytics.set({...this.analytics()!});this.accountMessage.set(this.t('accountSaved'))},error:x=>this.accountMessage.set(x.error?.error||this.t('accountSaveError'))})}
  flowHeight(value:number,rows:Point[]){const max=Math.max(1,...rows.flatMap(x=>[x.externalIncoming||0,x.externalOutgoing||0,x.transferIn||0,x.transferOut||0]));return value===0?0:Math.max(3,value/max*100)}
  buildOverviewDays(overview:any){if(!overview)return[];const days=new Map<string,PeriodDay>();for(const group of overview.groups||[]){if(group.direction.startsWith('Transfer'))continue;for(const transaction of group.transactions||[]){const date=String(transaction.bookingDate).slice(0,10);if(!days.has(date))days.set(date,{date,income:0,outgoing:0,net:0,count:0,transactions:[]});const day=days.get(date)!;if(group.direction==='Incoming')day.income+=transaction.amount;else if(group.direction==='Outgoing')day.outgoing+=transaction.amount;day.net=day.income-day.outgoing;day.count++;day.transactions.push(transaction)}}return [...days.values()].sort((a,b)=>a.date.localeCompare(b.date))}
  buildOverviewCategories(overview:any){if(!overview)return[];const categories=new Map<string,PeriodCategory>();for(const group of overview.groups||[]){if(group.direction!=='Outgoing')continue;const current:PeriodCategory=categories.get(group.category)||{name:group.category,total:0,count:0,largest:0,transactions:[]};current.total+=group.total;current.count+=group.count;current.transactions.push(...group.transactions);current.largest=Math.max(current.largest,...group.transactions.map((x:any)=>x.amount));categories.set(group.category,current)}return [...categories.values()].sort((a,b)=>b.total-a.total)}
  buildYearMonths(overview:any){if(!overview)return[];const year=Number(overview.year||this.overviewYear());const months:YearMonth[]=Array.from({length:12},(_,index)=>({period:`${year}-${String(index+1).padStart(2,'0')}`,income:0,outgoing:0,net:0,transferIn:0,transferOut:0,count:0}));for(const group of overview.groups||[]){for(const transaction of group.transactions||[]){const month=months[Number(String(transaction.bookingDate).slice(5,7))-1];if(!month)continue;if(group.direction==='Incoming')month.income+=transaction.amount;else if(group.direction==='Outgoing')month.outgoing+=transaction.amount;else if(group.direction==='Transfer in')month.transferIn+=transaction.amount;else if(group.direction==='Transfer out')month.transferOut+=transaction.amount;month.count++}}for(const month of months)month.net=month.income-month.outgoing;return months}
  buildCategoryTrend(overview:any,category?:string){const year=Number(overview?.year||this.overviewYear());const points=Array.from({length:12},(_,index)=>({period:`${year}-${String(index+1).padStart(2,'0')}`,total:0}));if(!overview||!category)return points;for(const group of overview.groups||[]){if(group.direction!=='Outgoing'||group.category!==category)continue;for(const transaction of group.transactions||[]){const point=points[Number(String(transaction.bookingDate).slice(5,7))-1];if(point)point.total+=transaction.amount}}return points}
  calendarLeadingDays(){const [year,month]=this.overviewMonth().split('-').map(Number);if(!year||!month)return[];const mondayFirst=(new Date(year,month-1,1).getDay()+6)%7;return Array.from({length:mondayFirst})}
  calendarDays(){const [year,month]=this.overviewMonth().split('-').map(Number);if(!year||!month)return[];const map=new Map(this.overviewDays().map(x=>[x.date,x]));const count=new Date(year,month,0).getDate();const max=Math.max(1,...this.overviewDays().map(x=>x.outgoing));return Array.from({length:count},(_,index)=>{const day=index+1,date=`${year}-${String(month).padStart(2,'0')}-${String(day).padStart(2,'0')}`,value=map.get(date)?.outgoing||0;return{day,date,outgoing:value,level:value===0?0:Math.min(4,Math.ceil(value/max*4))}})}
  weekdayLabels(){const locale=this.language()==='nl'?'nl-NL':'en-NL';const monday=new Date(2026,0,5);return Array.from({length:7},(_,i)=>new Date(monday.getFullYear(),monday.getMonth(),monday.getDate()+i).toLocaleDateString(locale,{weekday:'narrow'}))}
  monthAverageDaily(){const days=this.calendarDays().length||1;return (this.monthlyOverview()?.outgoing||0)/days}
  monthLargestDay(){return Math.max(0,...this.overviewDays().map(x=>x.outgoing))}
  monthElapsedPercent(){const [year,month]=this.overviewMonth().split('-').map(Number),days=this.calendarDays().length||1,now=new Date();if(year===now.getFullYear()&&month===now.getMonth()+1)return Math.min(100,now.getDate()/days*100);return 100}
  dailyBarHeight(value:number){return value===0?2:Math.max(5,value/Math.max(1,...this.overviewDays().map(x=>x.outgoing))*100)}
  categoryPercent(value:number){return value/Math.max(1,this.monthlyOverview()?.outgoing||0)*100}
  yearBarHeight(value:number){return value===0?2:Math.max(4,value/Math.max(1,...this.yearMonths().flatMap(x=>[x.income,x.outgoing]))*100)}
  categoryTrendHeight(value:number){return value===0?2:Math.max(4,value/Math.max(1,...this.categoryTrend().map(x=>x.total))*100)}
  yearCategoryPattern(){return this.overviewCategories().slice(0,8).map(category=>{const values=this.buildCategoryTrend(this.monthlyOverview(),category.name).map(x=>x.total);return{name:category.name,values,max:Math.max(1,...values)}})}
  patternOpacity(value:number,max:number){return value===0?.08:.18+value/max*.82}
  savingsRate(income:number,savings:number){return income===0?0:savings/income*100}
  compactMoney(value:number,currency='EUR',signed=false){const prefix=signed&&value>0?'+':'';if(currency==='MIXED')return prefix+new Intl.NumberFormat(this.language()==='nl'?'nl-NL':'en-NL',{notation:'compact',maximumFractionDigits:1}).format(value);return prefix+new Intl.NumberFormat(this.language()==='nl'?'nl-NL':'en-NL',{style:'currency',currency:currency||'EUR',notation:'compact',maximumFractionDigits:1}).format(value)}
  shiftMonth(offset:number){const [year,month]=this.overviewMonth().split('-').map(Number),next=new Date(year,month-1+offset,1);this.loadMonthlyOverview(`${next.getFullYear()}-${String(next.getMonth()+1).padStart(2,'0')}`)}
  shiftYear(offset:number){this.loadYearOverview(this.overviewYear()+offset)}
  openDayLedger(date:string){this.resetLedgerFilters();this.ledgerFrom.set(String(date).slice(0,10));this.ledgerTo.set(String(date).slice(0,10));this.loadLedger()}
  openCategoryLedger(category:string){this.resetLedgerFilters();this.ledgerFilterCategory.set(category);this.ledgerFrom.set(this.monthlyOverview()?.from||'');this.ledgerTo.set(this.monthlyOverview()?.to||'');this.loadLedger()}
  openMonthLedger(period:string){this.goPeriod(period)}
  loadMonthlyOverview(month?:string){this.tab.set('monthly');this.loading.set(true);this.error.set('');const params:any={};if(month||this.overviewMonth())params.month=month||this.overviewMonth();this.http.get<any>('/api/v1/analytics/month',{params}).subscribe({next:x=>{this.monthlyOverview.set(x);this.overviewMonth.set(x.month);this.selectedOverviewDay.set('');this.selectedOverviewCategory.set('');this.loading.set(false)},error:()=>{this.error.set(this.t('loadMonthlyError'));this.loading.set(false)}})}  changeOverviewMonth(event:Event){this.loadMonthlyOverview((event.target as HTMLInputElement).value)} loadYearOverview(year?:number){this.tab.set('year');this.loading.set(true);this.error.set('');const selected=year||this.overviewYear();this.http.get<any>('/api/v1/analytics/month',{params:{year:selected}}).subscribe({next:x=>{this.monthlyOverview.set(x);this.overviewYear.set(x.year);this.selectedOverviewCategory.set('');this.selectedYearPeriod.set('');this.loading.set(false)},error:()=>{this.error.set(this.t('loadMonthlyError'));this.loading.set(false)}})} changeOverviewYear(event:Event){this.loadYearOverview(Number((event.target as HTMLInputElement).value))} loadUsers(){this.tab.set('users');this.http.get<any[]>('/api/v1/admin/users').subscribe({next:x=>this.users.set(x),error:()=>this.userMessage.set('Could not load users.')})} createUser(displayName:string,email:string,password:string,role:string){this.http.post<any>('/api/v1/admin/users',{displayName,email,password,role}).subscribe({next:()=>{this.userMessage.set('User created.');this.loadUsers()},error:x=>this.userMessage.set(x.error?.error||'Could not create user.')})} toggleUser(user:any){this.http.put<any>('/api/v1/admin/users/'+user.id,{isActive:!user.isActive}).subscribe({next:()=>this.loadUsers(),error:x=>this.userMessage.set(x.error?.error||'Could not update user.')})}
  availabilityText(value:string){const keys:any={'Credit utilization requires credit-limit data':'creditUtilizationUnavailable','Days until next paycheck requires a payroll schedule':'paycheckUnavailable','Payment method is not consistently supplied by CAMT':'paymentMethodUnavailable','Forecasts require more history and an explicit forecasting model':'forecastUnavailable'};return keys[value]?this.t(keys[value]):value}
  directionGroups(groups:any[],direction:string){return groups.filter(x=>x.direction===direction)}
  transferGroups(groups:any[]){return groups.filter(x=>x.direction==='Transfer in'||x.direction==='Transfer out')}
  monthFullLabel(month:string){return new Date(month+'-01T00:00:00').toLocaleDateString(this.language()==='nl'?'nl-NL':'en',{month:'long',year:'numeric'})}  loadImports(){this.tab.set('imports');this.loading.set(true);this.http.get<ImportRow[]>('/api/v1/imports').subscribe({next:x=>{this.imports.set(x);this.loading.set(false);if(x.some(i=>i.status===0||i.status===1))setTimeout(()=>{if(this.tab()==='imports')this.loadImports()},2500)},error:()=>{this.error.set(this.t('loadImportsError'));this.loading.set(false)}})}
  goLedger(){this.resetLedgerFilters();this.loadLedger()}
  goAccount(accountId:string){this.resetLedgerFilters();this.ledgerAccountId.set(accountId);this.loadLedger()}
  goCategory(category:string){this.resetLedgerFilters();this.ledgerFilterCategory.set(category);this.loadLedger()}
  goSearch(search:string,direction=''){this.resetLedgerFilters();this.ledgerSearch.set(search);this.ledgerDirection.set(direction);this.loadLedger()}
  goDay(date:string){this.resetLedgerFilters();this.ledgerFrom.set(date);this.ledgerTo.set(date);this.loadLedger()}
  goPeriod(period:string,direction=''){const start=period+'-01';const end=new Date(Number(period.slice(0,4)),Number(period.slice(5,7)),0).toISOString().slice(0,10);this.resetLedgerFilters();this.ledgerFrom.set(start);this.ledgerTo.set(end);this.ledgerDirection.set(direction);this.loadLedger()}
  goRecentMonths(months:number,direction=''){const now=new Date();const start=new Date(now.getFullYear(),now.getMonth()-months+1,1);this.resetLedgerFilters();this.ledgerFrom.set(this.localDate(start));this.ledgerTo.set(this.localDate(now));this.ledgerDirection.set(direction);this.loadLedger()}
  localDate(date:Date){const y=date.getFullYear(),m=String(date.getMonth()+1).padStart(2,'0'),d=String(date.getDate()).padStart(2,'0');return `${y}-${m}-${d}`}
  resetLedgerFilters(){this.ledgerAccountId.set('');this.ledgerFilterCategory.set('');this.ledgerFilterSubcategory.set('');this.ledgerDirection.set('');this.ledgerFrom.set('');this.ledgerTo.set('');this.ledgerMin.set('');this.ledgerMax.set('');this.ledgerSearch.set('')}  loadLedger(){this.tab.set('ledger');this.loading.set(true);this.selectedTransaction.set(null);const params:any={page:1,pageSize:200};const values:any={accountId:this.ledgerAccountId(),category:this.ledgerFilterCategory(),subcategory:this.ledgerFilterSubcategory(),direction:this.ledgerDirection(),dateFrom:this.ledgerFrom(),dateTo:this.ledgerTo(),minAmount:this.ledgerMin(),maxAmount:this.ledgerMax(),search:this.ledgerSearch()};for(const key of Object.keys(values))if(values[key]!==''&&values[key]!=null)params[key]=values[key];this.http.get<any>('/api/v1/transactions',{params}).subscribe({next:x=>{this.transactions.set(x.items);this.ledgerTotal.set(x.total);this.loading.set(false)},error:()=>{this.error.set(this.t('loadLedgerError'));this.loading.set(false)}})}
  applyLedgerFilters(search:string,subcategory:string,direction:string,from:string,to:string,min:string,max:string){this.ledgerSearch.set(search);this.ledgerFilterSubcategory.set(subcategory);this.ledgerDirection.set(direction);this.ledgerFrom.set(from);this.ledgerTo.set(to);this.ledgerMin.set(min);this.ledgerMax.set(max);this.loadLedger()}
  clearLedgerFilters(){this.ledgerFilterCategory.set('');this.ledgerFilterSubcategory.set('');this.ledgerDirection.set('');this.ledgerFrom.set('');this.ledgerTo.set('');this.ledgerMin.set('');this.ledgerMax.set('');this.ledgerSearch.set('');this.loadLedger()}
  openLedgerCategory(x:Tx){this.selectedTransaction.set(this.selectedTransaction()?.id===x.id?null:x);this.categoryDraft.set(x.category||'Miscellaneous');this.categoryMessage.set('')}
  selectLedgerAccount(event:Event){this.ledgerAccountId.set((event.target as HTMLSelectElement).value);this.loadLedger()}
  loadTransactions(search=''){this.tab.set('transactions');this.loading.set(true);this.http.get<any>('/api/v1/transactions',{params:{page:1,pageSize:200,search}}).subscribe({next:x=>{this.transactions.set(x.items);this.loading.set(false)},error:()=>{this.error.set(this.t('loadTransactionsError'));this.loading.set(false)}})}
  toggleTransaction(x:Tx){this.selectedTransaction.set(this.selectedTransaction()?.id===x.id?null:x);this.categoryDraft.set(x.category||'Miscellaneous')}
  shortId(v:string){return v?v.slice(0,8)+'…':'—'}
  prettyJson(v:string){try{return JSON.stringify(JSON.parse(v),null,2)}catch{return v||this.t('noSourceMetadata')}}
  statusLabel(v:number){return [this.t('pending'),this.t('processing'),this.t('completed'),this.t('completedWarnings'),this.t('failed'),this.t('duplicate')][v]||this.t('unknown')}
}
const authInterceptor:HttpInterceptorFn=(req,next)=>{const token=localStorage.getItem('finance-token');return token&&req.url.startsWith('/api/v1/')&&!req.url.includes('/auth/login')&&!req.url.includes('/auth/bootstrap')?next(req.clone({setHeaders:{Authorization:'Bearer '+token}})):next(req)};
bootstrapApplication(App,{providers:[provideHttpClient(withInterceptors([authInterceptor]))]}).catch(console.error);
