import {Component, computed, CUSTOM_ELEMENTS_SCHEMA, effect, inject, OnInit, signal} from '@angular/core';
import {bootstrapApplication} from '@angular/platform-browser';
import {HttpClient, HttpInterceptorFn, provideHttpClient, withInterceptors} from '@angular/common/http';
import {CommonModule} from '@angular/common';
import {UI, categoryText, type Language, type TranslationKey} from './i18n';
import {OfflineService, offlineInterceptor} from './offline';
import '@endeavoury/finance-design';

type CategoryGroup={name:string;subcategories:string[]};
type ImportRow={id:string;originalFileName:string;status:number;createdAtUtc:string;transactionCount:number;warningCount:number};
type Tx={id:string;bankStatementId:string;bankAccountId:string;externalTransactionId?:string;entryReference?:string;accountServicerReference?:string;instructionId?:string;endToEndId?:string;mandateId?:string;transactionId?:string;bookingDate:string;valueDate?:string;amount:number;currency:string;creditDebitIndicator:number;status?:string;bankTransactionCode?:string;proprietaryTransactionCode?:string;counterpartyName?:string;counterpartyIban?:string;counterpartyBic?:string;remittanceInformation?:string;additionalInformation?:string;fingerprint:string;rawEntryJson:string;createdAtUtc:string;balanceAfterTransaction:number;category?:string;subcategory?:string;categorySource?:number};
type Point={period?:string;date?:string;label?:string;income:number;expenses:number;net:number;transferIn?:number;transferOut?:number;externalIncoming?:number;externalOutgoing?:number};
type Named={name:string;total:number;count:number;average?:number;percent?:number};
type Analytics={generatedAtUtc:string;dataAsOf?:string;selectedMonths?:number;rangeStart?:string;currency:string;kpis:any;monthly:Point[];daily:Point[];weeks:Point[];runningBalance:{date:string;balance:number}[];categories:Named[];merchants:Named[];incomeSources:Named[];heatmap:{date:string;value:number;count:number}[];accounts:any[];unavailable:string[]};
type PeriodDay={date:string;income:number;outgoing:number;net:number;count:number;transactions:any[]};
type PeriodCategory={name:string;total:number;count:number;largest:number;transactions:any[]};
type YearMonth={period:string;income:number;outgoing:number;net:number;transferIn:number;transferOut:number;count:number};

@Component({selector:'app-root',standalone:true,imports:[CommonModule],schemas:[CUSTOM_ELEMENTS_SCHEMA],template:`
<section *ngIf="!authUser()" class="login-page">
  <ds-card class="login-card">
    <div class="brand"><span class="brandmark">F</span><span>Finance<br><b>Inzicht</b></span></div>
    <p class="eyebrow">{{setupRequired()?'First-time setup':'Secure sign in'}}</p>
    <h1>{{setupRequired()?'Create administrator':'Welcome back'}}</h1>
    <p class="muted">{{setupRequired()?'Create the first local administrator to protect your financial data.':'Sign in to continue to your private financial dashboard.'}}</p>
    <ds-input *ngIf="setupRequired()" #setupName label="Name" autocomplete="name" placeholder="Your name" (ds-input)="setupDisplayName.set($any(setupName).value)"></ds-input>
    <ds-input #loginEmail label="Email" type="email" autocomplete="email" placeholder="you@example.com"></ds-input>
    <ds-input #loginPassword label="Password" type="password" autocomplete="current-password" placeholder="At least 12 characters"></ds-input>
    <ds-alert *ngIf="authError()" tone="danger" heading="Sign-in failed">{{authError()}}</ds-alert>
    <ds-button variant="primary" full-width [loading]="authBusy()" (click)="setupRequired()?bootstrap(setupDisplayName()||$any(loginEmail).value.split('@')[0],$any(loginEmail).value,$any(loginPassword).value):login($any(loginEmail).value,$any(loginPassword).value)">{{setupRequired()?'Create administrator':'Sign in'}}</ds-button>
  </ds-card>
</section>
<ds-app-shell *ngIf="authUser()" class="shell" [class.compact]="sidebarCompact()">
  <ds-sidebar slot="sidebar" [label]="t('toggleNavigation')">
    <div slot="brand" class="brand"><span class="brandmark">F</span><span class="brand-copy">Finance<br><b>Inzicht</b></span><ds-icon-button class="sidebar-toggle" [label]="t('toggleNavigation')" (click)="toggleSidebar()"><ds-icon name="menu"></ds-icon></ds-icon-button></div>
    <ds-sidebar-item class="core-nav" value="dashboard" [active]="tab()==='dashboard'" (ds-activate)="mobileMenuOpen.set(false);showDashboard()"><ds-icon slot="icon" name="home"></ds-icon>{{t('overview')}}</ds-sidebar-item>
    <ds-sidebar-item class="core-nav" value="monthly" [active]="tab()==='monthly'" (ds-activate)="mobileMenuOpen.set(false);loadMonthlyOverview()"><ds-icon slot="icon" name="calendar"></ds-icon>{{t('monthlyOverview')}}</ds-sidebar-item>
    <ds-sidebar-item class="core-nav" value="year" [active]="tab()==='year'" (ds-activate)="mobileMenuOpen.set(false);loadYearOverview()"><ds-icon slot="icon" name="chart"></ds-icon>{{t('yearOverview')}}</ds-sidebar-item>
    <div class="secondary-nav-group" [class.open]="mobileMenuOpen()">
      <ds-sidebar-item value="ledger" [active]="tab()==='ledger'" (ds-activate)="mobileMenuOpen.set(false);loadLedger()"><ds-icon slot="icon" name="table"></ds-icon>{{t('ledger')}}</ds-sidebar-item>
      <ds-sidebar-item value="transactions" [active]="tab()==='transactions'" (ds-activate)="mobileMenuOpen.set(false);loadTransactions()"><ds-icon slot="icon" name="search"></ds-icon>{{t('rawValues')}}</ds-sidebar-item>
      <ds-sidebar-item value="accounts" [active]="tab()==='accounts'" (ds-activate)="mobileMenuOpen.set(false);showAccounts()"><ds-icon slot="icon" name="wallet"></ds-icon>{{t('accounts')}}</ds-sidebar-item>
      <ds-sidebar-item value="imports" [active]="tab()==='imports'" (ds-activate)="mobileMenuOpen.set(false);loadImports()"><ds-icon slot="icon" name="table"></ds-icon>{{t('imports')}}</ds-sidebar-item>
      <ds-sidebar-item value="import" [active]="tab()==='import'" (ds-activate)="mobileMenuOpen.set(false);tab.set('import')"><ds-icon slot="icon" name="upload"></ds-icon>{{t('uploadCamt')}}</ds-sidebar-item>
      <ds-sidebar-item *ngIf="isAdmin()" value="users" [active]="tab()==='users'" (ds-activate)="mobileMenuOpen.set(false);loadUsers()"><ds-icon slot="icon" name="user"></ds-icon>{{t('userManagement')}}</ds-sidebar-item>
    </div>
    <ds-sidebar-item class="mobile-more-button" value="more" [active]="mobileMenuOpen()" (ds-activate)="mobileMenuOpen.update(value=>!value)" [attr.aria-expanded]="mobileMenuOpen()"><ds-icon slot="icon" name="menu"></ds-icon>{{t('more')}}</ds-sidebar-item>
    <div slot="footer" class="side-note"><ds-status-badge [tone]="offline.online()?'success':'warning'">{{offline.online()?t('systemOnline'):t('systemOffline')}}</ds-status-badge><small>{{offline.pending()?offline.pending()+' '+t('changesWaiting'):(offline.online()?t('workerActive'):t('savedDataAvailable'))}}</small></div>
  </ds-sidebar>

  <div slot="header" class="app-header"><div><small>{{t('personalFinance')}}</small><h1>{{title()}}</h1></div><div class="header-actions"><ds-select class="language-switch" [label]="t('language')" [options]="languageOptions" [value]="language()" (ds-change)="setLanguage($event)"></ds-select><ds-icon-button class="refresh-btn" [label]="t('refresh')" (click)="refresh()"><ds-icon name="refresh"></ds-icon></ds-icon-button><ds-button class="profile-chip" variant="ghost" [title]="t('signOut')" (click)="logout()"><ds-avatar [name]="authUser()?.displayName||'User'"></ds-avatar><span class="profile-name">{{authUser()?.displayName}}</span></ds-button><ds-button class="header-import" variant="primary" (click)="tab.set('import')"><ds-icon slot="prefix" name="upload"></ds-icon>{{t('importFiles')}}</ds-button></div></div>
  <ds-alert *ngIf="!offline.online() || offline.pending()" class="offline-banner" [tone]="offline.online()?'info':'warning'" [heading]="offline.online()?t('syncPending'):t('offlineMode')">{{offline.online()?(offline.pending()+' '+t('changesWaiting')):t('offlineExplanation')}}</ds-alert>
  <main>
      <ds-loading-state *ngIf="loading()" [label]="t('calculating')"></ds-loading-state>
      <ds-alert *ngIf="error()" tone="danger" [heading]="error()"><ds-button size="small" variant="secondary" (click)="refresh()">{{t('tryAgain')}}</ds-button></ds-alert>

      <ng-container *ngIf="tab()==='dashboard' && analytics() as a">
        <section class="application-page dashboard-page">
        <ds-page-header class="hero-row" [eyebrow]="t('financialOverview')" [heading]="t('dashboardHeadline')" [description]="'Based on '+(a.kpis.transactionCount | number)+' imported transactions · Updated '+(a.generatedAtUtc | date:'shortTime')"><ds-button-group slot="actions" class="period" aria-label="Dashboard period"><ds-button size="small" [variant]="dashboardMonths()===1 && dashboardRange()==='months'?'secondary':'ghost'" (click)="setDashboardPeriod(1)">{{t('thisMonth')}}</ds-button><ds-button size="small" [variant]="dashboardMonths()===3 && dashboardRange()==='months'?'secondary':'ghost'" (click)="setDashboardPeriod(3)">3 {{t('months')}}</ds-button><ds-button size="small" [variant]="dashboardMonths()===12 && dashboardRange()==='months'?'secondary':'ghost'" (click)="setDashboardPeriod(12)">12 {{t('months')}}</ds-button><ds-button size="small" [variant]="dashboardRange()==='this-year'?'secondary':'ghost'" (click)="setDashboardCalendarPeriod('this-year')">{{t('currentYear')}}</ds-button><ds-button size="small" [variant]="dashboardRange()==='last-year'?'secondary':'ghost'" (click)="setDashboardCalendarPeriod('last-year')">{{t('lastYear')}}</ds-button></ds-button-group></ds-page-header>
        <ds-kpi-grid class="kpi-grid primary" [columns]="4">
          <ds-metric class="dashboard-link" role="button" tabindex="0" tone="accent" [label]="t('currentBalance')" [value]="money(a.kpis.currentBalance,a.currency)" [detail]="'Across '+a.kpis.activeAccounts+' active account'+(a.kpis.activeAccounts===1?'':'s')" (click)="inspectKpi(t('currentBalance'),a.kpis.currentBalance,a.currency,t('balanceAcrossAccounts'),{})" (keydown.enter)="inspectKpi(t('currentBalance'),a.kpis.currentBalance,a.currency,t('balanceAcrossAccounts'),{})"></ds-metric>
          <ds-metric class="dashboard-link" role="button" tabindex="0" tone="success" [label]="t('income')+' · '+periodLabel()" [value]="money(a.kpis.incomeThisMonth,a.currency)" [detail]="t('cashInflow')" (click)="inspectKpi(t('income'),a.kpis.incomeThisMonth,a.currency,periodLabel()+' '+t('cashInflow'),{direction:'credit'})" (keydown.enter)="inspectKpi(t('income'),a.kpis.incomeThisMonth,a.currency,periodLabel()+' '+t('cashInflow'),{direction:'credit'})"></ds-metric>
          <ds-metric class="dashboard-link" role="button" tabindex="0" tone="danger" [label]="t('expensesPeriod')+' · '+periodLabel()" [value]="money(a.kpis.expensesThisMonth,a.currency)" [detail]="'Avg '+money(a.kpis.averageDailySpending,a.currency)+' / day'" (click)="inspectKpi(t('expensesPeriod'),a.kpis.expensesThisMonth,a.currency,periodLabel()+' '+t('cashOutflow'),{direction:'debit'})" (keydown.enter)="inspectKpi(t('expensesPeriod'),a.kpis.expensesThisMonth,a.currency,periodLabel()+' '+t('cashOutflow'),{direction:'debit'})"></ds-metric>
          <ds-metric class="dashboard-link" role="button" tabindex="0" [tone]="a.kpis.savingsThisMonth<0?'danger':'warning'" [label]="t('savingsPeriod')+' · '+periodLabel()" [value]="money(a.kpis.savingsThisMonth,a.currency)" [detail]="(a.kpis.savingsRate|number:'1.0-1')+'% savings rate'" (click)="inspectKpi(t('savingsPeriod'),a.kpis.savingsThisMonth,a.currency,periodLabel()+' '+t('netSavings'),{})" (keydown.enter)="inspectKpi(t('savingsPeriod'),a.kpis.savingsThisMonth,a.currency,periodLabel()+' '+t('netSavings'),{})"></ds-metric>
        </ds-kpi-grid>

        <ds-kpi-grid class="kpi-grid secondary" [columns]="6">
          <ds-metric [label]="t('netWorth')" [value]="money(a.kpis.netWorth,a.currency)" [detail]="'Total assets '+money(a.kpis.totalAssets,a.currency)"></ds-metric>
          <ds-metric [tone]="a.kpis.cashFlow<0?'danger':'success'" [label]="t('cashFlow')" [value]="signedMoney(a.kpis.cashFlow,a.currency)" [detail]="a.kpis.positiveCashFlowStreak+' positive month streak'"></ds-metric>
          <ds-metric [label]="t('monthlyBurnRate')" [value]="money(a.kpis.averageMonthlySpending,a.currency)" [detail]="money(a.kpis.burnRate,a.currency)+' per day'"></ds-metric>
          <ds-metric [label]="t('cashRunway')" [value]="a.kpis.daysOfCashRemaining==null?'—':(a.kpis.daysOfCashRemaining|number:'1.0-0')+' '+t('days')" [detail]="a.kpis.emergencyFundMonths==null?t('notEnoughHistory'):(a.kpis.emergencyFundMonths|number:'1.1-1')+' '+t('emergencyMonths')"></ds-metric>
          <ds-metric class="dashboard-link" role="button" tabindex="0" tone="info" [label]="t('transactions')" [value]="(a.kpis.transactionCount|number)||''" [detail]="(a.kpis.purchaseCount|number)+' outgoing payments'" (click)="inspectCount(t('transactions'),a.kpis.transactionCount,periodLabel()+' '+t('activity'),{})" (keydown.enter)="inspectCount(t('transactions'),a.kpis.transactionCount,periodLabel()+' '+t('activity'),{})"></ds-metric>
          <ds-metric [label]="t('averageTransaction')" [value]="money(a.kpis.averageTransaction,a.currency)" [detail]="'Median expense '+money(a.kpis.medianExpense,a.currency)"></ds-metric>
        </ds-kpi-grid>

        <section class="chart-grid">
          <article class="panel wide cashflow-panel"><div class="panel-head"><div><p class="eyebrow">{{t('cashFlowChart')}}</p><h3>{{t('incomeVsExpenses')}}</h3></div><div class="legend"><i class="income"></i>Income <i class="expense"></i>{{t('expensesPeriod')}}</div></div>
            <div *ngIf="!a.monthly.length" class="empty">{{t('importMoreHistory')}}</div>
            <div class="bar-chart" *ngIf="a.monthly.length"><div class="y-guide"><span>{{money(shortMax(a.monthly),a.currency)}}</span><span>{{money(shortMax(a.monthly)/2,a.currency)}}</span><span>0</span></div><div class="bars"><div class="bar-group dashboard-link" *ngFor="let m of a.monthly" role="button" tabindex="0" (click)="inspectMonth(m,a.currency)" (keydown.enter)="inspectMonth(m,a.currency)"><div class="bar-pair"><i class="income-bar" [style.height.%]="barHeight(m.income,a.monthly)"></i><i class="expense-bar" [style.height.%]="barHeight(m.expenses,a.monthly)"></i></div><small>{{monthLabel(m.period!)}}</small></div></div></div>
          </article>
          <article class="panel"><div class="panel-head"><div><p class="eyebrow">{{t('spending')}}</p><h3>{{t('byCategory')}}</h3></div></div><div *ngIf="!a.categories.length" class="empty">{{t('noExpense')}}</div><div class="donut-wrap" *ngIf="a.categories.length"><div class="donut" [style.background]="donut(a.categories)"><div><b>{{money(total(a.categories),a.currency)}}</b><small>{{t('totalSpent')}}</small></div></div><div class="category-list"><div *ngFor="let c of a.categories.slice(0,6);let i=index" class="dashboard-list-link" role="button" tabindex="0" (click)="inspectNamed(c,t('spendingCategory'),a.currency,{category:c.name})" (keydown.enter)="inspectNamed(c,t('spendingCategory'),a.currency,{category:c.name})"><i [style.background]="color(i)"></i><span>{{categoryText(c.name)}}</span><b>{{c.percent|number:'1.0-0'}}%</b></div></div></div></article>

          <article class="panel wide"><div class="panel-head"><div><p class="eyebrow">{{t('balanceTrend')}}</p><h3>{{t('runningBalance')}}</h3></div><b>{{money(a.kpis.currentBalance,a.currency)}}</b></div><div class="line-wrap" *ngIf="a.runningBalance.length"><svg viewBox="0 0 800 220" preserveAspectRatio="none"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="var(--ds-color-data-1)" stop-opacity=".25"/><stop offset="1" stop-color="var(--ds-color-data-1)" stop-opacity="0"/></linearGradient></defs><polygon [attr.points]="areaPoints(a.runningBalance)" fill="url(#area)"/><polyline [attr.points]="linePoints(a.runningBalance)" fill="none" stroke="var(--ds-color-data-1)" stroke-width="3" vector-effect="non-scaling-stroke"/></svg><div class="axis"><span>{{a.runningBalance[0].date|date:'MMM d'}}</span><span>{{a.runningBalance[a.runningBalance.length-1].date|date:'MMM d'}}</span></div></div><div *ngIf="!a.runningBalance.length" class="empty">{{t('noBalanceHistory')}}</div></article>
          <article class="panel"><div class="panel-head"><div><p class="eyebrow">{{t('income')}}</p><h3>{{t('topSources')}}</h3></div></div><div class="rank-list"><div *ngFor="let s of a.incomeSources;let i=index" class="dashboard-list-link" role="button" tabindex="0" (click)="inspectNamed(s,t('income'),a.currency,{search:s.name,direction:'credit'})" (keydown.enter)="inspectNamed(s,t('income'),a.currency,{search:s.name,direction:'credit'})"><span class="rank">{{i+1}}</span><div><b>{{s.name}}</b><small>{{s.count}} {{s.count===1?t('payment'):t('payments')}}</small></div><strong>{{money(s.total,a.currency)}}</strong></div><div *ngIf="!a.incomeSources.length" class="empty">{{t('noIncomeSources')}}</div></div></article>

          <article class="panel full"><div class="panel-head"><div><p class="eyebrow">{{t('monthlyMoneyFlowLabel')}}</p><h3>{{t('monthlyMoneyFlow')}}</h3><p class="muted">{{t('transferExplanation')}}</p></div><div class="flow-legend"><span><i class="fi"></i>{{t('incoming')}}</span><span><i class="fo"></i>{{t('outgoing')}}</span><span><i class="fti"></i>{{t('transferIn')}}</span><span><i class="fto"></i>{{t('transferOut')}}</span></div></div><div class="monthly-flow" *ngIf="a.monthly.length"><div class="flow-month dashboard-link" *ngFor="let m of a.monthly" role="button" tabindex="0" (click)="inspectMonth(m,a.currency)" (keydown.enter)="inspectMonth(m,a.currency)"><div class="flow-bars"><i class="flow-in" [style.height.%]="flowHeight(m.externalIncoming||0,a.monthly)"></i><i class="flow-out" [style.height.%]="flowHeight(m.externalOutgoing||0,a.monthly)"></i><i class="flow-transfer-in" [style.height.%]="flowHeight(m.transferIn||0,a.monthly)"></i><i class="flow-transfer-out" [style.height.%]="flowHeight(m.transferOut||0,a.monthly)"></i></div><b [class.negative]="m.net<0">{{signedMoney(m.net,a.currency)}}</b><small>{{monthLabel(m.period!)}}</small></div></div><div *ngIf="!a.monthly.length" class="empty">{{t('noMonthlyFlows')}}</div></article>
          <article class="panel full"><div class="panel-head"><div><p class="eyebrow">{{t('spendingPatterns')}}</p><h3>{{t('dailyExpenseActivity')}}</h3></div><div class="heat-legend">{{t('less')}} <i></i><i></i><i></i><i></i><i></i> {{t('more')}}</div></div><div class="heatmap"><div *ngFor="let day of heatDays(a.heatmap)" [class]="'heat h'+day.level" role="button" tabindex="0" (click)="inspectDay(day,a.currency)" (keydown.enter)="inspectDay(day,a.currency)" [title]="day.date+': '+money(day.value,a.currency)"></div></div><div class="heat-months"><span>{{analytics()?.rangeStart|date:'mediumDate'}}</span><span>{{analytics()?.dataAsOf|date:'mediumDate'}}</span></div></article>

          <article class="panel"><div class="panel-head"><div><p class="eyebrow">{{t('expenseMetrics')}}</p><h3>{{t('purchaseProfile')}}</h3></div></div><dl class="metrics"><div><dt>{{t('largestPurchase')}}</dt><dd>{{money(a.kpis.largestPurchase,a.currency)}}</dd></div><div><dt>{{t('smallestPurchase')}}</dt><dd>{{money(a.kpis.smallestPurchase,a.currency)}}</dd></div><div><dt>{{t('averagePurchase')}}</dt><dd>{{money(a.kpis.averageMonthlySpending/Math.max(1,a.kpis.purchaseCount),a.currency)}}</dd></div><div><dt>{{t('negativeFlowMonths')}}</dt><dd>{{a.kpis.negativeCashFlowMonths}}</dd></div></dl></article>
          <article class="panel wide"><div class="panel-head"><div><p class="eyebrow">{{t('merchants')}}</p><h3>{{t('whereMoneyGoes')}}</h3></div></div><div class="merchant-list"><div *ngFor="let m of a.merchants;let i=index" class="dashboard-list-link" role="button" tabindex="0" (click)="inspectNamed(m,t('merchants'),a.currency,{search:m.name,direction:'debit'})" (keydown.enter)="inspectNamed(m,t('merchants'),a.currency,{search:m.name,direction:'debit'})"><div class="merchant-avatar">{{initials(m.name)}}</div><div class="merchant-name"><b>{{m.name}}</b><small>{{m.count}} {{t('transactions')}} · {{t('averageShort')}} {{money(m.average,a.currency)}}</small></div><div class="merchant-bar"><i [style.width.%]="percentOf(m.total,a.merchants)"></i></div><strong>{{money(m.total,a.currency)}}</strong></div><div *ngIf="!a.merchants.length" class="empty">{{t('noMerchantData')}}</div></div></article>

          <article class="panel full"><div class="panel-head"><div><p class="eyebrow">{{t('accounts')}}</p><h3>{{t('accountOverview')}}</h3></div><ds-button size="small" variant="ghost" (click)="goLedger()">{{t('viewLedger')}} →</ds-button></div><div class="account-grid"><div class="account dashboard-link" *ngFor="let account of a.accounts" role="button" tabindex="0" (click)="inspectAccount(account)" (keydown.enter)="inspectAccount(account)"><span class="bank-icon"><ds-icon name="wallet"></ds-icon></span><div><b>{{account.displayName||account.accountName||t('bankAccount')}}</b><small>{{maskIban(account.iban)}}</small></div><strong>{{money(account.balance,account.currency)}}</strong></div></div></article>
        </section>
        <section class="data-note"><ds-icon name="info"></ds-icon><div><b>{{t('dataAvailability')}}</b><p>{{t('dataAvailabilityText')}}</p><span *ngFor="let note of a.unavailable">{{availabilityText(note)}}</span></div></section>
        </section>
      </ng-container>

      <section *ngIf="tab()==='monthly' && monthlyOverview() as m" class="application-page period-page month-page">
        <ds-page-header class="period-hero" [eyebrow]="t('monthlyOverview')" [heading]="monthFullLabel(m.month)" [description]="t('monthlyText')"><div slot="actions" class="period-navigator"><ds-icon-button size="large" (click)="shiftMonth(-1)" [label]="t('previousMonth')"><ds-icon name="chevron-left"></ds-icon></ds-icon-button><label><span>{{t('selectMonth')}}</span><input type="month" [value]="overviewMonth()" (change)="changeOverviewMonth($event)"></label><ds-icon-button size="large" (click)="shiftMonth(1)" [label]="t('nextMonth')"><ds-icon name="chevron-right"></ds-icon></ds-icon-button></div></ds-page-header>
        <section class="period-summary budget-strip">
          <article class="income-summary"><label>{{t('incomePeriod')}}</label><strong>{{money(m.incoming,m.currency)}}</strong><small>{{t('externalCashReceived')}}</small></article>
          <article class="expense-summary"><label>{{t('expensesPeriod')}}</label><strong>{{money(m.outgoing,m.currency)}}</strong><small>{{t('externalSpending')}}</small></article>
          <article class="savings-summary" [class.negative]="m.net<0"><label>{{t('savingsPeriod')}}</label><strong>{{signedMoney(m.net,m.currency)}}</strong><small>{{t('incomingMinusOutgoing')}}</small></article>
          <article class="transfer-summary"><label>{{t('ownTransfers')}}</label><strong>{{money(m.transferIn+m.transferOut,m.currency)}}</strong><small>{{t('transfersExcluded')}}</small></article>
          <article class="activity-summary"><label>{{t('transactions')}}</label><strong>{{m.transactionCount|number}}</strong><small>{{m.from|date:'mediumDate'}} – {{m.to|date:'mediumDate'}}</small></article>
          <article class="rate-summary"><label>{{t('savingsRate')}}</label><strong>{{savingsRate(m.incoming,m.net)|number:'1.0-1'}}%</strong><small>{{t('monthRhythm')}}</small></article>
        </section>

        <div class="month-analytics-grid">
          <article class="period-panel daily-panel"><div class="panel-head"><div><p class="eyebrow">{{t('dailySpending')}}</p><h3>{{t('spendingTimeline')}}</h3></div><small>{{money(monthAverageDaily(),m.currency)}} / {{t('day')}}</small></div><div class="daily-scroll" *ngIf="overviewDays().length"><div class="daily-chart"><button *ngFor="let day of overviewDays()" type="button" [class.selected]="activeOverviewDay()?.date===day.date" (click)="selectedOverviewDay.set(day.date)" [attr.aria-label]="(day.date|date:'mediumDate')+' '+money(day.outgoing,m.currency)"><span class="daily-bar"><i [style.height.%]="dailyBarHeight(day.outgoing)"></i></span><small>{{day.date|date:'d'}}</small></button></div></div><div class="empty" *ngIf="!overviewDays().length">{{t('noOutgoingMonth')}}</div><div class="selection-summary" *ngIf="activeOverviewDay() as day"><div><p class="eyebrow">{{day.date|date:'fullDate'}}</p><strong>{{money(day.outgoing,m.currency)}}</strong><small>{{day.count}} {{t('transactions')}} · {{money(day.income,m.currency)}} {{t('incoming').toLowerCase()}}</small></div><ds-button size="small" variant="secondary" (click)="openDayLedger(day.date)">{{t('viewInLedger')}}</ds-button></div></article>

          <article class="period-panel pace-panel"><div class="panel-head"><div><p class="eyebrow">{{t('spendingPace')}}</p><h3>{{t('monthRhythm')}}</h3></div></div><div class="pace-ring" [style.--pace]="monthElapsedPercent()+'%'"><div><strong>{{monthElapsedPercent()|number:'1.0-0'}}%</strong><small>{{t('monthElapsed')}}</small></div></div><dl class="pace-stats"><div><dt>{{t('averagePerDay')}}</dt><dd>{{money(monthAverageDaily(),m.currency)}}</dd></div><div><dt>{{t('largestDay')}}</dt><dd>{{money(monthLargestDay(),m.currency)}}</dd></div><div><dt>{{t('activeDays')}}</dt><dd>{{overviewDays().length}}</dd></div></dl></article>

          <article class="period-panel calendar-panel"><div class="panel-head"><div><p class="eyebrow">{{t('spendingCalendar')}}</p><h3>{{monthFullLabel(m.month)}}</h3></div><div class="heat-legend">{{t('less')}} <i></i><i></i><i></i><i></i> {{t('more')}}</div></div><div class="calendar-weekdays"><span *ngFor="let label of weekdayLabels()">{{label}}</span></div><div class="spending-calendar"><span class="calendar-blank" *ngFor="let blank of calendarLeadingDays()"></span><button *ngFor="let day of calendarDays()" type="button" [class]="'calendar-day h'+day.level" [class.selected]="activeOverviewDay()?.date===day.date" (click)="selectedOverviewDay.set(day.date)"><b>{{day.day}}</b><small *ngIf="day.outgoing">{{compactMoney(day.outgoing,m.currency)}}</small></button></div></article>

          <article class="period-panel category-panel"><div class="panel-head"><div><p class="eyebrow">{{t('categories')}}</p><h3>{{t('spendingByCategory')}}</h3></div><b>{{money(m.outgoing,m.currency)}}</b></div><div class="category-bars"><button *ngFor="let c of overviewCategories();let i=index" type="button" [class.selected]="activeOverviewCategory()?.name===c.name" (click)="selectedOverviewCategory.set(c.name)"><span><i [style.background]="color(i)"></i><b>{{categoryText(c.name)}}</b><small>{{c.count}} {{t('transactions')}}</small></span><strong>{{money(c.total,m.currency)}}</strong><em><i [style.width.%]="categoryPercent(c.total)"></i></em></button></div><div class="empty" *ngIf="!overviewCategories().length">{{t('noExpense')}}</div><div class="selection-summary category-selection" *ngIf="activeOverviewCategory() as c"><div><p class="eyebrow">{{categoryText(c.name)}}</p><strong>{{money(c.total,m.currency)}}</strong><small>{{c.count}} {{t('transactions')}} · {{t('largestPurchase')}} {{money(c.largest,m.currency)}}</small></div><ds-button size="small" variant="secondary" (click)="openCategoryLedger(c.name)">{{t('viewInLedger')}}</ds-button></div></article>
        </div>

        <details class="period-details" open><summary><div><p class="eyebrow">{{t('cashFlow')}}</p><h3>{{t('incomeAndSpendingDetails')}}</h3></div><span>{{t('showDetails')}} ⌄</span></summary><div class="balance-columns"><section><div class="balance-column-head incoming-head"><div><p class="eyebrow">{{t('incoming')}}</p><h3>{{t('incomeByCategory')}}</h3></div><b>{{money(m.incoming,m.currency)}}</b></div><details class="balance-group" *ngFor="let g of directionGroups(m.groups,'Incoming')"><summary><div><b>{{categoryText(g.category)}}</b><small>{{categoryText(g.subcategory)}} · {{g.count}} {{t('transactions')}}</small></div><strong>{{money(g.total,m.currency)}}</strong><span>⌄</span></summary><div class="period-transactions"><button *ngFor="let x of g.transactions" (click)="openDayLedger(x.bookingDate)"><span><b>{{x.counterpartyName||x.accountName||t('unknownCounterparty')}}</b><small>{{x.bookingDate|date:'mediumDate'}} · {{x.accountName}}</small><em>{{x.remittanceInformation||x.additionalInformation||'—'}}</em></span><strong class="credit-value">{{money(x.amount,x.currency)}}</strong></button></div></details></section><section><div class="balance-column-head outgoing-head"><div><p class="eyebrow">{{t('outgoing')}}</p><h3>{{t('spendingByCategory')}}</h3></div><b>{{money(m.outgoing,m.currency)}}</b></div><details class="balance-group" *ngFor="let g of directionGroups(m.groups,'Outgoing')"><summary><div><b>{{categoryText(g.category)}}</b><small>{{categoryText(g.subcategory)}} · {{g.count}} {{t('transactions')}}</small></div><strong>{{money(g.total,m.currency)}}</strong><span>⌄</span></summary><div class="period-transactions"><button *ngFor="let x of g.transactions" (click)="openDayLedger(x.bookingDate)"><span><b>{{x.counterpartyName||x.accountName||t('unknownCounterparty')}}</b><small>{{x.bookingDate|date:'mediumDate'}} · {{x.accountName}}</small><em>{{x.remittanceInformation||x.additionalInformation||'—'}}</em></span><strong class="debit-value">{{money(x.amount,x.currency)}}</strong></button></div></details></section></div></details>
        <ng-container *ngTemplateOutlet="transferBlock;context:{$implicit:m}"></ng-container>
      </section>

      <section *ngIf="tab()==='year' && monthlyOverview() as m" class="application-page period-page year-page">
        <ds-page-header class="period-hero" [eyebrow]="t('yearOverview')" [heading]="''+m.year" [description]="t('yearOverviewText')"><div slot="actions" class="period-navigator year-navigator"><ds-icon-button size="large" (click)="shiftYear(-1)" [label]="t('previousYear')"><ds-icon name="chevron-left"></ds-icon></ds-icon-button><label><span>{{t('selectYear')}}</span><input type="number" min="2000" max="2100" [value]="overviewYear()" (change)="changeOverviewYear($event)"></label><ds-icon-button size="large" (click)="shiftYear(1)" [label]="t('nextYear')"><ds-icon name="chevron-right"></ds-icon></ds-icon-button></div></ds-page-header>
        <section class="period-summary budget-strip">
          <article class="income-summary"><label>{{t('incomePeriod')}}</label><strong>{{money(m.incoming,m.currency)}}</strong><small>{{t('externalCashReceived')}}</small></article>
          <article class="expense-summary"><label>{{t('expensesPeriod')}}</label><strong>{{money(m.outgoing,m.currency)}}</strong><small>{{t('externalSpending')}}</small></article>
          <article class="savings-summary" [class.negative]="m.net<0"><label>{{t('savingsPeriod')}}</label><strong>{{signedMoney(m.net,m.currency)}}</strong><small>{{t('incomingMinusOutgoing')}}</small></article>
          <article class="transfer-summary"><label>{{t('ownTransfers')}}</label><strong>{{money(m.transferIn+m.transferOut,m.currency)}}</strong><small>{{t('transfersExcluded')}}</small></article>
          <article class="activity-summary"><label>{{t('transactions')}}</label><strong>{{m.transactionCount|number}}</strong><small>{{t('allTwelveMonths')}}</small></article>
          <article class="rate-summary"><label>{{t('savingsRate')}}</label><strong>{{savingsRate(m.incoming,m.net)|number:'1.0-1'}}%</strong><small>{{t('annualTrend')}}</small></article>
        </section>
        <div class="year-analytics-grid">
          <article class="period-panel annual-trend-panel"><div class="panel-head"><div><p class="eyebrow">{{t('annualTrend')}}</p><h3>{{t('incomeVsExpenses')}}</h3></div><div class="flow-legend"><span><i class="fi"></i>{{t('incoming')}}</span><span><i class="fo"></i>{{t('outgoing')}}</span></div></div><div class="year-chart-scroll"><div class="year-chart"><button *ngFor="let month of yearMonths()" type="button" [class.selected]="activeYearMonth()?.period===month.period" (click)="selectedYearPeriod.set(month.period)"><div class="year-bars"><i class="income-bar" [style.height.%]="yearBarHeight(month.income)"></i><i class="expense-bar" [style.height.%]="yearBarHeight(month.outgoing)"></i></div><small>{{monthLabel(month.period)}}</small></button></div></div><div class="selection-summary month-selection" *ngIf="activeYearMonth() as month"><div><p class="eyebrow">{{monthFullLabel(month.period)}}</p><strong>{{signedMoney(month.net,m.currency)}}</strong><small>{{t('incoming')}} {{money(month.income,m.currency)}} · {{t('outgoing')}} {{money(month.outgoing,m.currency)}} · {{savingsRate(month.income,month.net)|number:'1.0-1'}}%</small></div><ds-button size="small" variant="secondary" (click)="openMonthLedger(month.period)">{{t('viewInLedger')}}</ds-button></div></article>

          <article class="period-panel monthly-performance-panel"><div class="panel-head"><div><p class="eyebrow">{{t('monthlyPerformance')}}</p><h3>{{t('allTwelveMonths')}}</h3></div></div><div class="month-card-rail"><button *ngFor="let month of yearMonths()" type="button" [class.selected]="activeYearMonth()?.period===month.period" (click)="selectedYearPeriod.set(month.period)"><span>{{monthLabel(month.period)}}</span><strong [class.negative]="month.net<0">{{compactMoney(month.net,m.currency,true)}}</strong><small>{{month.count}} {{t('transactions')}}</small></button></div></article>

          <article class="period-panel category-trend-panel"><div class="panel-head"><div><p class="eyebrow">{{t('categoryTrends')}}</p><h3>{{activeOverviewCategory()?categoryText(activeOverviewCategory()!.name):t('spendingByCategory')}}</h3></div></div><div class="category-chips"><button *ngFor="let c of overviewCategories()" type="button" [class.active]="activeOverviewCategory()?.name===c.name" (click)="selectedOverviewCategory.set(c.name)">{{categoryText(c.name)}}</button></div><div class="category-trend"><div *ngFor="let point of categoryTrend()"><span><i [style.height.%]="categoryTrendHeight(point.total)"></i></span><small>{{monthLabel(point.period)}}</small></div></div><div class="selection-summary category-selection" *ngIf="activeOverviewCategory() as c"><div><p class="eyebrow">{{categoryText(c.name)}}</p><strong>{{money(c.total,m.currency)}}</strong><small>{{c.count}} {{t('transactions')}} · {{t('largestPurchase')}} {{money(c.largest,m.currency)}}</small></div><ds-button size="small" variant="secondary" (click)="openCategoryLedger(c.name)">{{t('viewInLedger')}}</ds-button></div></article>

          <article class="period-panel year-pattern-panel"><div class="panel-head"><div><p class="eyebrow">{{t('yearPattern')}}</p><h3>{{t('categoryByMonth')}}</h3></div><small>{{t('selectCategoryHint')}}</small></div><div class="year-pattern"><div class="pattern-head"><span></span><b *ngFor="let month of yearMonths()">{{monthLabel(month.period)}}</b></div><button *ngFor="let row of yearCategoryPattern()" (click)="selectedOverviewCategory.set(row.name)"><strong>{{categoryText(row.name)}}</strong><i *ngFor="let value of row.values" [style.opacity]="patternOpacity(value,row.max)" [title]="money(value,m.currency)"></i></button></div></article>
        </div>

        <details class="period-details" open><summary><div><p class="eyebrow">{{t('annualDetails')}}</p><h3>{{t('incomeAndSpendingDetails')}}</h3></div><span>{{t('showDetails')}} ⌄</span></summary><div class="balance-columns"><section><div class="balance-column-head incoming-head"><h3>{{t('incomeByCategory')}}</h3><b>{{money(m.incoming,m.currency)}}</b></div><details class="balance-group" *ngFor="let g of directionGroups(m.groups,'Incoming')"><summary><div><b>{{categoryText(g.category)}}</b><small>{{categoryText(g.subcategory)}} · {{g.count}} {{t('transactions')}}</small></div><strong>{{money(g.total,m.currency)}}</strong><span>⌄</span></summary></details></section><section><div class="balance-column-head outgoing-head"><h3>{{t('spendingByCategory')}}</h3><b>{{money(m.outgoing,m.currency)}}</b></div><details class="balance-group" *ngFor="let g of directionGroups(m.groups,'Outgoing')"><summary><div><b>{{categoryText(g.category)}}</b><small>{{categoryText(g.subcategory)}} · {{g.count}} {{t('transactions')}}</small></div><strong>{{money(g.total,m.currency)}}</strong><span>⌄</span></summary></details></section></div></details>
        <ng-container *ngTemplateOutlet="transferBlock;context:{$implicit:m}"></ng-container>
      </section>

      <ng-template #transferBlock let-m><section class="transfer-section" *ngIf="transferGroups(m.groups).length"><div class="balance-column-head"><div><p class="eyebrow">{{t('internalMovements')}}</p><h3>{{t('transfersOwnAccounts')}}</h3><small>{{t('excludedIncomeExpenses')}}</small></div><div class="transfer-totals"><span>{{t('transferIn')}} <b>{{money(m.transferIn,m.currency)}}</b></span><span>{{t('transferOut')}} <b>{{money(m.transferOut,m.currency)}}</b></span></div></div><details class="balance-group" *ngFor="let g of transferGroups(m.groups)"><summary><div><b>{{directionText(g.direction)}}</b><small>{{g.count}} {{t('transactions')}}</small></div><strong>{{money(g.total,m.currency)}}</strong><span>⌄</span></summary><div class="period-transactions"><button *ngFor="let x of g.transactions" (click)="openDayLedger(x.bookingDate)"><span><b>{{x.counterpartyName||x.counterpartyIban||t('ownAccount')}}</b><small>{{x.bookingDate|date:'mediumDate'}} · {{x.accountName}}</small><em>{{x.remittanceInformation||'—'}}</em></span><strong>{{money(x.amount,x.currency)}}</strong></button></div></details></section></ng-template>
      <section *ngIf="tab()==='accounts' && analytics() as a" class="application-page settings-page accounts-page"><ds-page-header [eyebrow]="t('accountSettings')" [heading]="t('nameAccounts')" [description]="t('accountSettingsText')"></ds-page-header><div class="account-settings"><article *ngFor="let account of a.accounts"><div class="settings-account-head"><span class="bank-icon"><ds-icon name="wallet"></ds-icon></span><div><b>{{account.displayName||account.accountName||t('bankAccount')}}</b><small class="mono">{{account.iban||t('noIban')}} · {{account.currency}}</small></div><strong>{{money(account.balance,account.currency)}}</strong></div><ds-input #accountName [label]="t('customAccountName')" [value]="account.displayName||''" [maxlength]="100" [placeholder]="t('accountNamePlaceholder')"></ds-input><ds-select #accountType [label]="t('accountType')" [value]="''+account.accountKind" [options]="accountTypeOptions()"></ds-select><ds-button variant="primary" (click)="saveAccount(account,$any(accountName).value,$any(accountType).value)">{{t('saveAccount')}}</ds-button></article></div><ds-alert *ngIf="accountMessage()" tone="success">{{accountMessage()}}</ds-alert></section>
      <section *ngIf="tab()==='import'" class="application-page import-page"><ds-page-header [eyebrow]="t('dataIngestion')" [heading]="t('importStatements')" [description]="t('uploadText')"></ds-page-header><ds-panel class="upload-surface"><label class="drop" [class.busy]="busy()" [class.dragging]="dragging()" (dragover)="dragOver($event)" (dragleave)="dragLeave()" (drop)="dropFile($event)"><input type="file" accept=".xml,.zip,application/xml,application/zip" (change)="upload($event)"><ds-icon name="upload"></ds-icon><strong>{{busy()?'Uploading and creating import jobs…':'Choose or drop an XML / ZIP file'}}</strong><small>{{t('maximumZip')}}</small></label></ds-panel><ds-alert *ngIf="message()" tone="success">{{message()}}</ds-alert></section>
      <section *ngIf="tab()==='imports'" class="application-page data-page imports-page"><ds-page-header [eyebrow]="t('importHistory')" [heading]="t('statementImports')"><ds-button slot="actions" variant="primary" (click)="tab.set('import')"><ds-icon slot="prefix" name="plus"></ds-icon>{{t('newImport')}}</ds-button></ds-page-header><div class="data-surface table-wrap" role="region" tabindex="0" [attr.aria-label]="t('statementImports')"><table><thead><tr><th>{{t('file')}}</th><th>{{t('uploaded')}}</th><th>{{t('status')}}</th><th>{{t('transactions')}}</th><th>{{t('warnings')}}</th></tr></thead><tbody><tr *ngFor="let x of imports()"><td><b>{{x.originalFileName}}</b></td><td>{{x.createdAtUtc|date:'medium'}}</td><td><ds-badge [tone]="importStatusTone(x.status)">{{statusLabel(x.status)}}</ds-badge></td><td>{{x.transactionCount}}</td><td>{{x.warningCount}}</td></tr></tbody></table><ds-empty-state *ngIf="!imports().length" [heading]="t('noImports')"><ds-icon slot="icon" name="upload"></ds-icon><ds-button slot="actions" size="small" (click)="tab.set('import')">{{t('newImport')}}</ds-button></ds-empty-state></div></section>
      <section *ngIf="tab()==='ledger'" class="application-page data-page ledger-page">
        <ds-page-header [eyebrow]="t('accountLedger')" [heading]="t('ledgerHeadline')" [description]="t('ledgerText')"><div slot="actions" class="result-count"><b>{{ledgerTotal()|number}}</b><small>{{t('matchingTransactions')}}</small></div></ds-page-header>
        <ds-filter-bar class="ledger-filter-panel" [columns]="4">
          <label>{{t('account')}}<select [value]="ledgerAccountId()" (change)="selectLedgerAccount($event)"><option value="">{{t('allAccounts')}}</option><option *ngFor="let account of analytics()?.accounts||[]" [value]="account.id">{{account.displayName||account.accountName||t('bankAccount')}} · {{maskIban(account.iban)}}</option></select></label>
          <label>{{t('category')}}<select #filterCategory [value]="ledgerFilterCategory()" (change)="ledgerFilterCategory.set(filterCategory.value);ledgerFilterSubcategory.set('')"><option value="">{{t('allCategories')}}</option><option *ngFor="let group of categoryGroups()" [value]="group.name">{{categoryText(group.name)}}</option></select></label>
          <label>{{t('subcategory')}}<select #filterSubcategory [value]="ledgerFilterSubcategory()" [disabled]="!ledgerFilterCategory()"><option value="">{{t('allSubcategories')}}</option><option *ngFor="let sub of subcategories(ledgerFilterCategory())" [value]="sub">{{categoryText(sub)}}</option></select></label>
          <label>{{t('direction')}}<select #filterDirection [value]="ledgerDirection()"><option value="">{{t('incomingOutgoing')}}</option><option value="credit">{{t('incoming')}}</option><option value="debit">{{t('outgoing')}}</option></select></label>
          <label>{{t('from')}}<input type="date" #filterFrom [value]="ledgerFrom()"></label><label>{{t('to')}}<input type="date" #filterTo [value]="ledgerTo()"></label>
          <label>{{t('minimumAmount')}}<input type="number" min="0" step="0.01" #filterMin [value]="ledgerMin()" placeholder="0.00"></label><label>{{t('maximumAmount')}}<input type="number" min="0" step="0.01" #filterMax [value]="ledgerMax()" [placeholder]="t('maximumPlaceholder')"></label>
          <label class="filter-search">{{t('search')}}<input #ledgerQuery [value]="ledgerSearch()" [placeholder]="t('ledgerSearchPlaceholder')" (keyup.enter)="applyLedgerFilters(ledgerQuery.value,filterSubcategory.value,filterDirection.value,filterFrom.value,filterTo.value,filterMin.value,filterMax.value)"></label>
          <div slot="actions" class="filter-actions"><ds-button variant="secondary" (click)="clearLedgerFilters()">{{t('clear')}}</ds-button><ds-button variant="primary" (click)="applyLedgerFilters(ledgerQuery.value,filterSubcategory.value,filterDirection.value,filterFrom.value,filterTo.value,filterMin.value,filterMax.value)">{{t('applyFilters')}}</ds-button></div>
        </ds-filter-bar>
        <div class="ledger-explanation"><b>{{t('balanceAfterTransaction')}}</b><span>{{t('balanceExplanation')}}</span></div>
        <p class="category-feedback" *ngIf="categoryMessage()">{{categoryMessage()}}</p>
        <div class="data-surface table-wrap" role="region" tabindex="0" [attr.aria-label]="t('accountLedger')"><table class="ledger-balance-table"><thead><tr><th>{{t('bookingDate')}}</th><th>{{t('account')}}</th><th>{{t('description')}}</th><th>{{t('category')}}</th><th>{{t('reference')}}</th><th class="right">{{t('debit')}}</th><th class="right">{{t('credit')}}</th><th class="right">{{t('balanceAfter')}}</th><th></th></tr></thead><tbody>
          <ng-container *ngFor="let x of transactions()">
            <tr><td><b>{{x.bookingDate|date:'mediumDate'}}</b><small>{{t('value')}} {{x.valueDate?(x.valueDate|date:'mediumDate'):'—'}}</small></td><td class="mono">{{shortId(x.bankAccountId)}}</td><td><b>{{x.counterpartyName||t('unknownCounterparty')}}</b><small>{{x.remittanceInformation||x.additionalInformation||'—'}}</small></td><td><ds-badge tone="info">{{categoryText(x.category||'Miscellaneous')}}</ds-badge><small>{{categoryText(x.subcategory||'Other')}} · {{categorySourceLabel(x.categorySource)}}</small></td><td class="mono">{{x.accountServicerReference||x.entryReference||x.endToEndId||'—'}}</td><td class="right debit-value">{{x.creditDebitIndicator===1?money(x.amount,x.currency):'—'}}</td><td class="right credit-value">{{x.creditDebitIndicator===0?money(x.amount,x.currency):'—'}}</td><td class="right balance-value">{{money(x.balanceAfterTransaction,x.currency)}}</td><td><ds-button size="small" variant="secondary" (click)="openLedgerCategory(x)">{{selectedTransaction()?.id===x.id?t('close'):t('categorize')}}</ds-button></td></tr>
            <tr class="ledger-editor-row" *ngIf="selectedTransaction()?.id===x.id"><td colspan="9"><div class="category-editor"><div><p class="eyebrow">{{t('categoryLabel')}}</p><h4>{{x.counterpartyName||x.counterpartyIban||'Transaction'}}</h4><small>{{t('currentSource')}}: {{categorySourceLabel(x.categorySource)}}</small></div><label>{{t('category')}}<select #categorySelect [value]="x.category||'Miscellaneous'" (change)="categoryDraft.set(categorySelect.value)"><option *ngFor="let group of categoryGroups()" [value]="group.name">{{categoryText(group.name)}}</option></select></label><label>{{t('subcategory')}}<select #subcategorySelect><option *ngFor="let sub of subcategories(categoryDraft()||x.category||'Miscellaneous')" [value]="sub" [selected]="sub===x.subcategory">{{categoryText(sub)}}</option></select></label><ds-checkbox #applyIban [disabled]="!x.counterpartyIban">{{t('applyIban')}} {{x.counterpartyIban||'this IBAN'}}</ds-checkbox><ds-button variant="primary" (click)="saveCategory(x,categorySelect.value,subcategorySelect.value,$any(applyIban).checked)">{{t('saveCategory')}}</ds-button></div></td></tr>
          </ng-container>
        </tbody></table><div *ngIf="!transactions().length" class="empty">{{t('noLedgerMatches')}}</div></div>
      </section>      <section *ngIf="tab()==='transactions'" class="application-page data-page transactions-page ledger-page">
        <ds-page-header [eyebrow]="t('rawValuesLabel')" [heading]="t('rawHeadline')" [description]="t('rawText')"><div slot="actions" class="ledger-tools"><ds-search-input class="search" [placeholder]="t('rawSearchPlaceholder')" #q (keydown.enter)="loadTransactions($any(q).value)"></ds-search-input><ds-icon-button [label]="t('search')" (click)="loadTransactions($any(q).value)"><ds-icon name="search"></ds-icon></ds-icon-button></div></ds-page-header>
        <div class="data-surface table-wrap" role="region" tabindex="0" [attr.aria-label]="t('rawValuesLabel')"><table class="ledger-table"><thead><tr><th></th><th>{{t('bookingValue')}}</th><th>{{t('counterparty')}}</th><th>{{t('remittance')}}</th><th>{{t('status')}}</th><th>{{t('account')}}</th><th class="right">{{t('amount')}}</th></tr></thead><tbody>
          <ng-container *ngFor="let x of transactions()">
            <tr class="transaction-row" [class.selected]="selectedTransaction()?.id===x.id" (click)="toggleTransaction(x)"><td><button class="expand-btn" [attr.aria-label]="selectedTransaction()?.id===x.id?t('close'):t('showDetails')">{{selectedTransaction()?.id===x.id?'−':'+'}}</button></td><td><b>{{x.bookingDate|date:'mediumDate'}}</b><small>{{t('value')}} {{x.valueDate?(x.valueDate|date:'mediumDate'):'—'}}</small></td><td><b>{{x.counterpartyName||t('unknownCounterparty')}}</b><small class="mono">{{x.counterpartyIban||t('noIban')}}</small></td><td class="remittance-cell">{{x.remittanceInformation||x.additionalInformation||'—'}}</td><td><ds-badge [tone]="x.creditDebitIndicator===1?'danger':'success'">{{x.creditDebitIndicator===1?'Debit':'Credit'}}</ds-badge><small>{{x.status||t('noStatus')}}</small></td><td class="mono">{{shortId(x.bankAccountId)}}</td><td class="right amount" [class.negative]="x.creditDebitIndicator===1">{{x.creditDebitIndicator===1?'-':'+'}}{{money(x.amount,x.currency)}}</td></tr>
            <tr class="detail-row" *ngIf="selectedTransaction()?.id===x.id"><td colspan="7"><div class="transaction-detail">
              <div class="detail-title"><div><p class="eyebrow">{{t('transactionDetail')}}</p><h3>{{x.counterpartyName||t('unknownCounterparty')}}</h3></div><div class="detail-amount" [class.negative]="x.creditDebitIndicator===1">{{x.creditDebitIndicator===1?'-':'+'}}{{money(x.amount,x.currency)}}<small>{{x.creditDebitIndicator===1?'Debit':'Credit'}} · {{x.status||t('unknown')}}</small></div></div>
              <div class="detail-groups">
                <section><h4>{{t('coreTransaction')}}</h4><dl><div><dt>{{t('transactionId')}}</dt><dd class="mono">{{x.id}}</dd></div><div><dt>{{t('bookingDate')}}</dt><dd>{{x.bookingDate|date:'fullDate'}}</dd></div><div><dt>{{t('valueDate')}}</dt><dd>{{x.valueDate?(x.valueDate|date:'fullDate'):'—'}}</dd></div><div><dt>{{t('amount')}}</dt><dd>{{money(x.amount,x.currency)}}</dd></div><div><dt>{{t('currency')}}</dt><dd>{{x.currency}}</dd></div><div><dt>{{t('direction')}}</dt><dd>{{x.creditDebitIndicator===1?'Debit':'Credit'}}</dd></div><div><dt>{{t('status')}}</dt><dd>{{x.status||'—'}}</dd></div><div><dt>{{t('importedAt')}}</dt><dd>{{x.createdAtUtc|date:'medium'}}</dd></div></dl></section>
                <section><h4>{{t('counterparty')}}</h4><dl><div><dt>{{t('name')}}</dt><dd>{{x.counterpartyName||'—'}}</dd></div><div><dt>{{t('iban')}}</dt><dd class="mono">{{x.counterpartyIban||'—'}}</dd></div><div><dt>{{t('bic')}}</dt><dd class="mono">{{x.counterpartyBic||'—'}}</dd></div><div><dt>{{t('remittance')}}</dt><dd>{{x.remittanceInformation||'—'}}</dd></div><div><dt>{{t('additionalInformation')}}</dt><dd>{{x.additionalInformation||'—'}}</dd></div></dl></section>
                <section><h4>{{t('bankReferences')}}</h4><dl><div><dt>{{t('entryReference')}}</dt><dd class="mono">{{x.entryReference||'—'}}</dd></div><div><dt>{{t('servicerReference')}}</dt><dd class="mono">{{x.accountServicerReference||'—'}}</dd></div><div><dt>{{t('instructionId')}}</dt><dd class="mono">{{x.instructionId||'—'}}</dd></div><div><dt>{{t('endToEndId')}}</dt><dd class="mono">{{x.endToEndId||'—'}}</dd></div><div><dt>{{t('mandateId')}}</dt><dd class="mono">{{x.mandateId||'—'}}</dd></div><div><dt>{{t('bankTransactionId')}}</dt><dd class="mono">{{x.transactionId||'—'}}</dd></div><div><dt>{{t('externalTransactionId')}}</dt><dd class="mono">{{x.externalTransactionId||'—'}}</dd></div></dl></section>
                <section><h4>{{t('classificationOwnership')}}</h4><dl><div><dt>{{t('bankTransactionCode')}}</dt><dd class="mono">{{x.bankTransactionCode||'—'}}</dd></div><div><dt>{{t('proprietaryCode')}}</dt><dd class="mono">{{x.proprietaryTransactionCode||'—'}}</dd></div><div><dt>{{t('bankAccountId')}}</dt><dd class="mono">{{x.bankAccountId}}</dd></div><div><dt>{{t('statementId')}}</dt><dd class="mono">{{x.bankStatementId}}</dd></div><div><dt>{{t('fingerprint')}}</dt><dd class="mono wrap">{{x.fingerprint}}</dd></div></dl></section>
              </div>
              <details class="raw-detail"><summary>{{t('sourceMetadata')}}</summary><pre>{{prettyJson(x.rawEntryJson)}}</pre></details>
            </div></td></tr>
          </ng-container>
        </tbody></table><div *ngIf="!transactions().length" class="empty">{{t('noTransactionMatches')}}</div></div>
      </section>
      <section *ngIf="tab()==='users'" class="application-page data-page users-page"><ds-page-header [eyebrow]="t('administration')" [heading]="t('userManagement')" [description]="t('usersText')"></ds-page-header><ds-filter-bar class="user-create-bar" [columns]="4"><ds-input #newName [label]="t('name')" [placeholder]="t('name')"></ds-input><ds-input #newEmail label="Email" type="email" placeholder="Email"></ds-input><ds-input #newPassword label="Password" type="password" placeholder="Password (12+ characters)"></ds-input><ds-select #newRole [label]="t('role')" value="User" [options]="roleOptions()"></ds-select><ds-button slot="actions" variant="primary" (click)="createUser($any(newName).value,$any(newEmail).value,$any(newPassword).value,$any(newRole).value)">{{t('addUser')}}</ds-button></ds-filter-bar><ds-alert *ngIf="userMessage()" tone="success">{{userMessage()}}</ds-alert><div class="data-surface table-wrap" role="region" tabindex="0" [attr.aria-label]="t('userManagement')"><table><thead><tr><th>{{t('name')}}</th><th>Email</th><th>{{t('role')}}</th><th>{{t('status')}}</th><th></th></tr></thead><tbody><tr *ngFor="let user of users()"><td>{{user.displayName}}</td><td>{{user.email}}</td><td>{{user.role}}</td><td><ds-status-badge [tone]="user.isActive?'success':'neutral'">{{user.isActive?t('active'):t('inactive')}}</ds-status-badge></td><td><ds-button size="small" variant="ghost" (click)="toggleUser(user)">{{user.isActive?t('deactivate'):t('activate')}}</ds-button></td></tr></tbody></table></div></section>
  </main>
  <ds-detail-sidebar class="insight-sidebar" [open]="!!dashboardInsight()" [heading]="dashboardInsight()?.title||t('selectedInsight')" [closeLabel]="t('closeInsightDetails')" (ds-close)="closeDashboardInsight()">
    <div slot="summary" class="insight-sidebar-summary" *ngIf="dashboardInsight() as insight">
      <p class="eyebrow">{{t('selectedInsight')}}</p>
      <strong>{{insight.value}}</strong>
      <p>{{insight.detail}}</p>
      <span>{{insightTotal()|number}} {{t('matchingTransactions')}}</span>
    </div>
    <section class="insight-ledger" [attr.aria-label]="t('matchingLedgerEntries')">
      <div class="insight-ledger-head"><div><p class="eyebrow">{{t('ledger')}}</p><h3>{{t('matchingLedgerEntries')}}</h3></div><ds-badge tone="info">{{insightTransactions().length|number}}</ds-badge></div>
      <ds-loading-state *ngIf="insightLoading()" [label]="t('loadingLedgerEntries')"></ds-loading-state>
      <ds-alert *ngIf="insightError()" tone="danger" [heading]="insightError()"><ds-button size="small" variant="secondary" (click)="reloadDashboardInsight()">{{t('tryAgain')}}</ds-button></ds-alert>
      <div class="insight-ledger-list" *ngIf="insightTransactions().length">
        <article *ngFor="let x of insightTransactions()">
          <div class="insight-entry-main"><strong>{{x.counterpartyName||t('unknownCounterparty')}}</strong><span>{{x.remittanceInformation||x.additionalInformation||'—'}}</span><small>{{x.bookingDate|date:'mediumDate'}} · {{categoryText(x.category||'Miscellaneous')}}</small></div>
          <div class="insight-entry-amount" [class.negative]="x.creditDebitIndicator===1"><strong>{{x.creditDebitIndicator===1?'−':'+'}}{{money(x.amount,x.currency)}}</strong><small>{{t('balanceAfter')}} {{money(x.balanceAfterTransaction,x.currency)}}</small></div>
        </article>
      </div>
      <ds-empty-state *ngIf="!insightLoading() && !insightError() && !insightTransactions().length" [heading]="t('noInsightTransactions')"></ds-empty-state>
    </section>
    <ds-button slot="footer" variant="secondary" full-width *ngIf="dashboardInsight()?.ledger" (click)="openInsightLedger(dashboardInsight().ledger)">{{t('viewInLedger')}}</ds-button>
  </ds-detail-sidebar>
</ds-app-shell>`})
class App implements OnInit {
  readonly Math=Math;readonly Number=Number; private http=inject(HttpClient);readonly offline=inject(OfflineService); language=signal<Language>((localStorage.getItem('finance-language') as Language)||'en'); tab=signal('dashboard');mobileMenuOpen=signal(false);loading=signal(false);busy=signal(false);message=signal('');error=signal('');analytics=signal<Analytics|null>(null);imports=signal<ImportRow[]>([]);transactions=signal<Tx[]>([]);selectedTransaction=signal<Tx|null>(null);ledgerAccountId=signal('');ledgerFilterCategory=signal('');ledgerFilterSubcategory=signal('');ledgerDirection=signal('');ledgerFrom=signal('');ledgerTo=signal('');ledgerMin=signal('');ledgerMax=signal('');ledgerSearch=signal('');ledgerTotal=signal(0);accountMessage=signal('');categoryGroups=signal<CategoryGroup[]>([]);categoryDraft=signal('');categoryMessage=signal('');dashboardMonths=signal(1);dashboardRange=signal('months');dashboardInsight=signal<any|null>(null);insightTransactions=signal<Tx[]>([]);insightTotal=signal(0);insightLoading=signal(false);insightError=signal('');private insightRequest=0;monthlyOverview=signal<any|null>(null);overviewMonth=signal('');overviewYear=signal(new Date().getFullYear());selectedOverviewDay=signal('');selectedOverviewCategory=signal('');selectedYearPeriod=signal('');authUser=signal<any|null>(null);setupRequired=signal(false);authBusy=signal(false);authError=signal('');setupDisplayName=signal('');dragging=signal(false);sidebarCompact=signal(localStorage.getItem('finance-sidebar-compact')==='true');users=signal<any[]>([]);userMessage=signal('');
  title=computed(()=>this.t(({dashboard:'overview',transactions:'rawValues',ledger:'ledger',monthly:'monthlyOverview',year:'yearOverview',users:'userManagement',accounts:'accounts',imports:'imports',import:'uploadCamt'} as any)[this.tab()]));
  overviewDays=computed<PeriodDay[]>(()=>this.buildOverviewDays(this.monthlyOverview()));
  overviewCategories=computed<PeriodCategory[]>(()=>this.buildOverviewCategories(this.monthlyOverview()));
  yearMonths=computed<YearMonth[]>(()=>this.buildYearMonths(this.monthlyOverview()));
  activeOverviewDay=computed<PeriodDay|null>(()=>this.overviewDays().find(x=>x.date===this.selectedOverviewDay())||[...this.overviewDays()].reverse().find(x=>x.outgoing>0)||this.overviewDays()[0]||null);
  activeOverviewCategory=computed<PeriodCategory|null>(()=>this.overviewCategories().find(x=>x.name===this.selectedOverviewCategory())||this.overviewCategories()[0]||null);
  activeYearMonth=computed<YearMonth|null>(()=>this.yearMonths().find(x=>x.period===this.selectedYearPeriod())||[...this.yearMonths()].reverse().find(x=>x.count>0)||this.yearMonths()[0]||null);
  categoryTrend=computed(()=>this.buildCategoryTrend(this.monthlyOverview(),this.activeOverviewCategory()?.name));
  colors=['var(--ds-color-data-1)','var(--ds-color-data-2)','var(--ds-color-data-3)','var(--ds-color-data-4)','var(--ds-color-data-5)','var(--ds-color-data-6)','var(--ds-color-data-7)','var(--ds-color-data-8)'];
  languageOptions=[{label:'English',value:'en'},{label:'Nederlands',value:'nl'}];
  constructor(){let observed=0;effect(()=>{const version=this.offline.syncVersion();if(version>observed&&this.authUser())this.refresh();observed=version})}
  t(key:TranslationKey|string){return (UI[this.language()] as any)[key]||(UI.en as any)[key]||key}
  categoryText(value:string){return value.split(' / ').map(x=>categoryText(x,this.language())).join(' / ')}
  accountTypeOptions(){return [{label:this.t('currentAccount'),value:'0'},{label:this.t('savingsAccount'),value:'1'},{label:this.t('creditAccount'),value:'2'},{label:this.t('investmentAccount'),value:'3'},{label:this.t('other'),value:'4'}]}
  roleOptions(){return [{label:this.t('user'),value:'User'},{label:this.t('administrator'),value:'Administrator'}]}
  importStatusTone(status:number){return status===2?'success':status===4?'danger':status===0||status===1||status===3?'warning':'neutral'}
  directionText(value:string){return ({Incoming:this.t('incoming'),Outgoing:this.t('outgoing'),'Transfer in':this.t('transferIn'),'Transfer out':this.t('transferOut')} as any)[value]||value}
  setLanguage(event:Event){const value=((event as CustomEvent<{value:string}>).detail?.value||(event.target as HTMLSelectElement).value) as Language;this.language.set(value);localStorage.setItem('finance-language',value)} toggleSidebar(){this.sidebarCompact.update(x=>!x);localStorage.setItem('finance-sidebar-compact',String(this.sidebarCompact()))}  ngOnInit(){const token=localStorage.getItem('finance-token'),remembered=this.offline.rememberedUser<any>();if(token&&remembered){this.authUser.set(remembered);this.loadCategories();this.showDashboard()}this.http.get<any>('/api/v1/auth/setup-required').subscribe({next:x=>{this.setupRequired.set(x.setupRequired);if(!x.setupRequired&&token&&!this.authUser())this.restoreSession()},error:()=>{if(!this.authUser())this.authError.set(this.t('signInUnavailableOffline'))}});if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(error=>console.warn('Offline shell unavailable',error)));this.offline.flush()} isAdmin(){return this.authUser()?.role==='Administrator'} restoreSession(){this.http.get<any>('/api/v1/auth/me').subscribe({next:user=>{this.authUser.set(user);this.offline.rememberUser(user);this.loadCategories();this.showDashboard();this.primeOfflineData()},error:()=>{localStorage.removeItem('finance-token');this.offline.forgetUser();this.authUser.set(null)}})} login(email:string,password:string){this.authBusy.set(true);this.authError.set('');this.http.post<any>('/api/v1/auth/login',{email,password}).subscribe({next:r=>this.completeLogin(r),error:x=>{this.authBusy.set(false);this.authError.set(x.status===0?this.t('signInUnavailableOffline'):'Invalid email address or password.')}})} bootstrap(displayName:string,email:string,password:string){this.authBusy.set(true);this.authError.set('');this.http.post<any>('/api/v1/auth/bootstrap',{displayName,email,password}).subscribe({next:r=>this.completeLogin(r),error:x=>{this.authBusy.set(false);this.authError.set(x.error?.error||'Could not create administrator.')}})} completeLogin(r:any){localStorage.setItem('finance-token',r.token);this.offline.rememberUser(r.user);this.authUser.set(r.user);this.setupRequired.set(false);this.authBusy.set(false);this.offline.flush();this.loadCategories();this.showDashboard();this.primeOfflineData()} logout(){localStorage.removeItem('finance-token');this.offline.forgetUser();this.authUser.set(null);this.analytics.set(null);this.tab.set('dashboard')}
  primeOfflineData(){if(!navigator.onLine)return;const year=new Date().getFullYear();const reads=[this.http.get('/api/v1/analytics/overview',{params:{months:3}}),this.http.get('/api/v1/analytics/overview',{params:{months:12}}),this.http.get('/api/v1/analytics/overview',{params:{months:1,period:'this-year'}}),this.http.get('/api/v1/analytics/overview',{params:{months:1,period:'last-year'}}),this.http.get('/api/v1/analytics/month'),this.http.get('/api/v1/analytics/month',{params:{year}}),this.http.get('/api/v1/analytics/month',{params:{year:year-1}}),this.http.get('/api/v1/transactions',{params:{page:1,pageSize:200}}),this.http.get('/api/v1/transactions',{params:{page:1,pageSize:200,search:''}}),this.http.get('/api/v1/imports')];if(this.isAdmin())reads.push(this.http.get('/api/v1/admin/users'));for(const read of reads)read.subscribe({error:()=>{}})}
  showDashboard(){this.tab.set('dashboard');this.loading.set(true);this.error.set('');const params:any={months:this.dashboardMonths()};if(this.dashboardRange()!=='months')params.period=this.dashboardRange();this.http.get<Analytics>('/api/v1/analytics/overview',{params}).subscribe({next:x=>{this.analytics.set(x);this.loading.set(false)},error:x=>{this.error.set(x.error?.detail||this.t('loadDashboardError'));this.loading.set(false)}})}
  setDashboardPeriod(months:number){this.dashboardRange.set('months');this.dashboardMonths.set(months);this.closeDashboardInsight();this.showDashboard()} setDashboardCalendarPeriod(period:'this-year'|'last-year'){this.dashboardRange.set(period);this.closeDashboardInsight();this.showDashboard()}
  periodLabel(){return this.dashboardRange()==='this-year'?this.t('currentYear'):this.dashboardRange()==='last-year'?this.t('lastYear'):this.dashboardMonths()===1?this.t('thisMonth'):this.dashboardMonths()+' '+this.t('months')}
  inspectKpi(title:string,value:number,currency:string,detail:string,ledger:any){this.selectDashboardInsight({title,value:this.money(value,currency),detail,ledger})}
  inspectCount(title:string,value:number,detail:string,ledger:any){this.selectDashboardInsight({title,value:value.toLocaleString(this.language()==='nl'?'nl-NL':'en-NL'),detail,ledger})}
  inspectMonth(m:Point,currency:string){this.selectDashboardInsight({title:this.monthLabel(m.period!),value:this.signedMoney(m.net,currency),detail:this.t('incoming')+' '+this.money(m.income,currency)+' / '+this.t('outgoing')+' '+this.money(m.expenses,currency),ledger:{period:m.period}})}
  inspectNamed(item:Named,type:string,currency:string,ledger:any){this.selectDashboardInsight({title:this.categoryText(item.name),value:this.money(item.total,currency),detail:type+' / '+item.count+' '+this.t('transactions').toLowerCase(),ledger})}
  inspectDay(day:any,currency:string){this.selectDashboardInsight({title:new Date(day.date+'T00:00:00').toLocaleDateString(this.language()==='nl'?'nl-NL':'en-NL'),value:this.money(day.value,currency),detail:this.t('dailyExpenseActivity')+' / '+(day.count||0)+' '+this.t('transactions').toLowerCase(),ledger:{from:day.date,to:day.date,direction:'debit'}})}
  inspectAccount(account:any){this.selectDashboardInsight({title:account.displayName||account.accountName||this.t('account'),value:this.money(account.balance,account.currency),detail:this.maskIban(account.iban),ledger:{accountId:account.id}})}
  selectDashboardInsight(insight:any){this.dashboardInsight.set(insight);this.loadDashboardInsight(insight.ledger||{})}
  reloadDashboardInsight(){const insight=this.dashboardInsight();if(insight)this.loadDashboardInsight(insight.ledger||{})}
  closeDashboardInsight(){this.insightRequest++;this.dashboardInsight.set(null);this.insightTransactions.set([]);this.insightTotal.set(0);this.insightLoading.set(false);this.insightError.set('')}
  insightParams(filter:any,page=1){const params:any={page,pageSize:200};if(filter.accountId)params.accountId=filter.accountId;if(filter.category)params.category=filter.category;if(filter.search)params.search=filter.search;if(filter.direction)params.direction=filter.direction;if(filter.from)params.dateFrom=filter.from;if(filter.to)params.dateTo=filter.to;if(filter.period){params.dateFrom=filter.period+'-01';params.dateTo=this.localDate(new Date(Number(filter.period.slice(0,4)),Number(filter.period.slice(5,7)),0))}if(!filter.from&&!filter.period&&this.analytics()?.rangeStart)params.dateFrom=this.analytics()!.rangeStart;if(!filter.to&&!filter.period&&this.analytics()?.dataAsOf)params.dateTo=this.analytics()!.dataAsOf;return params}
  loadDashboardInsight(filter:any){const request=++this.insightRequest;this.insightTransactions.set([]);this.insightTotal.set(0);this.insightLoading.set(true);this.insightError.set('');this.loadDashboardInsightPage(filter,1,[],request)}
  loadDashboardInsightPage(filter:any,page:number,items:Tx[],request:number){this.http.get<any>('/api/v1/transactions',{params:this.insightParams(filter,page)}).subscribe({next:x=>{if(request!==this.insightRequest)return;const combined=[...items,...x.items];this.insightTotal.set(x.total);this.insightTransactions.set(combined);if(combined.length<x.total&&x.items.length){this.loadDashboardInsightPage(filter,page+1,combined,request);return}this.insightLoading.set(false)},error:()=>{if(request!==this.insightRequest)return;this.insightTransactions.set(items);this.insightError.set(this.t('loadInsightError'));this.insightLoading.set(false)}})}
  openInsightLedger(filter:any){this.closeDashboardInsight();this.resetLedgerFilters();if(filter.accountId)this.ledgerAccountId.set(filter.accountId);if(filter.category)this.ledgerFilterCategory.set(filter.category);if(filter.search)this.ledgerSearch.set(filter.search);if(filter.direction)this.ledgerDirection.set(filter.direction);if(filter.from)this.ledgerFrom.set(filter.from);if(filter.to)this.ledgerTo.set(filter.to);if(filter.period){this.ledgerFrom.set(filter.period+'-01');this.ledgerTo.set(this.localDate(new Date(Number(filter.period.slice(0,4)),Number(filter.period.slice(5,7)),0)))}if(!filter.from&&!filter.period&&this.analytics()?.rangeStart)this.ledgerFrom.set(this.analytics()!.rangeStart!);this.loadLedger()}
  refresh(){const current=this.tab();if(current==='dashboard')this.showDashboard();else if(current==='imports')this.loadImports();else if(current==='monthly')this.loadMonthlyOverview();else if(current==='year')this.loadYearOverview();else if(current==='ledger')this.loadLedger();else if(current==='accounts')this.showAccounts();else if(current==='users')this.loadUsers();else if(current==='transactions')this.loadTransactions()}
  money(value:number|null|undefined,currency='EUR'){if(value==null)return String.fromCharCode(8212);if(currency==='MIXED')return new Intl.NumberFormat(this.language()==='nl'?'nl-NL':'en-NL',{maximumFractionDigits:2}).format(value)+' mixed';return new Intl.NumberFormat(this.language()==='nl'?'nl-NL':'en-NL',{style:'currency',currency:currency||'EUR'}).format(value)}
  signedMoney(v:number,c:string){return (v>=0?'+':'')+this.money(v,c)}
  shortMax(rows:Point[]){return Math.max(1,...rows.flatMap(x=>[x.income,x.expenses]))}
  barHeight(v:number,rows:Point[]){return Math.max(2,v/this.shortMax(rows)*100)}
  monthLabel(v:string){return new Date(v+'-01T00:00:00').toLocaleDateString(this.language()==='nl'?'nl-NL':'en-NL',{month:'short'})}
  total(rows:Named[]){return rows.reduce((a,b)=>a+b.total,0)}
  color(i:number){return this.colors[i%this.colors.length]}
  donut(rows:Named[]){let p=0;const sum=this.total(rows)||1;return `conic-gradient(${rows.slice(0,8).map((x,i)=>{const s=p;p+=x.total/sum*100;return `${this.color(i)} ${s}% ${p}%`}).join(',')})`}
  linePoints(rows:{balance:number}[]){const vals=rows.map(x=>x.balance),min=Math.min(...vals),max=Math.max(...vals),range=max-min||1;return rows.map((x,i)=>`${i/(rows.length-1||1)*800},${205-(x.balance-min)/range*185}`).join(' ')}
  areaPoints(rows:{balance:number}[]){return `0,220 ${this.linePoints(rows)} 800,220`}
  heatDays(rows:{date:string;value:number;count?:number}[]){const map=new Map(rows.map(x=>[x.date,x]));const max=Math.max(1,...rows.map(x=>x.value));const end=new Date((this.analytics()?.dataAsOf||new Date().toISOString().slice(0,10))+'T00:00:00');const start=new Date((this.analytics()?.rangeStart||end.toISOString().slice(0,10))+'T00:00:00');const days=Math.max(1,Math.round((end.getTime()-start.getTime())/86400000)+1),out=[];for(let i=days-1;i>=0;i--){const d=new Date(end);d.setDate(end.getDate()-i);const key=this.localDate(d),item=map.get(key),value=item?.value||0;out.push({date:key,value,count:item?.count||0,level:value===0?0:Math.min(4,Math.ceil(value/max*4))})}return out}
  percentOf(v:number,rows:Named[]){return v/Math.max(1,...rows.map(x=>x.total))*100}
  initials(v:string){return v.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()}
  maskIban(v?:string){return v?v.slice(0,4)+' '+String.fromCharCode(8226).repeat(4)+' '+v.slice(-4):this.t('noIban')}
  upload(e:Event){const file=(e.target as HTMLInputElement).files?.[0];if(file)this.uploadFile(file)} dragOver(event:DragEvent){event.preventDefault();this.dragging.set(true)} dragLeave(){this.dragging.set(false)} dropFile(event:DragEvent){event.preventDefault();this.dragging.set(false);const file=event.dataTransfer?.files?.[0];if(file)this.uploadFile(file)} uploadFile(file:File){this.busy.set(true);this.message.set('');const form=new FormData();form.append('file',file);this.http.post<any>('/api/v1/imports',form).subscribe({next:r=>{this.busy.set(false);this.message.set(r.queued?this.t('uploadQueued'):r.count.toLocaleString()+' '+this.t('newImport'));if(!r.queued)setTimeout(()=>this.loadImports(),1200)},error:x=>{this.busy.set(false);this.message.set(x.error?.error||x.error?.detail||this.t('uploadFailed')+' ('+(x.status||'network')+')')}})}
  loadCategories(){this.http.get<CategoryGroup[]>('/api/v1/categories').subscribe(x=>this.categoryGroups.set(x))}
  subcategories(category:string){return this.categoryGroups().find(x=>x.name===category)?.subcategories||['Other']}
  categorySourceLabel(source?:number){return source===2?this.t('manual'):source===1?this.t('ibanRule'):this.t('automaticRecognition')}
  saveCategory(transaction:Tx,category:string,subcategory:string,applyToIban:boolean){this.http.put<any>('/api/v1/transactions/'+transaction.id+'/category',{category,subcategory,applyToIban}).subscribe({next:r=>{if(applyToIban&&transaction.counterpartyIban){for(const item of this.transactions())if(item.counterpartyIban===transaction.counterpartyIban){item.category=category;item.subcategory=subcategory;item.categorySource=1}}else{transaction.category=category;transaction.subcategory=subcategory;transaction.categorySource=2}this.transactions.set([...this.transactions()]);this.categoryMessage.set(r.queued?this.t('savedOffline'):r.affected+' '+this.t('categorySaved'))},error:x=>this.categoryMessage.set(x.error?.error||this.t('categorySaveError'))})}
  showAccounts(){this.tab.set('accounts');this.accountMessage.set('');if(this.analytics())return;this.loading.set(true);this.error.set('');this.http.get<Analytics>('/api/v1/analytics/overview',{params:{months:this.dashboardMonths()}}).subscribe({next:x=>{this.analytics.set(x);this.loading.set(false)},error:()=>{this.error.set(this.t('loadDashboardError'));this.loading.set(false)}})}
  saveAccount(account:any,displayName:string,accountKind:string){this.http.put<any>('/api/v1/accounts/'+account.id,{displayName,accountKind:Number(accountKind)}).subscribe({next:updated=>{account.displayName=updated.displayName;account.accountKind=updated.accountKind;this.analytics.set({...this.analytics()!});this.accountMessage.set(updated.queued?this.t('savedOffline'):this.t('accountSaved'))},error:x=>this.accountMessage.set(x.error?.error||this.t('accountSaveError'))})}
  flowHeight(value:number,rows:Point[]){const max=Math.max(1,...rows.flatMap(x=>[x.externalIncoming||0,x.externalOutgoing||0,x.transferIn||0,x.transferOut||0]));return value===0?0:Math.max(3,value/max*100)}
  buildOverviewDays(overview:any){if(!overview)return[];const days=new Map<string,PeriodDay>();for(const group of overview.groups||[]){if(group.direction.startsWith('Transfer'))continue;for(const transaction of group.transactions||[]){const date=String(transaction.bookingDate).slice(0,10);if(!days.has(date))days.set(date,{date,income:0,outgoing:0,net:0,count:0,transactions:[]});const day=days.get(date)!;if(group.direction==='Incoming')day.income+=transaction.amount;else if(group.direction==='Outgoing')day.outgoing+=transaction.amount;day.net=day.income-day.outgoing;day.count++;day.transactions.push(transaction)}}return [...days.values()].sort((a,b)=>a.date.localeCompare(b.date))}
  buildOverviewCategories(overview:any){if(!overview)return[];const categories=new Map<string,PeriodCategory>();for(const group of overview.groups||[]){if(group.direction!=='Outgoing')continue;const current:PeriodCategory=categories.get(group.category)||{name:group.category,total:0,count:0,largest:0,transactions:[]};current.total+=group.total;current.count+=group.count;current.transactions.push(...group.transactions);current.largest=Math.max(current.largest,...group.transactions.map((x:any)=>x.amount));categories.set(group.category,current)}return [...categories.values()].sort((a,b)=>b.total-a.total)}
  buildYearMonths(overview:any){if(!overview)return[];const year=Number(overview.year||this.overviewYear());const months:YearMonth[]=Array.from({length:12},(_,index)=>({period:`${year}-${String(index+1).padStart(2,'0')}`,income:0,outgoing:0,net:0,transferIn:0,transferOut:0,count:0}));for(const group of overview.groups||[]){for(const transaction of group.transactions||[]){const month=months[Number(String(transaction.bookingDate).slice(5,7))-1];if(!month)continue;if(group.direction==='Incoming')month.income+=transaction.amount;else if(group.direction==='Outgoing')month.outgoing+=transaction.amount;else if(group.direction==='Transfer in')month.transferIn+=transaction.amount;else if(group.direction==='Transfer out')month.transferOut+=transaction.amount;month.count++}}for(const month of months)month.net=month.income-month.outgoing;return months}
  buildCategoryTrend(overview:any,category?:string){const year=Number(overview?.year||this.overviewYear());const points=Array.from({length:12},(_,index)=>({period:`${year}-${String(index+1).padStart(2,'0')}`,total:0}));if(!overview||!category)return points;for(const group of overview.groups||[]){if(group.direction!=='Outgoing'||group.category!==category)continue;for(const transaction of group.transactions||[]){const point=points[Number(String(transaction.bookingDate).slice(5,7))-1];if(point)point.total+=transaction.amount}}return points}
  calendarLeadingDays(){const [year,month]=this.overviewMonth().split('-').map(Number);if(!year||!month)return[];const mondayFirst=(new Date(year,month-1,1).getDay()+6)%7;return Array.from({length:mondayFirst})}
  calendarDays(){const [year,month]=this.overviewMonth().split('-').map(Number);if(!year||!month)return[];const map=new Map(this.overviewDays().map(x=>[x.date,x]));const count=new Date(year,month,0).getDate();const max=Math.max(1,...this.overviewDays().map(x=>x.outgoing));return Array.from({length:count},(_,index)=>{const day=index+1,date=`${year}-${String(month).padStart(2,'0')}-${String(day).padStart(2,'0')}`,value=map.get(date)?.outgoing||0;return{day,date,outgoing:value,level:value===0?0:Math.min(4,Math.ceil(value/max*4))}})}
  weekdayLabels(){const locale=this.language()==='nl'?'nl-NL':'en-NL';const monday=new Date(2026,0,5);return Array.from({length:7},(_,i)=>new Date(monday.getFullYear(),monday.getMonth(),monday.getDate()+i).toLocaleDateString(locale,{weekday:'narrow'}))}
  monthAverageDaily(){const days=this.calendarDays().length||1;return (this.monthlyOverview()?.outgoing||0)/days}
  monthLargestDay(){return Math.max(0,...this.overviewDays().map(x=>x.outgoing))}
  monthElapsedPercent(){const [year,month]=this.overviewMonth().split('-').map(Number),days=this.calendarDays().length||1,now=new Date();if(year===now.getFullYear()&&month===now.getMonth()+1)return Math.min(100,now.getDate()/days*100);return 100}
  dailyBarHeight(value:number){return value===0?2:Math.max(5,value/Math.max(1,...this.overviewDays().map(x=>x.outgoing))*100)}
  categoryPercent(value:number){return value/Math.max(1,this.monthlyOverview()?.outgoing||0)*100}
  yearBarHeight(value:number){return value===0?2:Math.max(4,value/Math.max(1,...this.yearMonths().flatMap(x=>[x.income,x.outgoing]))*100)}
  categoryTrendHeight(value:number){return value===0?2:Math.max(4,value/Math.max(1,...this.categoryTrend().map(x=>x.total))*100)}
  yearCategoryPattern(){return this.overviewCategories().slice(0,8).map(category=>{const values=this.buildCategoryTrend(this.monthlyOverview(),category.name).map(x=>x.total);return{name:category.name,values,max:Math.max(1,...values)}})}
  patternOpacity(value:number,max:number){return value===0?.08:.18+value/max*.82}
  savingsRate(income:number,savings:number){return income===0?0:savings/income*100}
  compactMoney(value:number,currency='EUR',signed=false){const prefix=signed&&value>0?'+':'';if(currency==='MIXED')return prefix+new Intl.NumberFormat(this.language()==='nl'?'nl-NL':'en-NL',{notation:'compact',maximumFractionDigits:1}).format(value);return prefix+new Intl.NumberFormat(this.language()==='nl'?'nl-NL':'en-NL',{style:'currency',currency:currency||'EUR',notation:'compact',maximumFractionDigits:1}).format(value)}
  shiftMonth(offset:number){const [year,month]=this.overviewMonth().split('-').map(Number),next=new Date(year,month-1+offset,1);this.loadMonthlyOverview(`${next.getFullYear()}-${String(next.getMonth()+1).padStart(2,'0')}`)}
  shiftYear(offset:number){this.loadYearOverview(this.overviewYear()+offset)}
  openDayLedger(date:string){this.resetLedgerFilters();this.ledgerFrom.set(String(date).slice(0,10));this.ledgerTo.set(String(date).slice(0,10));this.loadLedger()}
  openCategoryLedger(category:string){this.resetLedgerFilters();this.ledgerFilterCategory.set(category);this.ledgerFrom.set(this.monthlyOverview()?.from||'');this.ledgerTo.set(this.monthlyOverview()?.to||'');this.loadLedger()}
  openMonthLedger(period:string){this.goPeriod(period)}
  loadMonthlyOverview(month?:string){this.tab.set('monthly');this.loading.set(true);this.error.set('');const params:any={};if(month||this.overviewMonth())params.month=month||this.overviewMonth();this.http.get<any>('/api/v1/analytics/month',{params}).subscribe({next:x=>{this.monthlyOverview.set(x);this.overviewMonth.set(x.month);this.selectedOverviewDay.set('');this.selectedOverviewCategory.set('');this.loading.set(false)},error:()=>{this.error.set(this.t('loadMonthlyError'));this.loading.set(false)}})}  changeOverviewMonth(event:Event){this.loadMonthlyOverview((event.target as HTMLInputElement).value)} loadYearOverview(year?:number){this.tab.set('year');this.loading.set(true);this.error.set('');const selected=year||this.overviewYear();this.http.get<any>('/api/v1/analytics/month',{params:{year:selected}}).subscribe({next:x=>{this.monthlyOverview.set(x);this.overviewYear.set(x.year);this.selectedOverviewCategory.set('');this.selectedYearPeriod.set('');this.loading.set(false)},error:()=>{this.error.set(this.t('loadMonthlyError'));this.loading.set(false)}})} changeOverviewYear(event:Event){this.loadYearOverview(Number((event.target as HTMLInputElement).value))} loadUsers(){this.tab.set('users');this.http.get<any[]>('/api/v1/admin/users').subscribe({next:x=>this.users.set(x),error:()=>this.userMessage.set('Could not load users.')})} createUser(displayName:string,email:string,password:string,role:string){this.http.post<any>('/api/v1/admin/users',{displayName,email,password,role}).subscribe({next:r=>{this.userMessage.set(r.queued?this.t('savedOffline'):'User created.');if(r.queued)this.users.update(items=>[...items,{id:'offline-'+Date.now(),displayName,email,role,isActive:true}]);else this.loadUsers()},error:x=>this.userMessage.set(x.error?.error||'Could not create user.')})} toggleUser(user:any){this.http.put<any>('/api/v1/admin/users/'+user.id,{isActive:!user.isActive}).subscribe({next:r=>{if(r.queued){user.isActive=!user.isActive;this.users.set([...this.users()]);this.userMessage.set(this.t('savedOffline'))}else this.loadUsers()},error:x=>this.userMessage.set(x.error?.error||'Could not update user.')})}
  availabilityText(value:string){const keys:any={'Credit utilization requires credit-limit data':'creditUtilizationUnavailable','Days until next paycheck requires a payroll schedule':'paycheckUnavailable','Payment method is not consistently supplied by CAMT':'paymentMethodUnavailable','Forecasts require more history and an explicit forecasting model':'forecastUnavailable'};return keys[value]?this.t(keys[value]):value}
  directionGroups(groups:any[],direction:string){return groups.filter(x=>x.direction===direction)}
  transferGroups(groups:any[]){return groups.filter(x=>x.direction==='Transfer in'||x.direction==='Transfer out')}
  monthFullLabel(month:string){return new Date(month+'-01T00:00:00').toLocaleDateString(this.language()==='nl'?'nl-NL':'en',{month:'long',year:'numeric'})}  loadImports(){this.tab.set('imports');this.loading.set(true);this.error.set('');this.http.get<ImportRow[]>('/api/v1/imports').subscribe({next:x=>{this.imports.set(x);this.loading.set(false);if(this.offline.online()&&x.some(i=>i.status===0||i.status===1))setTimeout(()=>{if(this.tab()==='imports')this.loadImports()},2500)},error:()=>{this.error.set(this.t('loadImportsError'));this.loading.set(false)}})}
  goLedger(){this.resetLedgerFilters();this.loadLedger()}
  goAccount(accountId:string){this.resetLedgerFilters();this.ledgerAccountId.set(accountId);this.loadLedger()}
  goCategory(category:string){this.resetLedgerFilters();this.ledgerFilterCategory.set(category);this.loadLedger()}
  goSearch(search:string,direction=''){this.resetLedgerFilters();this.ledgerSearch.set(search);this.ledgerDirection.set(direction);this.loadLedger()}
  goDay(date:string){this.resetLedgerFilters();this.ledgerFrom.set(date);this.ledgerTo.set(date);this.loadLedger()}
  goPeriod(period:string,direction=''){const start=period+'-01';const end=this.localDate(new Date(Number(period.slice(0,4)),Number(period.slice(5,7)),0));this.resetLedgerFilters();this.ledgerFrom.set(start);this.ledgerTo.set(end);this.ledgerDirection.set(direction);this.loadLedger()}
  goRecentMonths(months:number,direction=''){const now=new Date();const start=new Date(now.getFullYear(),now.getMonth()-months+1,1);this.resetLedgerFilters();this.ledgerFrom.set(this.localDate(start));this.ledgerTo.set(this.localDate(now));this.ledgerDirection.set(direction);this.loadLedger()}
  localDate(date:Date){const y=date.getFullYear(),m=String(date.getMonth()+1).padStart(2,'0'),d=String(date.getDate()).padStart(2,'0');return `${y}-${m}-${d}`}
  resetLedgerFilters(){this.ledgerAccountId.set('');this.ledgerFilterCategory.set('');this.ledgerFilterSubcategory.set('');this.ledgerDirection.set('');this.ledgerFrom.set('');this.ledgerTo.set('');this.ledgerMin.set('');this.ledgerMax.set('');this.ledgerSearch.set('')}  loadLedger(){this.tab.set('ledger');this.loading.set(true);this.error.set('');this.selectedTransaction.set(null);const params:any={page:1,pageSize:200};const values:any={accountId:this.ledgerAccountId(),category:this.ledgerFilterCategory(),subcategory:this.ledgerFilterSubcategory(),direction:this.ledgerDirection(),dateFrom:this.ledgerFrom(),dateTo:this.ledgerTo(),minAmount:this.ledgerMin(),maxAmount:this.ledgerMax(),search:this.ledgerSearch()};for(const key of Object.keys(values))if(values[key]!==''&&values[key]!=null)params[key]=values[key];this.http.get<any>('/api/v1/transactions',{params}).subscribe({next:x=>{this.transactions.set(x.items);this.ledgerTotal.set(x.total);this.loading.set(false)},error:()=>{this.error.set(this.t('loadLedgerError'));this.loading.set(false)}})}
  applyLedgerFilters(search:string,subcategory:string,direction:string,from:string,to:string,min:string,max:string){this.ledgerSearch.set(search);this.ledgerFilterSubcategory.set(subcategory);this.ledgerDirection.set(direction);this.ledgerFrom.set(from);this.ledgerTo.set(to);this.ledgerMin.set(min);this.ledgerMax.set(max);this.loadLedger()}
  clearLedgerFilters(){this.ledgerFilterCategory.set('');this.ledgerFilterSubcategory.set('');this.ledgerDirection.set('');this.ledgerFrom.set('');this.ledgerTo.set('');this.ledgerMin.set('');this.ledgerMax.set('');this.ledgerSearch.set('');this.loadLedger()}
  openLedgerCategory(x:Tx){this.selectedTransaction.set(this.selectedTransaction()?.id===x.id?null:x);this.categoryDraft.set(x.category||'Miscellaneous');this.categoryMessage.set('')}
  selectLedgerAccount(event:Event){this.ledgerAccountId.set((event.target as HTMLSelectElement).value);this.loadLedger()}
  loadTransactions(search=''){this.tab.set('transactions');this.loading.set(true);this.error.set('');this.http.get<any>('/api/v1/transactions',{params:{page:1,pageSize:200,search}}).subscribe({next:x=>{this.transactions.set(x.items);this.loading.set(false)},error:()=>{this.error.set(this.t('loadTransactionsError'));this.loading.set(false)}})}
  toggleTransaction(x:Tx){this.selectedTransaction.set(this.selectedTransaction()?.id===x.id?null:x);this.categoryDraft.set(x.category||'Miscellaneous')}
  shortId(v:string){return v?v.slice(0,8)+'…':'—'}
  prettyJson(v:string){try{return JSON.stringify(JSON.parse(v),null,2)}catch{return v||this.t('noSourceMetadata')}}
  statusLabel(v:number){return [this.t('pending'),this.t('processing'),this.t('completed'),this.t('completedWarnings'),this.t('failed'),this.t('duplicate')][v]||this.t('unknown')}
}
const authInterceptor:HttpInterceptorFn=(req,next)=>{const token=localStorage.getItem('finance-token');return token&&req.url.startsWith('/api/v1/')&&!req.url.includes('/auth/login')&&!req.url.includes('/auth/bootstrap')?next(req.clone({setHeaders:{Authorization:'Bearer '+token}})):next(req)};
bootstrapApplication(App,{providers:[provideHttpClient(withInterceptors([authInterceptor,offlineInterceptor]))]}).catch(console.error);
