import {Component, computed, inject, OnInit, signal} from '@angular/core';
import {bootstrapApplication} from '@angular/platform-browser';
import {HttpClient, provideHttpClient} from '@angular/common/http';
import {CommonModule} from '@angular/common';
import {UI, categoryText, type Language, type TranslationKey} from './i18n';

type CategoryGroup={name:string;subcategories:string[]};
type ImportRow={id:string;originalFileName:string;status:number;createdAtUtc:string;transactionCount:number;warningCount:number};
type Tx={id:string;bankStatementId:string;bankAccountId:string;externalTransactionId?:string;entryReference?:string;accountServicerReference?:string;instructionId?:string;endToEndId?:string;mandateId?:string;transactionId?:string;bookingDate:string;valueDate?:string;amount:number;currency:string;creditDebitIndicator:number;status?:string;bankTransactionCode?:string;proprietaryTransactionCode?:string;counterpartyName?:string;counterpartyIban?:string;counterpartyBic?:string;remittanceInformation?:string;additionalInformation?:string;fingerprint:string;rawEntryJson:string;createdAtUtc:string;balanceAfterTransaction:number;category?:string;subcategory?:string;categorySource?:number};
type Point={period?:string;date?:string;label?:string;income:number;expenses:number;net:number;transferIn?:number;transferOut?:number;externalIncoming?:number;externalOutgoing?:number};
type Named={name:string;total:number;count:number;average?:number;percent?:number};
type Analytics={generatedAtUtc:string;dataAsOf?:string;selectedMonths?:number;rangeStart?:string;currency:string;kpis:any;monthly:Point[];daily:Point[];weeks:Point[];runningBalance:{date:string;balance:number}[];categories:Named[];merchants:Named[];incomeSources:Named[];heatmap:{date:string;value:number;count:number}[];accounts:any[];unavailable:string[]};

@Component({selector:'app-root',standalone:true,imports:[CommonModule],template:`
<div class="shell">
  <aside>
    <div class="brand"><span class="brandmark">F</span><span>Finance<br><b>Inzicht</b></span></div>
    <nav>
      <button [class.active]="tab()==='dashboard'" (click)="showDashboard()"><span>⌂</span> {{t('overview')}}</button>
      <button [class.active]="tab()==='ledger'" (click)="loadLedger()"><span>≋</span> {{t('ledger')}}</button>
<button [class.active]="tab()==='monthly'" (click)="loadMonthlyOverview()"><span>▤</span> {{t('monthlyOverview')}}</button>
            <button [class.active]="tab()==='transactions'" (click)="loadTransactions()"><span>↕</span> {{t('rawValues')}}</button>
      <button [class.active]="tab()==='accounts'" (click)="showAccounts()"><span>▦</span> {{t('accounts')}}</button>
      <button [class.active]="tab()==='imports'" (click)="loadImports()"><span>⇩</span> {{t('imports')}}</button>
      <button [class.active]="tab()==='import'" (click)="tab.set('import')"><span>＋</span> {{t('uploadCamt')}}</button>
    </nav>
    <div class="side-note"><span class="pulse"></span><div><b>{{t('systemOnline')}}</b><small>{{t('workerActive')}}</small></div></div>
  </aside>

  <div class="workspace">
    <header><div><small>{{t('personalFinance')}}</small><h1>{{title()}}</h1></div><div class="header-actions"><label class="language-switch"><span>{{t('language')}}</span><select [value]="language()" (change)="setLanguage($event)"><option value="en">English</option><option value="nl">Nederlands</option></select></label><button class="icon-btn" (click)="refresh()">↻</button><button class="upload-btn" (click)="tab.set('import')">＋ {{t('importFiles')}}</button></div></header>
    <main>
      <div *ngIf="loading()" class="loading"><span></span><p>{{t('calculating')}}</p></div>
      <div *ngIf="error()" class="alert error">{{error()}} <button (click)="refresh()">{{t('tryAgain')}}</button></div>

      <ng-container *ngIf="tab()==='dashboard' && analytics() as a">
        <section class="hero-row"><div><p class="eyebrow">{{t('financialOverview')}}</p><h2>{{t('dashboardHeadline')}}</h2><p class="muted">Based on {{a.kpis.transactionCount | number}} imported transactions · Updated {{a.generatedAtUtc | date:'shortTime'}}</p></div><div class="period"><button [class.active]="dashboardMonths()===1" (click)="setDashboardPeriod(1)">{{t('thisMonth')}}</button><button [class.active]="dashboardMonths()===3" (click)="setDashboardPeriod(3)">3 {{t('months')}}</button><button [class.active]="dashboardMonths()===12" (click)="setDashboardPeriod(12)">12 {{t('months')}}</button></div></section>
        <section class="dashboard-insight" *ngIf="dashboardInsight() as insight"><div><p class="eyebrow">{{t('selectedInsight')}}</p><h3>{{insight.title}}</h3><p>{{insight.detail}}</p></div><strong>{{insight.value}}</strong><div class="insight-actions"><button class="secondary-btn" (click)="dashboardInsight.set(null)">{{t('close')}}</button><button class="upload-btn" *ngIf="insight.ledger" (click)="openInsightLedger(insight.ledger)">{{t('viewInLedger')}}</button></div></section>

        <section class="kpi-grid primary">
          <article class="kpi balance dashboard-link" role="button" tabindex="0" (click)="inspectKpi(t('currentBalance'),a.kpis.currentBalance,a.currency,t('balanceAcrossAccounts'),{})" (keydown.enter)="inspectKpi(t('currentBalance'),a.kpis.currentBalance,a.currency,t('balanceAcrossAccounts'),{})"><div class="kpi-icon">€</div><label>{{t('currentBalance')}}</label><strong>{{money(a.kpis.currentBalance,a.currency)}}</strong><small>Across {{a.kpis.activeAccounts}} active account{{a.kpis.activeAccounts===1?'':'s'}}</small></article>
          <article class="kpi dashboard-link" role="button" tabindex="0" (click)="inspectKpi(t('income'),a.kpis.incomeThisMonth,a.currency,periodLabel()+' '+t('cashInflow'),{direction:'credit'})" (keydown.enter)="inspectKpi(t('income'),a.kpis.incomeThisMonth,a.currency,periodLabel()+' '+t('cashInflow'),{direction:'credit'})"><div class="kpi-icon green">↗</div><label>Income · {{periodLabel()}}</label><strong>{{money(a.kpis.incomeThisMonth,a.currency)}}</strong><small class="positive">{{t('cashInflow')}}</small></article>
          <article class="kpi dashboard-link" role="button" tabindex="0" (click)="inspectKpi(t('expensesPeriod'),a.kpis.expensesThisMonth,a.currency,periodLabel()+' '+t('cashOutflow'),{direction:'debit'})" (keydown.enter)="inspectKpi(t('expensesPeriod'),a.kpis.expensesThisMonth,a.currency,periodLabel()+' '+t('cashOutflow'),{direction:'debit'})"><div class="kpi-icon coral">↘</div><label>Expenses · {{periodLabel()}}</label><strong>{{money(a.kpis.expensesThisMonth,a.currency)}}</strong><small>Avg {{money(a.kpis.averageDailySpending,a.currency)}} / day</small></article>
          <article class="kpi dashboard-link" role="button" tabindex="0" (click)="inspectKpi(t('savingsPeriod'),a.kpis.savingsThisMonth,a.currency,periodLabel()+' '+t('netSavings'),{})" (keydown.enter)="inspectKpi(t('savingsPeriod'),a.kpis.savingsThisMonth,a.currency,periodLabel()+' '+t('netSavings'),{})"><div class="kpi-icon blue">◇</div><label>Savings · {{periodLabel()}}</label><strong [class.negative]="a.kpis.savingsThisMonth<0">{{money(a.kpis.savingsThisMonth,a.currency)}}</strong><small>{{a.kpis.savingsRate | number:'1.0-1'}}% savings rate</small></article>
        </section>

        <section class="kpi-grid secondary">
          <article class="mini"><label>{{t('netWorth')}}</label><b>{{money(a.kpis.netWorth,a.currency)}}</b><span>Total assets {{money(a.kpis.totalAssets,a.currency)}}</span></article>
          <article class="mini"><label>{{t('cashFlow')}}</label><b [class.negative]="a.kpis.cashFlow<0">{{signedMoney(a.kpis.cashFlow,a.currency)}}</b><span>{{a.kpis.positiveCashFlowStreak}} positive month streak</span></article>
          <article class="mini"><label>{{t('monthlyBurnRate')}}</label><b>{{money(a.kpis.averageMonthlySpending,a.currency)}}</b><span>{{money(a.kpis.burnRate,a.currency)}} per day</span></article>
          <article class="mini"><label>{{t('cashRunway')}}</label><b>{{a.kpis.daysOfCashRemaining==null?'—':(a.kpis.daysOfCashRemaining|number:'1.0-0')+' '+t('days')}}</b><span>{{a.kpis.emergencyFundMonths==null?t('notEnoughHistory'):(a.kpis.emergencyFundMonths|number:'1.1-1')+' '+t('emergencyMonths')}}</span></article>
          <article class="mini dashboard-link" role="button" tabindex="0" (click)="inspectCount(t('transactions'),a.kpis.transactionCount,periodLabel()+' '+t('activity'),{})" (keydown.enter)="inspectCount(t('transactions'),a.kpis.transactionCount,periodLabel()+' '+t('activity'),{})"><label>{{t('transactions')}}</label><b>{{a.kpis.transactionCount | number}}</b><span>{{a.kpis.purchaseCount | number}} outgoing payments</span></article>
          <article class="mini"><label>{{t('averageTransaction')}}</label><b>{{money(a.kpis.averageTransaction,a.currency)}}</b><span>Median expense {{money(a.kpis.medianExpense,a.currency)}}</span></article>
        </section>

        <section class="chart-grid">
          <article class="panel wide"><div class="panel-head"><div><p class="eyebrow">{{t('cashFlowChart')}}</p><h3>{{t('incomeVsExpenses')}}</h3></div><div class="legend"><i class="income"></i>Income <i class="expense"></i>{{t('expensesPeriod')}}</div></div>
            <div *ngIf="!a.monthly.length" class="empty">{{t('importMoreHistory')}}</div>
            <div class="bar-chart" *ngIf="a.monthly.length"><div class="y-guide"><span>{{money(shortMax(a.monthly),a.currency)}}</span><span>{{money(shortMax(a.monthly)/2,a.currency)}}</span><span>0</span></div><div class="bars"><div class="bar-group dashboard-link" *ngFor="let m of a.monthly" role="button" tabindex="0" (click)="inspectMonth(m,a.currency)" (keydown.enter)="inspectMonth(m,a.currency)"><div class="bar-pair"><i class="income-bar" [style.height.%]="barHeight(m.income,a.monthly)"></i><i class="expense-bar" [style.height.%]="barHeight(m.expenses,a.monthly)"></i></div><small>{{monthLabel(m.period!)}}</small></div></div></div>
          </article>
          <article class="panel"><div class="panel-head"><div><p class="eyebrow">{{t('spending')}}</p><h3>{{t('byCategory')}}</h3></div></div><div *ngIf="!a.categories.length" class="empty">{{t('noExpense')}}</div><div class="donut-wrap" *ngIf="a.categories.length"><div class="donut" [style.background]="donut(a.categories)"><div><b>{{money(total(a.categories),a.currency)}}</b><small>{{t('totalSpent')}}</small></div></div><div class="category-list"><div *ngFor="let c of a.categories.slice(0,6);let i=index" class="dashboard-list-link" role="button" tabindex="0" (click)="inspectNamed(c,t('spendingCategory'),a.currency,{category:c.name})" (keydown.enter)="inspectNamed(c,t('spendingCategory'),a.currency,{category:c.name})"><i [style.background]="color(i)"></i><span>{{categoryText(c.name)}}</span><b>{{c.percent|number:'1.0-0'}}%</b></div></div></div></article>

          <article class="panel wide"><div class="panel-head"><div><p class="eyebrow">{{t('balanceTrend')}}</p><h3>{{t('runningBalance')}}</h3></div><b>{{money(a.kpis.currentBalance,a.currency)}}</b></div><div class="line-wrap" *ngIf="a.runningBalance.length"><svg viewBox="0 0 800 220" preserveAspectRatio="none"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#156b5b" stop-opacity=".25"/><stop offset="1" stop-color="#156b5b" stop-opacity="0"/></linearGradient></defs><polygon [attr.points]="areaPoints(a.runningBalance)" fill="url(#area)"/><polyline [attr.points]="linePoints(a.runningBalance)" fill="none" stroke="#156b5b" stroke-width="3" vector-effect="non-scaling-stroke"/></svg><div class="axis"><span>{{a.runningBalance[0].date|date:'MMM d'}}</span><span>{{a.runningBalance[a.runningBalance.length-1].date|date:'MMM d'}}</span></div></div><div *ngIf="!a.runningBalance.length" class="empty">{{t('noBalanceHistory')}}</div></article>
          <article class="panel"><div class="panel-head"><div><p class="eyebrow">{{t('income')}}</p><h3>{{t('topSources')}}</h3></div></div><div class="rank-list"><div *ngFor="let s of a.incomeSources;let i=index" class="dashboard-list-link" role="button" tabindex="0" (click)="inspectNamed(s,t('income'),a.currency,{search:s.name,direction:'credit'})" (keydown.enter)="inspectNamed(s,t('income'),a.currency,{search:s.name,direction:'credit'})"><span class="rank">{{i+1}}</span><div><b>{{s.name}}</b><small>{{s.count}} {{s.count===1?t('payment'):t('payments')}}</small></div><strong>{{money(s.total,a.currency)}}</strong></div><div *ngIf="!a.incomeSources.length" class="empty">{{t('noIncomeSources')}}</div></div></article>

          <article class="panel full"><div class="panel-head"><div><p class="eyebrow">{{t('monthlyMoneyFlowLabel')}}</p><h3>{{t('monthlyMoneyFlow')}}</h3><p class="muted">{{t('transferExplanation')}}</p></div><div class="flow-legend"><span><i class="fi"></i>{{t('incoming')}}</span><span><i class="fo"></i>{{t('outgoing')}}</span><span><i class="fti"></i>{{t('transferIn')}}</span><span><i class="fto"></i>{{t('transferOut')}}</span></div></div><div class="monthly-flow" *ngIf="a.monthly.length"><div class="flow-month dashboard-link" *ngFor="let m of a.monthly" role="button" tabindex="0" (click)="inspectMonth(m,a.currency)" (keydown.enter)="inspectMonth(m,a.currency)"><div class="flow-bars"><i class="flow-in" [style.height.%]="flowHeight(m.externalIncoming||0,a.monthly)"></i><i class="flow-out" [style.height.%]="flowHeight(m.externalOutgoing||0,a.monthly)"></i><i class="flow-transfer-in" [style.height.%]="flowHeight(m.transferIn||0,a.monthly)"></i><i class="flow-transfer-out" [style.height.%]="flowHeight(m.transferOut||0,a.monthly)"></i></div><b [class.negative]="m.net<0">{{signedMoney(m.net,a.currency)}}</b><small>{{monthLabel(m.period!)}}</small></div></div><div *ngIf="!a.monthly.length" class="empty">{{t('noMonthlyFlows')}}</div></article>
          <article class="panel full"><div class="panel-head"><div><p class="eyebrow">{{t('spendingPatterns')}}</p><h3>{{t('dailyExpenseActivity')}}</h3></div><div class="heat-legend">{{t('less')}} <i></i><i></i><i></i><i></i><i></i> {{t('more')}}</div></div><div class="heatmap"><div *ngFor="let day of heatDays(a.heatmap)" [class]="'heat h'+day.level" role="button" tabindex="0" (click)="inspectDay(day,a.currency)" (keydown.enter)="inspectDay(day,a.currency)" [title]="day.date+': '+money(day.value,a.currency)"></div></div><div class="heat-months"><span>{{analytics()?.rangeStart|date:'mediumDate'}}</span><span>{{analytics()?.dataAsOf|date:'mediumDate'}}</span></div></article>

          <article class="panel"><div class="panel-head"><div><p class="eyebrow">{{t('expenseMetrics')}}</p><h3>{{t('purchaseProfile')}}</h3></div></div><dl class="metrics"><div><dt>{{t('largestPurchase')}}</dt><dd>{{money(a.kpis.largestPurchase,a.currency)}}</dd></div><div><dt>{{t('smallestPurchase')}}</dt><dd>{{money(a.kpis.smallestPurchase,a.currency)}}</dd></div><div><dt>{{t('averagePurchase')}}</dt><dd>{{money(a.kpis.averageMonthlySpending/Math.max(1,a.kpis.purchaseCount),a.currency)}}</dd></div><div><dt>{{t('negativeFlowMonths')}}</dt><dd>{{a.kpis.negativeCashFlowMonths}}</dd></div></dl></article>
          <article class="panel wide"><div class="panel-head"><div><p class="eyebrow">{{t('merchants')}}</p><h3>{{t('whereMoneyGoes')}}</h3></div></div><div class="merchant-list"><div *ngFor="let m of a.merchants;let i=index" class="dashboard-list-link" role="button" tabindex="0" (click)="inspectNamed(m,t('merchants'),a.currency,{search:m.name,direction:'debit'})" (keydown.enter)="inspectNamed(m,t('merchants'),a.currency,{search:m.name,direction:'debit'})"><div class="merchant-avatar">{{initials(m.name)}}</div><div class="merchant-name"><b>{{m.name}}</b><small>{{m.count}} {{t('transactions')}} · {{t('averageShort')}} {{money(m.average,a.currency)}}</small></div><div class="merchant-bar"><i [style.width.%]="percentOf(m.total,a.merchants)"></i></div><strong>{{money(m.total,a.currency)}}</strong></div><div *ngIf="!a.merchants.length" class="empty">{{t('noMerchantData')}}</div></div></article>

          <article class="panel full"><div class="panel-head"><div><p class="eyebrow">{{t('accounts')}}</p><h3>{{t('accountOverview')}}</h3></div><button class="text-btn" (click)="goLedger()">{{t('viewLedger')}} →</button></div><div class="account-grid"><div class="account dashboard-link" *ngFor="let account of a.accounts" role="button" tabindex="0" (click)="inspectAccount(account)" (keydown.enter)="inspectAccount(account)"><span class="bank-icon">▦</span><div><b>{{account.displayName||account.accountName||t('bankAccount')}}</b><small>{{maskIban(account.iban)}}</small></div><strong>{{money(account.balance,account.currency)}}</strong></div></div></article>
        </section>
        <section class="data-note"><div>ⓘ</div><div><b>{{t('dataAvailability')}}</b><p>{{t('dataAvailabilityText')}}</p><span *ngFor="let note of a.unavailable">{{availabilityText(note)}}</span></div></section>
      </ng-container>

      <section *ngIf="tab()==='monthly' && monthlyOverview() as m" class="page-card monthly-page">
        <div class="panel-head"><div><p class="eyebrow">{{t('monthlyBalanceSheet')}}</p><h2>{{monthFullLabel(m.month)}}</h2><p class="muted">{{t('monthlyText')}}</p></div><label class="month-picker">{{t('selectMonth')}}<input type="month" [value]="overviewMonth()" (change)="changeOverviewMonth($event)"></label></div>
        <section class="month-summary"><article class="opening"><label>{{t('incoming')}}</label><strong>{{money(m.incoming,m.currency)}}</strong><small>{{t('externalCashReceived')}}</small></article><article class="closing"><label>{{t('outgoing')}}</label><strong>{{money(m.outgoing,m.currency)}}</strong><small>{{t('externalSpending')}}</small></article><article [class.negative]="m.net<0"><label>{{t('netResult')}}</label><strong>{{signedMoney(m.net,m.currency)}}</strong><small>{{t('incomingMinusOutgoing')}}</small></article><article><label>{{t('ownTransfers')}}</label><strong>{{money(m.transferIn,m.currency)}} in</strong><small>{{money(m.transferOut,m.currency)}} out · {{t('transfersExcluded')}}</small></article></section>
        <div class="month-meta"><b>{{m.transactionCount|number}} {{t('transactions')}}</b><span>{{m.from|date:'mediumDate'}} – {{m.to|date:'mediumDate'}}</span></div>
        <div class="balance-columns">
          <section><div class="balance-column-head incoming-head"><div><p class="eyebrow">{{t('incoming')}}</p><h3>{{t('incomeByCategory')}}</h3></div><b>{{money(m.incoming,m.currency)}}</b></div><ng-container *ngFor="let g of directionGroups(m.groups,'Incoming')"><details class="balance-group"><summary><div><b>{{categoryText(g.category)}}</b><small>{{g.subcategory}} · {{g.count}} {{g.count===1?t('transactionId'):t('transactions')}}</small></div><strong>{{money(g.total,m.currency)}}</strong><span>⌄</span></summary><div class="group-details"><table><thead><tr><th>{{t('date')}}</th><th>{{t('account')}}</th><th>{{t('counterparty')}}</th><th>{{t('descriptionReference')}}</th><th class="right">{{t('amount')}}</th></tr></thead><tbody><tr *ngFor="let x of g.transactions"><td>{{x.bookingDate|date:'mediumDate'}}</td><td><b>{{x.accountName}}</b><small class="mono">{{shortId(x.bankAccountId)}}</small></td><td><b>{{x.counterpartyName||'Unknown'}}</b><small class="mono">{{x.counterpartyIban||t('noIban')}}</small></td><td>{{x.remittanceInformation||x.additionalInformation||'—'}}<small class="mono">{{x.accountServicerReference||x.entryReference||x.endToEndId||'—'}}</small></td><td class="right credit-value">{{money(x.amount,x.currency)}}</td></tr></tbody></table></div></details><div class="empty compact-empty" *ngIf="!directionGroups(m.groups,'Incoming').length">{{t('noIncomingMonth')}}</div></ng-container></section>
          <section><div class="balance-column-head outgoing-head"><div><p class="eyebrow">{{t('outgoing')}}</p><h3>{{t('spendingByCategory')}}</h3></div><b>{{money(m.outgoing,m.currency)}}</b></div><ng-container *ngFor="let g of directionGroups(m.groups,'Outgoing')"><details class="balance-group"><summary><div><b>{{categoryText(g.category)}}</b><small>{{g.subcategory}} · {{g.count}} {{g.count===1?t('transactionId'):t('transactions')}}</small></div><strong>{{money(g.total,m.currency)}}</strong><span>⌄</span></summary><div class="group-details"><table><thead><tr><th>{{t('date')}}</th><th>{{t('account')}}</th><th>{{t('counterparty')}}</th><th>{{t('descriptionReference')}}</th><th class="right">{{t('amount')}}</th></tr></thead><tbody><tr *ngFor="let x of g.transactions"><td>{{x.bookingDate|date:'mediumDate'}}</td><td><b>{{x.accountName}}</b><small class="mono">{{shortId(x.bankAccountId)}}</small></td><td><b>{{x.counterpartyName||'Unknown'}}</b><small class="mono">{{x.counterpartyIban||t('noIban')}}</small></td><td>{{x.remittanceInformation||x.additionalInformation||'—'}}<small class="mono">{{x.accountServicerReference||x.entryReference||x.endToEndId||'—'}}</small></td><td class="right debit-value">{{money(x.amount,x.currency)}}</td></tr></tbody></table></div></details><div class="empty compact-empty" *ngIf="!directionGroups(m.groups,'Outgoing').length">{{t('noOutgoingMonth')}}</div></ng-container></section>
        </div>
        <section class="transfer-section" *ngIf="directionGroups(m.groups,'Transfer in').length||directionGroups(m.groups,'Transfer out').length"><div class="balance-column-head"><div><p class="eyebrow">{{t('internalMovements')}}</p><h3>{{t('transfersOwnAccounts')}}</h3></div><small>{{t('excludedIncomeExpenses')}}</small></div><details class="balance-group" *ngFor="let g of transferGroups(m.groups)"><summary><div><b>{{directionText(g.direction)}}</b><small>{{g.subcategory}} · {{g.count}} {{g.count===1?t('transactionId'):t('transactions')}}</small></div><strong>{{money(g.total,m.currency)}}</strong><span>⌄</span></summary><div class="group-details"><table><tbody><tr *ngFor="let x of g.transactions"><td>{{x.bookingDate|date:'mediumDate'}}</td><td>{{x.accountName}}</td><td>{{x.counterpartyName||x.counterpartyIban||t('ownAccount')}}</td><td>{{x.remittanceInformation||'—'}}</td><td class="right">{{money(x.amount,x.currency)}}</td></tr></tbody></table></div></details></section>
      </section>
      <section *ngIf="tab()==='accounts' && analytics() as a" class="page-card"><div class="panel-head"><div><p class="eyebrow">{{t('accountSettings')}}</p><h2>{{t('nameAccounts')}}</h2><p class="muted">{{t('accountSettingsText')}}</p></div></div><div class="account-settings"><article *ngFor="let account of a.accounts"><div class="settings-account-head"><span class="bank-icon">▦</span><div><b>{{account.displayName||account.accountName||t('bankAccount')}}</b><small class="mono">{{account.iban||t('noIban')}} · {{account.currency}}</small></div><strong>{{money(account.balance,account.currency)}}</strong></div><label>{{t('customAccountName')}}<input #accountName [value]="account.displayName||''" maxlength="100" [placeholder]="t('accountNamePlaceholder')"></label><label>{{t('accountType')}}<select #accountType [value]="account.accountKind"><option value="0">{{t('currentAccount')}}</option><option value="1">{{t('savingsAccount')}}</option><option value="2">{{t('creditAccount')}}</option><option value="3">{{t('investmentAccount')}}</option><option value="4">{{t('other')}}</option></select></label><button class="upload-btn" (click)="saveAccount(account,accountName.value,accountType.value)">{{t('saveAccount')}}</button></article></div><div *ngIf="accountMessage()" class="alert">{{accountMessage()}}</div></section>
      <section *ngIf="tab()==='import'" class="page-card import-page"><p class="eyebrow">{{t('dataIngestion')}}</p><h2>{{t('importStatements')}}</h2><p class="muted">{{t('uploadText')}}</p><label class="drop" [class.busy]="busy()"><input type="file" accept=".xml,.zip,application/xml,application/zip" (change)="upload($event)"><span>⇧</span><strong>{{busy()?'Uploading and creating import jobs…':'Choose or drop an XML / ZIP file'}}</strong><small>{{t('maximumZip')}}</small></label><div *ngIf="message()" class="alert">{{message()}}</div></section>
      <section *ngIf="tab()==='imports'" class="page-card"><div class="panel-head"><div><p class="eyebrow">{{t('importHistory')}}</p><h2>{{t('statementImports')}}</h2></div><button class="upload-btn" (click)="tab.set('import')">＋ {{t('newImport')}}</button></div><div class="table-wrap"><table><thead><tr><th>{{t('file')}}</th><th>{{t('uploaded')}}</th><th>{{t('status')}}</th><th>{{t('transactions')}}</th><th>{{t('warnings')}}</th></tr></thead><tbody><tr *ngFor="let x of imports()"><td><b>{{x.originalFileName}}</b></td><td>{{x.createdAtUtc|date:'medium'}}</td><td><span [class]="'status s'+x.status">{{statusLabel(x.status)}}</span></td><td>{{x.transactionCount}}</td><td>{{x.warningCount}}</td></tr></tbody></table><div *ngIf="!imports().length" class="empty">{{t('noImports')}}</div></div></section>
      <section *ngIf="tab()==='ledger'" class="page-card ledger-page">
        <div class="panel-head"><div><p class="eyebrow">{{t('accountLedger')}}</p><h2>{{t('ledgerHeadline')}}</h2><p class="muted">{{t('ledgerText')}}</p></div><div class="result-count"><b>{{ledgerTotal()|number}}</b><small>{{t('matchingTransactions')}}</small></div></div>
        <div class="ledger-filter-panel">
          <label>{{t('account')}}<select [value]="ledgerAccountId()" (change)="selectLedgerAccount($event)"><option value="">{{t('allAccounts')}}</option><option *ngFor="let account of analytics()?.accounts||[]" [value]="account.id">{{account.displayName||account.accountName||t('bankAccount')}} · {{maskIban(account.iban)}}</option></select></label>
          <label>{{t('category')}}<select #filterCategory [value]="ledgerFilterCategory()" (change)="ledgerFilterCategory.set(filterCategory.value);ledgerFilterSubcategory.set('')"><option value="">{{t('allCategories')}}</option><option *ngFor="let group of categoryGroups()" [value]="group.name">{{categoryText(group.name)}}</option></select></label>
          <label>{{t('subcategory')}}<select #filterSubcategory [value]="ledgerFilterSubcategory()" [disabled]="!ledgerFilterCategory()"><option value="">{{t('allSubcategories')}}</option><option *ngFor="let sub of subcategories(ledgerFilterCategory())" [value]="sub">{{categoryText(sub)}}</option></select></label>
          <label>{{t('direction')}}<select #filterDirection [value]="ledgerDirection()"><option value="">{{t('incomingOutgoing')}}</option><option value="credit">{{t('incoming')}}</option><option value="debit">{{t('outgoing')}}</option></select></label>
          <label>{{t('from')}}<input type="date" #filterFrom [value]="ledgerFrom()"></label><label>{{t('to')}}<input type="date" #filterTo [value]="ledgerTo()"></label>
          <label>{{t('minimumAmount')}}<input type="number" min="0" step="0.01" #filterMin [value]="ledgerMin()" placeholder="0.00"></label><label>{{t('maximumAmount')}}<input type="number" min="0" step="0.01" #filterMax [value]="ledgerMax()" [placeholder]="t('maximumPlaceholder')"></label>
          <label class="filter-search">{{t('search')}}<input #ledgerQuery [value]="ledgerSearch()" [placeholder]="t('ledgerSearchPlaceholder')" (keyup.enter)="applyLedgerFilters(ledgerQuery.value,filterSubcategory.value,filterDirection.value,filterFrom.value,filterTo.value,filterMin.value,filterMax.value)"></label>
          <div class="filter-actions"><button class="secondary-btn" (click)="clearLedgerFilters()">{{t('clear')}}</button><button class="upload-btn" (click)="applyLedgerFilters(ledgerQuery.value,filterSubcategory.value,filterDirection.value,filterFrom.value,filterTo.value,filterMin.value,filterMax.value)">{{t('applyFilters')}}</button></div>
        </div>
        <div class="ledger-explanation"><b>{{t('balanceAfterTransaction')}}</b><span>{{t('balanceExplanation')}}</span></div>
        <p class="category-feedback" *ngIf="categoryMessage()">{{categoryMessage()}}</p>
        <div class="table-wrap"><table class="ledger-balance-table"><thead><tr><th>{{t('bookingDate')}}</th><th>{{t('account')}}</th><th>{{t('description')}}</th><th>{{t('category')}}</th><th>{{t('reference')}}</th><th class="right">{{t('debit')}}</th><th class="right">{{t('credit')}}</th><th class="right">{{t('balanceAfter')}}</th><th></th></tr></thead><tbody>
          <ng-container *ngFor="let x of transactions()">
            <tr><td><b>{{x.bookingDate|date:'mediumDate'}}</b><small>{{t('value')}} {{x.valueDate?(x.valueDate|date:'mediumDate'):'—'}}</small></td><td class="mono">{{shortId(x.bankAccountId)}}</td><td><b>{{x.counterpartyName||t('unknownCounterparty')}}</b><small>{{x.remittanceInformation||x.additionalInformation||'—'}}</small></td><td><span class="category-pill">{{categoryText(x.category||'Miscellaneous')}}</span><small>{{categoryText(x.subcategory||'Other')}} · {{categorySourceLabel(x.categorySource)}}</small></td><td class="mono">{{x.accountServicerReference||x.entryReference||x.endToEndId||'—'}}</td><td class="right debit-value">{{x.creditDebitIndicator===1?money(x.amount,x.currency):'—'}}</td><td class="right credit-value">{{x.creditDebitIndicator===0?money(x.amount,x.currency):'—'}}</td><td class="right balance-value">{{money(x.balanceAfterTransaction,x.currency)}}</td><td><button class="secondary-btn compact" (click)="openLedgerCategory(x)">{{selectedTransaction()?.id===x.id?t('close'):t('categorize')}}</button></td></tr>
            <tr class="ledger-editor-row" *ngIf="selectedTransaction()?.id===x.id"><td colspan="9"><div class="category-editor"><div><p class="eyebrow">{{t('categoryLabel')}}</p><h4>{{x.counterpartyName||x.counterpartyIban||'Transaction'}}</h4><small>{{t('currentSource')}}: {{categorySourceLabel(x.categorySource)}}</small></div><label>{{t('category')}}<select #categorySelect [value]="x.category||'Miscellaneous'" (change)="categoryDraft.set(categorySelect.value)"><option *ngFor="let group of categoryGroups()" [value]="group.name">{{categoryText(group.name)}}</option></select></label><label>{{t('subcategory')}}<select #subcategorySelect><option *ngFor="let sub of subcategories(categoryDraft()||x.category||'Miscellaneous')" [value]="sub" [selected]="sub===x.subcategory">{{categoryText(sub)}}</option></select></label><label class="iban-rule"><input type="checkbox" #applyIban [disabled]="!x.counterpartyIban"> {{t('applyIban')}} {{x.counterpartyIban||'this IBAN'}}</label><button class="upload-btn" (click)="saveCategory(x,categorySelect.value,subcategorySelect.value,applyIban.checked)">{{t('saveCategory')}}</button></div></td></tr>
          </ng-container>
        </tbody></table><div *ngIf="!transactions().length" class="empty">{{t('noLedgerMatches')}}</div></div>
      </section>      <section *ngIf="tab()==='transactions'" class="page-card ledger-page">
        <div class="panel-head ledger-head"><div><p class="eyebrow">{{t('rawValuesLabel')}}</p><h2>{{t('rawHeadline')}}</h2><p class="muted">{{t('rawText')}}</p></div><div class="ledger-tools"><input class="search" [placeholder]="t('rawSearchPlaceholder')" #q (keyup.enter)="loadTransactions(q.value)"><button class="icon-btn" (click)="loadTransactions(q.value)">⌕</button></div></div>
        <div class="table-wrap"><table class="ledger-table"><thead><tr><th></th><th>{{t('bookingValue')}}</th><th>{{t('counterparty')}}</th><th>{{t('remittance')}}</th><th>{{t('status')}}</th><th>{{t('account')}}</th><th class="right">{{t('amount')}}</th></tr></thead><tbody>
          <ng-container *ngFor="let x of transactions()">
            <tr class="transaction-row" [class.selected]="selectedTransaction()?.id===x.id" (click)="toggleTransaction(x)"><td><button class="expand-btn">{{selectedTransaction()?.id===x.id?'−':'+'}}</button></td><td><b>{{x.bookingDate|date:'mediumDate'}}</b><small>{{t('value')}} {{x.valueDate?(x.valueDate|date:'mediumDate'):'—'}}</small></td><td><b>{{x.counterpartyName||t('unknownCounterparty')}}</b><small class="mono">{{x.counterpartyIban||t('noIban')}}</small></td><td class="remittance-cell">{{x.remittanceInformation||x.additionalInformation||'—'}}</td><td><span [class]="x.creditDebitIndicator===1?'pill debit-pill':'pill credit-pill'">{{x.creditDebitIndicator===1?'Debit':'Credit'}}</span><small>{{x.status||t('noStatus')}}</small></td><td class="mono">{{shortId(x.bankAccountId)}}</td><td class="right amount" [class.negative]="x.creditDebitIndicator===1">{{x.creditDebitIndicator===1?'-':'+'}}{{money(x.amount,x.currency)}}</td></tr>
            <tr class="detail-row" *ngIf="selectedTransaction()?.id===x.id"><td colspan="7"><div class="transaction-detail">
              <div class="detail-title"><div><p class="eyebrow">{{t('transactionDetail')}}</p><h3>{{x.counterpartyName||t('unknownCounterparty')}}</h3></div><div class="detail-amount" [class.negative]="x.creditDebitIndicator===1">{{x.creditDebitIndicator===1?'-':'+'}}{{money(x.amount,x.currency)}}<small>{{x.creditDebitIndicator===1?'Debit':'Credit'}} · {{x.status||t('unknown')}}</small></div></div>
              <div class="detail-groups">
                <section><h4>{{t('coreTransaction')}}</h4><dl><div><dt>{{t('transactionId')}}</dt><dd class="mono">{{x.id}}</dd></div><div><dt>{{t('bookingDate')}}</dt><dd>{{x.bookingDate|date:'fullDate'}}</dd></div><div><dt>{{t('valueDate')}}</dt><dd>{{x.valueDate?(x.valueDate|date:'fullDate'):'—'}}</dd></div><div><dt>{{t('amount')}}</dt><dd>{{money(x.amount,x.currency)}}</dd></div><div><dt>{{t('currency')}}</dt><dd>{{x.currency}}</dd></div><div><dt>{{t('direction')}}</dt><dd>{{x.creditDebitIndicator===1?'Debit':'Credit'}}</dd></div><div><dt>{{t('status')}}</dt><dd>{{x.status||'—'}}</dd></div><div><dt>{{t('importedAt')}}</dt><dd>{{x.createdAtUtc|date:'medium'}}</dd></div></dl></section>
                <section><h4>{{t('counterparty')}}</h4><dl><div><dt>{{t('name')}}</dt><dd>{{x.counterpartyName||'—'}}</dd></div><div><dt>{{t('iban')}}</dt><dd class="mono">{{x.counterpartyIban||'—'}}</dd></div><div><dt>{{t('bic')}}</dt><dd class="mono">{{x.counterpartyBic||'—'}}</dd></div><div><dt>{{t('remittance')}}</dt><dd>{{x.remittanceInformation||'—'}}</dd></div><div><dt>{{t('additionalInformation')}}</dt><dd>{{x.additionalInformation||'—'}}</dd></div></dl></section>
                <section><h4>{{t('bankReferences')}}</h4><dl><div><dt>{{t('entryReference')}}</dt><dd class="mono">{{x.entryReference||'—'}}</dd></div><div><dt>{{t('servicerReference')}}</dt><dd class="mono">{{x.accountServicerReference||'—'}}</dd></div><div><dt>{{t('instructionId')}}</dt><dd class="mono">{{x.instructionId||'—'}}</dd></div><div><dt>{{t('endToEndId')}}</dt><dd class="mono">{{x.endToEndId||'—'}}</dd></div><div><dt>{{t('mandateId')}}</dt><dd class="mono">{{x.mandateId||'—'}}</dd></div><div><dt>{{t('bankTransactionId')}}</dt><dd class="mono">{{x.transactionId||'—'}}</dd></div><div><dt>{{t('externalTransactionId')}}</dt><dd class="mono">{{x.externalTransactionId||'—'}}</dd></div></dl></section>
                <section><h4>{{t('classificationOwnership')}}</h4><dl><div><dt>{{t('bankTransactionCode')}}</dt><dd class="mono">{{x.bankTransactionCode||'—'}}</dd></div><div><dt>{{t('proprietaryCode')}}</dt><dd class="mono">{{x.proprietaryTransactionCode||'—'}}</dd></div><div><dt>{{t('bankAccountId')}}</dt><dd class="mono">{{x.bankAccountId}}</dd></div><div><dt>{{t('statementId')}}</dt><dd class="mono">{{x.bankStatementId}}</dd></div><div><dt>{{t('fingerprint')}}</dt><dd class="mono wrap">{{x.fingerprint}}</dd></div></dl></section>
              </div>
              <details class="raw-detail"><summary>{{t('sourceMetadata')}}</summary><pre>{{prettyJson(x.rawEntryJson)}}</pre></details>
            </div></td></tr>
          </ng-container>
        </tbody></table><div *ngIf="!transactions().length" class="empty">{{t('noTransactionMatches')}}</div></div>
      </section>
    </main>
  </div>
</div>`})
class App implements OnInit {
  readonly Math=Math;readonly Number=Number; private http=inject(HttpClient); language=signal<Language>((localStorage.getItem('finance-language') as Language)||'en'); tab=signal('dashboard');loading=signal(false);busy=signal(false);message=signal('');error=signal('');analytics=signal<Analytics|null>(null);imports=signal<ImportRow[]>([]);transactions=signal<Tx[]>([]);selectedTransaction=signal<Tx|null>(null);ledgerAccountId=signal('');ledgerFilterCategory=signal('');ledgerFilterSubcategory=signal('');ledgerDirection=signal('');ledgerFrom=signal('');ledgerTo=signal('');ledgerMin=signal('');ledgerMax=signal('');ledgerSearch=signal('');ledgerTotal=signal(0);accountMessage=signal('');categoryGroups=signal<CategoryGroup[]>([]);categoryDraft=signal('');categoryMessage=signal('');dashboardMonths=signal(1);dashboardInsight=signal<any|null>(null);monthlyOverview=signal<any|null>(null);overviewMonth=signal('');
  title=computed(()=>this.t(({dashboard:'overview',transactions:'rawValues',ledger:'ledger',monthly:'monthlyOverview',accounts:'accounts',imports:'imports',import:'uploadCamt'} as any)[this.tab()]));
  colors=['#166b5c','#e0a84b','#e16b5a','#6387ba','#8f78ad','#69a58b','#d98aa4','#7a8b98'];
  t(key:TranslationKey|string){return (UI[this.language()] as any)[key]||(UI.en as any)[key]||key}
  categoryText(value:string){return value.split(' / ').map(x=>categoryText(x,this.language())).join(' / ')}
  directionText(value:string){return ({Incoming:this.t('incoming'),Outgoing:this.t('outgoing'),'Transfer in':this.t('transferIn'),'Transfer out':this.t('transferOut')} as any)[value]||value}
  setLanguage(event:Event){const value=(event.target as HTMLSelectElement).value as Language;this.language.set(value);localStorage.setItem('finance-language',value)}  ngOnInit(){this.loadCategories();this.showDashboard()}
  showDashboard(){this.tab.set('dashboard');this.loading.set(true);this.error.set('');this.http.get<Analytics>('/api/v1/analytics/overview',{params:{months:this.dashboardMonths()}}).subscribe({next:x=>{this.analytics.set(x);this.loading.set(false)},error:x=>{this.error.set(x.error?.detail||this.t('loadDashboardError'));this.loading.set(false)}})}
  setDashboardPeriod(months:number){this.dashboardMonths.set(months);this.dashboardInsight.set(null);this.showDashboard()}
  periodLabel(){return this.dashboardMonths()===1?this.t('thisMonth'):this.dashboardMonths()+' '+this.t('months')}
  inspectKpi(title:string,value:number,currency:string,detail:string,ledger:any){this.dashboardInsight.set({title,value:this.money(value,currency),detail,ledger})}
  inspectCount(title:string,value:number,detail:string,ledger:any){this.dashboardInsight.set({title,value:value.toLocaleString(this.language()==='nl'?'nl-NL':'en-NL'),detail,ledger})}
  inspectMonth(m:Point,currency:string){this.dashboardInsight.set({title:this.monthLabel(m.period!),value:this.signedMoney(m.net,currency),detail:this.t('incoming')+' '+this.money(m.income,currency)+' / '+this.t('outgoing')+' '+this.money(m.expenses,currency),ledger:{period:m.period}})}
  inspectNamed(item:Named,type:string,currency:string,ledger:any){this.dashboardInsight.set({title:this.categoryText(item.name),value:this.money(item.total,currency),detail:type+' / '+item.count+' '+this.t('transactions').toLowerCase(),ledger})}
  inspectDay(day:any,currency:string){this.dashboardInsight.set({title:new Date(day.date+'T00:00:00').toLocaleDateString(this.language()==='nl'?'nl-NL':'en-NL'),value:this.money(day.value,currency),detail:this.t('dailyExpenseActivity')+' / '+(day.count||0)+' '+this.t('transactions').toLowerCase(),ledger:{from:day.date,to:day.date,direction:'debit'}})}
  inspectAccount(account:any){this.dashboardInsight.set({title:account.displayName||account.accountName||this.t('account'),value:this.money(account.balance,account.currency),detail:this.maskIban(account.iban),ledger:{accountId:account.id}})}
  openInsightLedger(filter:any){this.resetLedgerFilters();if(filter.accountId)this.ledgerAccountId.set(filter.accountId);if(filter.category)this.ledgerFilterCategory.set(filter.category);if(filter.search)this.ledgerSearch.set(filter.search);if(filter.direction)this.ledgerDirection.set(filter.direction);if(filter.from)this.ledgerFrom.set(filter.from);if(filter.to)this.ledgerTo.set(filter.to);if(filter.period){this.ledgerFrom.set(filter.period+'-01');this.ledgerTo.set(new Date(Number(filter.period.slice(0,4)),Number(filter.period.slice(5,7)),0).toISOString().slice(0,10))}if(!filter.from&&!filter.period&&this.analytics()?.rangeStart)this.ledgerFrom.set(this.analytics()!.rangeStart!);this.loadLedger()}
  refresh(){this.tab()==='dashboard'?this.showDashboard():this.tab()==='imports'?this.loadImports():this.tab()==='monthly'?this.loadMonthlyOverview():this.loadTransactions()}
  money(value:number|null|undefined,currency='EUR'){if(value==null)return 'â€”';if(currency==='MIXED')return new Intl.NumberFormat(this.language()==='nl'?'nl-NL':'en-NL',{maximumFractionDigits:2}).format(value)+' mixed';return new Intl.NumberFormat(this.language()==='nl'?'nl-NL':'en-NL',{style:'currency',currency:currency||'EUR'}).format(value)}
  signedMoney(v:number,c:string){return (v>=0?'+':'')+this.money(v,c)}
  shortMax(rows:Point[]){return Math.max(1,...rows.flatMap(x=>[x.income,x.expenses]))}
  barHeight(v:number,rows:Point[]){return Math.max(2,v/this.shortMax(rows)*100)}
  monthLabel(v:string){return new Date(v+'-01T00:00:00').toLocaleDateString(this.language()==='nl'?'nl-NL':'en-NL',{month:'short'})}
  total(rows:Named[]){return rows.reduce((a,b)=>a+b.total,0)}
  color(i:number){return this.colors[i%this.colors.length]}
  donut(rows:Named[]){let p=0;const sum=this.total(rows)||1;return `conic-gradient(${rows.slice(0,8).map((x,i)=>{const s=p;p+=x.total/sum*100;return `${this.color(i)} ${s}% ${p}%`}).join(',')})`}
  linePoints(rows:{balance:number}[]){const vals=rows.map(x=>x.balance),min=Math.min(...vals),max=Math.max(...vals),range=max-min||1;return rows.map((x,i)=>`${i/(rows.length-1||1)*800},${205-(x.balance-min)/range*185}`).join(' ')}
  areaPoints(rows:{balance:number}[]){return `0,220 ${this.linePoints(rows)} 800,220`}
  heatDays(rows:{date:string;value:number;count?:number}[]){const map=new Map(rows.map(x=>[x.date,x]));const max=Math.max(1,...rows.map(x=>x.value));const end=new Date((this.analytics()?.dataAsOf||new Date().toISOString().slice(0,10))+'T00:00:00');const start=new Date((this.analytics()?.rangeStart||end.toISOString().slice(0,10))+'T00:00:00');const days=Math.max(1,Math.round((end.getTime()-start.getTime())/86400000)+1),out=[];for(let i=days-1;i>=0;i--){const d=new Date(end);d.setDate(end.getDate()-i);const key=this.localDate(d),item=map.get(key),value=item?.value||0;out.push({date:key,value,count:item?.count||0,level:value===0?0:Math.min(4,Math.ceil(value/max*4))})}return out}
  percentOf(v:number,rows:Named[]){return v/Math.max(1,...rows.map(x=>x.total))*100}
  initials(v:string){return v.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()}
  maskIban(v?:string){return v?v.slice(0,4)+' â€¢â€¢â€¢â€¢ '+v.slice(-4):this.t('noIban')}
  upload(e:Event){const f=(e.target as HTMLInputElement).files?.[0];if(!f)return;this.busy.set(true);this.message.set('');const form=new FormData();form.append('file',f);this.http.post<any>('/api/v1/imports',form).subscribe({next:r=>{this.busy.set(false);this.message.set(r.count.toLocaleString()+' '+this.t('newImport'));setTimeout(()=>this.loadImports(),1200)},error:x=>{this.busy.set(false);this.message.set(x.error?.error||x.error?.detail||this.t('uploadFailed')+' ('+(x.status||'network')+')')}})}
  loadCategories(){this.http.get<CategoryGroup[]>('/api/v1/categories').subscribe(x=>this.categoryGroups.set(x))}
  subcategories(category:string){return this.categoryGroups().find(x=>x.name===category)?.subcategories||['Other']}
  categorySourceLabel(source?:number){return source===2?this.t('manual'):source===1?this.t('ibanRule'):this.t('automaticRecognition')}
  saveCategory(transaction:Tx,category:string,subcategory:string,applyToIban:boolean){this.http.put<any>('/api/v1/transactions/'+transaction.id+'/category',{category,subcategory,applyToIban}).subscribe({next:r=>{if(applyToIban&&transaction.counterpartyIban){for(const item of this.transactions())if(item.counterpartyIban===transaction.counterpartyIban){item.category=category;item.subcategory=subcategory;item.categorySource=1}}else{transaction.category=category;transaction.subcategory=subcategory;transaction.categorySource=2}this.transactions.set([...this.transactions()]);this.categoryMessage.set(r.affected+' '+this.t('categorySaved'))},error:x=>this.categoryMessage.set(x.error?.error||this.t('categorySaveError'))})}
  showAccounts(){this.tab.set('accounts');if(!this.analytics())this.showDashboard();else this.accountMessage.set('')}
  saveAccount(account:any,displayName:string,accountKind:string){this.http.put<any>('/api/v1/accounts/'+account.id,{displayName,accountKind:Number(accountKind)}).subscribe({next:updated=>{account.displayName=updated.displayName;account.accountKind=updated.accountKind;this.analytics.set({...this.analytics()!});this.accountMessage.set(this.t('accountSaved'))},error:x=>this.accountMessage.set(x.error?.error||this.t('accountSaveError'))})}
  flowHeight(value:number,rows:Point[]){const max=Math.max(1,...rows.flatMap(x=>[x.externalIncoming||0,x.externalOutgoing||0,x.transferIn||0,x.transferOut||0]));return value===0?0:Math.max(3,value/max*100)}
  loadMonthlyOverview(month?:string){this.tab.set('monthly');this.loading.set(true);const params:any={};if(month||this.overviewMonth())params.month=month||this.overviewMonth();this.http.get<any>('/api/v1/analytics/month',{params}).subscribe({next:x=>{this.monthlyOverview.set(x);this.overviewMonth.set(x.month);this.loading.set(false)},error:()=>{this.error.set(this.t('loadMonthlyError'));this.loading.set(false)}})}  changeOverviewMonth(event:Event){this.loadMonthlyOverview((event.target as HTMLInputElement).value)}
  availabilityText(value:string){const keys:any={'Credit utilization requires credit-limit data':'creditUtilizationUnavailable','Days until next paycheck requires a payroll schedule':'paycheckUnavailable','Payment method is not consistently supplied by CAMT':'paymentMethodUnavailable','Forecasts require more history and an explicit forecasting model':'forecastUnavailable'};return keys[value]?this.t(keys[value]):value}
  directionGroups(groups:any[],direction:string){return groups.filter(x=>x.direction===direction)}
  transferGroups(groups:any[]){return groups.filter(x=>x.direction==='Transfer in'||x.direction==='Transfer out')}
  monthFullLabel(month:string){return new Date(month+'-01T00:00:00').toLocaleDateString(this.language()==='nl'?'nl-NL':'en',{month:'long',year:'numeric'})}  loadImports(){this.tab.set('imports');this.loading.set(true);this.http.get<ImportRow[]>('/api/v1/imports').subscribe({next:x=>{this.imports.set(x);this.loading.set(false);if(x.some(i=>i.status===0||i.status===1))setTimeout(()=>this.loadImports(),2500)},error:()=>{this.error.set(this.t('loadImportsError'));this.loading.set(false)}})}
  goLedger(){this.resetLedgerFilters();this.loadLedger()}
  goAccount(accountId:string){this.resetLedgerFilters();this.ledgerAccountId.set(accountId);this.loadLedger()}
  goCategory(category:string){this.resetLedgerFilters();this.ledgerFilterCategory.set(category);this.loadLedger()}
  goSearch(search:string,direction=''){this.resetLedgerFilters();this.ledgerSearch.set(search);this.ledgerDirection.set(direction);this.loadLedger()}
  goDay(date:string){this.resetLedgerFilters();this.ledgerFrom.set(date);this.ledgerTo.set(date);this.loadLedger()}
  goPeriod(period:string,direction=''){const start=period+'-01';const end=new Date(Number(period.slice(0,4)),Number(period.slice(5,7)),0).toISOString().slice(0,10);this.resetLedgerFilters();this.ledgerFrom.set(start);this.ledgerTo.set(end);this.ledgerDirection.set(direction);this.loadLedger()}
  goRecentMonths(months:number,direction=''){const now=new Date();const start=new Date(now.getFullYear(),now.getMonth()-months+1,1);this.resetLedgerFilters();this.ledgerFrom.set(this.localDate(start));this.ledgerTo.set(this.localDate(now));this.ledgerDirection.set(direction);this.loadLedger()}
  localDate(date:Date){const y=date.getFullYear(),m=String(date.getMonth()+1).padStart(2,'0'),d=String(date.getDate()).padStart(2,'0');return `${y}-${m}-${d}`}
  resetLedgerFilters(){this.ledgerAccountId.set('');this.ledgerFilterCategory.set('');this.ledgerFilterSubcategory.set('');this.ledgerDirection.set('');this.ledgerFrom.set('');this.ledgerTo.set('');this.ledgerMin.set('');this.ledgerMax.set('');this.ledgerSearch.set('')}  loadLedger(){this.tab.set('ledger');this.loading.set(true);this.selectedTransaction.set(null);const params:any={page:1,pageSize:200};const values:any={accountId:this.ledgerAccountId(),category:this.ledgerFilterCategory(),subcategory:this.ledgerFilterSubcategory(),direction:this.ledgerDirection(),dateFrom:this.ledgerFrom(),dateTo:this.ledgerTo(),minAmount:this.ledgerMin(),maxAmount:this.ledgerMax(),search:this.ledgerSearch()};for(const key of Object.keys(values))if(values[key]!==''&&values[key]!=null)params[key]=values[key];this.http.get<any>('/api/v1/transactions',{params}).subscribe({next:x=>{this.transactions.set(x.items);this.ledgerTotal.set(x.total);this.loading.set(false)},error:()=>{this.error.set(this.t('loadLedgerError'));this.loading.set(false)}})}
  applyLedgerFilters(search:string,subcategory:string,direction:string,from:string,to:string,min:string,max:string){this.ledgerSearch.set(search);this.ledgerFilterSubcategory.set(subcategory);this.ledgerDirection.set(direction);this.ledgerFrom.set(from);this.ledgerTo.set(to);this.ledgerMin.set(min);this.ledgerMax.set(max);this.loadLedger()}
  clearLedgerFilters(){this.ledgerFilterCategory.set('');this.ledgerFilterSubcategory.set('');this.ledgerDirection.set('');this.ledgerFrom.set('');this.ledgerTo.set('');this.ledgerMin.set('');this.ledgerMax.set('');this.ledgerSearch.set('');this.loadLedger()}
  openLedgerCategory(x:Tx){this.selectedTransaction.set(this.selectedTransaction()?.id===x.id?null:x);this.categoryDraft.set(x.category||'Miscellaneous');this.categoryMessage.set('')}
  selectLedgerAccount(event:Event){this.ledgerAccountId.set((event.target as HTMLSelectElement).value);this.loadLedger()}
  loadTransactions(search=''){this.tab.set('transactions');this.loading.set(true);this.http.get<any>('/api/v1/transactions',{params:{page:1,pageSize:200,search}}).subscribe({next:x=>{this.transactions.set(x.items);this.loading.set(false)},error:()=>{this.error.set(this.t('loadTransactionsError'));this.loading.set(false)}})}
  toggleTransaction(x:Tx){this.selectedTransaction.set(this.selectedTransaction()?.id===x.id?null:x);this.categoryDraft.set(x.category||'Miscellaneous')}
  shortId(v:string){return v?v.slice(0,8)+'…':'—'}
  prettyJson(v:string){try{return JSON.stringify(JSON.parse(v),null,2)}catch{return v||this.t('noSourceMetadata')}}
  statusLabel(v:number){return [this.t('pending'),this.t('processing'),this.t('completed'),this.t('completedWarnings'),this.t('failed'),this.t('duplicate')][v]||this.t('unknown')}
}
bootstrapApplication(App,{providers:[provideHttpClient()]}).catch(console.error);
