using System.Globalization;
using System.Text.Json;
using System.Xml;
using System.Xml.Linq;
using FinanceInzicht.Application;
using FinanceInzicht.Domain;
namespace FinanceInzicht.Camt;
public sealed class CamtImporter : ITransactionSourceImporter
{
 public string SourceType=>"CAMT"; public const long MaxBytes=50*1024*1024;
 public async Task<ImportResult> ImportAsync(ImportContext context,Stream source,CancellationToken ct){if(source.CanSeek&&source.Length>MaxBytes)throw new InvalidDataException("XML exceeds maximum size."); using var limited=new LimitedStream(source,MaxBytes); var settings=new XmlReaderSettings{Async=true,DtdProcessing=DtdProcessing.Prohibit,XmlResolver=null,MaxCharactersInDocument=MaxBytes,MaxCharactersFromEntities=0,IgnoreComments=true}; using var reader=XmlReader.Create(limited,settings); var doc=await XDocument.LoadAsync(reader,LoadOptions.None,ct); var ns=doc.Root?.Name.NamespaceName??""; if(!ns.Contains("camt.053.001.",StringComparison.Ordinal)||!(ns.EndsWith(".02")||ns.EndsWith(".04")||ns.EndsWith(".08")))throw new InvalidDataException($"Unsupported CAMT namespace: {ns}"); XNamespace n=ns; var messageId=V(doc.Descendants(n+"MsgId").FirstOrDefault())??throw new InvalidDataException("Message ID missing."); var created=Dt(V(doc.Descendants(n+"CreDtTm").FirstOrDefault())); var statements=new List<ParsedStatement>(); var warnings=new List<ParsedWarning>();
 foreach(var s in doc.Descendants(n+"Stmt")){var sid=V(s.Element(n+"Id"))??throw new InvalidDataException("Statement ID missing."); var acct=s.Element(n+"Acct"); var iban=V(acct?.Element(n+"Id")?.Element(n+"IBAN")); var other=V(acct?.Element(n+"Id")?.Element(n+"Othr")?.Element(n+"Id")); var currency=V(acct?.Element(n+"Ccy"))??"XXX"; var account=new ParsedAccount(Normalization.Iban(iban),other,currency,V(acct?.Element(n+"Nm")),V(acct?.Element(n+"Svcr")?.Descendants(n+"BICFI").FirstOrDefault())??V(acct?.Element(n+"Svcr")?.Descendants(n+"BIC").FirstOrDefault())); var entries=new List<ParsedTransaction>();
 foreach(var e in s.Elements(n+"Ntry")){var amount=Dec(V(e.Element(n+"Amt"))); var indicator=V(e.Element(n+"CdtDbtInd"))=="CRDT"?CreditDebitIndicator.Credit:CreditDebitIndicator.Debit; var details=e.Descendants(n+"TxDtls").ToList(); if(details.Count==0)details.Add(new XElement(n+"TxDtls")); var entryRef=V(e.Element(n+"NtryRef")); foreach(var d in details){var refs=d.Element(n+"Refs"); var parties=d.Element(n+"RltdPties"); var agents=d.Element(n+"RltdAgts"); var cp=indicator==CreditDebitIndicator.Debit?parties?.Element(n+"Cdtr"):parties?.Element(n+"Dbtr"); var cpAcct=indicator==CreditDebitIndicator.Debit?parties?.Element(n+"CdtrAcct"):parties?.Element(n+"DbtrAcct"); var cpAgent=indicator==CreditDebitIndicator.Debit?agents?.Element(n+"CdtrAgt"):agents?.Element(n+"DbtrAgt"); var txAmount=d.Element(n+"AmtDtls")?.Descendants(n+"TxAmt").Descendants(n+"Amt").FirstOrDefault()??e.Element(n+"Amt"); entries.Add(new(entryRef,V(e.Element(n+"AcctSvcrRef")),V(refs?.Element(n+"InstrId")),V(refs?.Element(n+"EndToEndId")),V(refs?.Element(n+"MndtId")),V(refs?.Element(n+"TxId")),Date(V(e.Element(n+"BookgDt")?.Elements().FirstOrDefault()))??throw new InvalidDataException("Booking date missing."),Date(V(e.Element(n+"ValDt")?.Elements().FirstOrDefault())),details.Count>1?Dec(V(txAmount)):amount,V(txAmount?.Attribute("Ccy"))??currency,indicator,V(e.Element(n+"Sts")?.Elements().FirstOrDefault())??V(e.Element(n+"Sts")),string.Join('.',e.Element(n+"BkTxCd")?.Descendants().Where(x=>!x.HasElements).Select(x=>x.Value)??[]),V(e.Element(n+"BkTxCd")?.Descendants(n+"Prtry").FirstOrDefault()),V(cp?.Element(n+"Nm")),Normalization.Iban(V(cpAcct?.Descendants(n+"IBAN").FirstOrDefault())),V(cpAgent?.Descendants(n+"BICFI").FirstOrDefault())??V(cpAgent?.Descendants(n+"BIC").FirstOrDefault()),Normalization.Text(string.Join(' ',d.Element(n+"RmtInf")?.Elements().Select(x=>x.Value)??[])),V(e.Element(n+"AddtlNtryInf")),JsonSerializer.Serialize(new{entryRef,detailIndex=entries.Count}))); } if(details.Count>1)warnings.Add(new(sid,entryRef,"MULTI_DETAIL","Entry expanded into one transaction per TxDtls; detail amounts are preferred.",null)); }
 var balances=s.Elements(n+"Bal").ToList(); decimal? Bal(string code)=>balances.Where(b=>b.Descendants(n+"Cd").Any(x=>x.Value==code)).Select(b=>(decimal?)Dec(V(b.Element(n+"Amt")))).FirstOrDefault(); var from=Dt(V(s.Element(n+"FrToDt")?.Element(n+"FrDtTm"))); var to=Dt(V(s.Element(n+"FrToDt")?.Element(n+"ToDtTm"))); statements.Add(new(messageId,sid,account,created,from,to,Bal("OPBD"),Bal("CLBD"),JsonSerializer.Serialize(new{messageId,sid,namespaceName=ns}),entries)); }
 return new(statements,warnings); }
 static string? V(XObject? x)=>x switch{XElement e=>string.IsNullOrWhiteSpace(e.Value)?null:e.Value.Trim(),XAttribute a=>a.Value,_=>null}; static decimal Dec(string? x)=>decimal.Parse(x??"0",NumberStyles.Number,CultureInfo.InvariantCulture); static DateOnly? Date(string? x)=>DateOnly.TryParse(x,CultureInfo.InvariantCulture,out var d)?d:null; static DateTimeOffset? Dt(string? x)=>DateTimeOffset.TryParse(x,CultureInfo.InvariantCulture,DateTimeStyles.AssumeUniversal,out var d)?d.ToUniversalTime():null;
 sealed class LimitedStream(Stream inner,long max):Stream{long read; public override async ValueTask<int> ReadAsync(Memory<byte>b,CancellationToken ct=default){var n=await inner.ReadAsync(b,ct);read+=n;if(read>max)throw new InvalidDataException("XML exceeds maximum size.");return n;} public override int Read(byte[]b,int o,int c){var n=inner.Read(b,o,c);read+=n;if(read>max)throw new InvalidDataException("XML exceeds maximum size.");return n;} public override bool CanRead=>true;public override bool CanSeek=>false;public override bool CanWrite=>false;public override long Length=>throw new NotSupportedException();public override long Position{get=>read;set=>throw new NotSupportedException();}public override void Flush(){}public override long Seek(long o,SeekOrigin so)=>throw new NotSupportedException();public override void SetLength(long v)=>throw new NotSupportedException();public override void Write(byte[]b,int o,int c)=>throw new NotSupportedException();}
}
