using Oikonomis.Domain;
namespace Oikonomis.Application;
public interface IObjectStorage { Task PutAsync(string key,Stream content,string contentType,CancellationToken ct); Task<Stream> OpenReadAsync(string key,CancellationToken ct); Task<bool> ExistsAsync(string key,CancellationToken ct); }
public sealed record ImportContext(Guid ImportJobId,string FileName);
public sealed record ImportResult(IReadOnlyList<ParsedStatement> Statements,IReadOnlyList<ParsedWarning> Warnings);
public interface ITransactionSourceImporter { string SourceType {get;} Task<ImportResult> ImportAsync(ImportContext context,Stream source,CancellationToken ct); }
public sealed record ParsedAccount(string? Iban,string? OtherId,string Currency,string? Name,string? Bic);
public sealed record ParsedStatement(string MessageId,string StatementId,ParsedAccount Account,DateTimeOffset? CreatedAt,DateTimeOffset? From,DateTimeOffset? To,decimal? Opening,decimal? Closing,string RawJson,IReadOnlyList<ParsedTransaction> Transactions);
public sealed record ParsedTransaction(string? EntryRef,string? ServicerRef,string? InstructionId,string? EndToEndId,string? MandateId,string? TransactionId,DateOnly BookingDate,DateOnly? ValueDate,decimal Amount,string Currency,CreditDebitIndicator Indicator,string? Status,string? BankCode,string? ProprietaryCode,string? CounterpartyName,string? CounterpartyIban,string? CounterpartyBic,string? Remittance,string? AdditionalInfo,string RawJson);
public sealed record ParsedWarning(string? StatementId,string? EntryReference,string Code,string Message,string? XmlPath);
public static class Normalization { public static string? Iban(string? v)=>string.IsNullOrWhiteSpace(v)?null:string.Concat(v.Where(char.IsLetterOrDigit)).ToUpperInvariant(); public static string? Text(string? v)=>string.IsNullOrWhiteSpace(v)?null:string.Join(' ',v.Split((char[]?)null,StringSplitOptions.RemoveEmptyEntries)); public static string Fingerprint(Guid accountId,ParsedTransaction t){var s=string.Join('|',accountId,t.BookingDate,t.ValueDate,t.Amount.ToString(System.Globalization.CultureInfo.InvariantCulture),t.Currency.ToUpperInvariant(),t.Indicator,t.ServicerRef,t.EntryRef,t.EndToEndId,Iban(t.CounterpartyIban),Text(t.Remittance)?.ToUpperInvariant());return Convert.ToHexString(System.Security.Cryptography.SHA256.HashData(System.Text.Encoding.UTF8.GetBytes(s))).ToLowerInvariant();}}
